### ISSUE TITLE
Use facebook logo instead of a blue circle icon?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/contain-facebook#10]
I was testing this alongside the [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/?src=search) add-on to try and verify there would be no conflicts, and managed to set my custom facebook icon to a pair of glasses.
Not sure how difficult it'd be to add a Facebook logo icon to make it less vague "blue circle".

![facebook-en-gb](https://user-images.githubusercontent.com/557895/37740913-abd0997a-2d1c-11e8-8693-163a516565c3.png)
**Figure 1:** Default blue circle.

---

![menubar_and_facebook_-_log_in_or_sign_up](https://user-images.githubusercontent.com/557895/37740415-da5dc710-2d1a-11e8-880a-78f30abf6d46.png)
**Figure 2:** Custom fancy sunglasses, compliments of Multi-Account Containers customization.

**Comment by krystian3w** [comment]
In my opinion this is not duplicate container.

**Comment by krystian3w** [comment]
Maybe create CSS code to change image (logo) with userChrome.css file (file still works with Friefox Nigthtly 61).

**Comment by SoftVision-PaulOiegas** [comment]
As mentioned in #87, I think we're gonna have a fence icon for this container.

**Comment by maxxcrawford** [comment]
We went with the "fence" icon! 🙌
