### ISSUE TITLE
Feature request: Add `facebookcorewwwi.onion`

### ISSUE THREAD

**Issue by ExE-Boss** [mozilla/contain-facebook#111]
As can be read in [this Facebook release notes post](https://www.facebook.com/notes/protect-the-graph/making-connections-to-facebook-more-secure/1526085754298237/), which is linked from [the article about Tor on Cloudflare’s blog](https://blog.cloudflare.com/the-trouble-with-tor/), Facebook uses the <code title="Facebook Core World Wide Web Infrastructure">https://<wbr/>facebookcorewwwi<wbr/>.onion/</code> address for better user experience for users of the Tor browser.

**Comment by TanviHacks** [comment]
Note that Tor browser has First Party Isolation enabled, which helps mitigate cross-site tracking.

**Comment by luixxiul** [comment]
I usually access to onion sites on Firefox toggling the preference `network.dns.blockDotOnion` on `about:config`. I would love to see this feature available in the near future :-)

**Comment by Perflyst** [comment]
Will be fixed with #147

**Comment by luixxiul** [comment]
> Will be fixed with #147

Awesome! :-)

**Comment by groovecoder** [comment]
Thanks for the contribution. We are conducting some site audits now, and we will have make an effort to combine GitHub domain requests with domain lists from Disconnect and from other data-sets to come up with an expanded domain list to include in a single new release all at once.

I'm closing this issue for now, but labeling it with `domain-request` so we can look at all issues and PRs with that label when we expand our domain containment list.
