### ISSUE TITLE
Send list of jailed domains

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/contain-facebook#113]
This is to make the addon MAC Compatabile in Version 1.4.0 - 

Add functionality to send the list of “jailed” domains to other extensions.
If you receive a request for “jailed” domains from Multi Account Containers (MAC), return the list of domains currently jailed.

Do this before you check if a domain is assigned by MAC.  We may need to change this check, since MAC may not have enough time to unassign before we detect assignment.  We could change the assignment check to first check the MAC version.  If MAC is enabled && it is version less than 7.0.0, then check assignment.
https://github.com/mozilla/contain-facebook/blob/master/background.js#L177

**Comment by TanviHacks** [comment]
See also https://github.com/mozilla/multi-account-containers/issues/1182

**Comment by TanviHacks** [comment]
@stoically are you going to do the PR for this?

**Comment by stoically** [comment]
@TanviHacks yeah, can look into implementing it. Would be great if we could merge https://github.com/mozilla/multi-account-containers/pull/1131 in MAC (test only changes) beforehand so I can add in some tests too.

**Comment by jonathanKingston** [comment]
I'm going to look into this for now given it's high urgency. Would appreciate help in reviewing etc later.

**Comment by jonathanKingston** [comment]
```
  // due to the limitations in extensions, there isn't a way to know when the extension will be listening
  async function sendJailedDomainsToMACRecursive() {
    for (let i = 0; i < MAC_RETRY_COUNT; i++) {
      try {
        const response = await sendJailedDomainsToMAC();
        if (response) {
          return;
        }
      } catch (e) {
        // loop again
      }
    }
  }
```

There is the possibility of a race condition where both addons are installed on a slow machine, however I think we should hold off using this until/if we need it.

**Comment by TanviHacks** [comment]
@jonathanKingston what about this part from the first comment (below).  Should we skip it?  And instead, If we are in a case where the FC code is exectuing before MAC has time to unassign facebook domains, then read in the MAC assigned domains into FC and ignore them, like we did before?  Does that make sense?

>Do this before you check if a domain is assigned by MAC. We may need to change this check, since MAC may not have enough time to unassign before we detect assignment. We could change the assignment check to first check the MAC version. If MAC is enabled && it is version less than 7.0.0, then check assignment.
https://github.com/mozilla/contain-facebook/blob/master/background.js#L177

**Comment by jonathanKingston** [comment]
@TanviHacks the impact to MAC not listening the jailed domains currently is that the checkbox might still be assigned. However the extension will then fall back to its previous behaviour. Later we can rip this code out given that it shouldn't ever be possible in the future.

@SoftVision-PaulOiegas the cases I would test are ensuring that if extensions are in different orders, that the MAC assignment of Facebook is always disabled when Facebook is loaded. (when you open the MAC browser action the checkbox is disabled).
The other one I am concerned about is some form of race condition that brings back the startup issues of opening multiple of the same page.
