### ISSUE TITLE
CDN assignment cookie clearing

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/contain-facebook#117]
Filing this so we don't forget. In https://github.com/mozilla/contain-facebook/pull/114 we removed cookies only from unassigned sites in MAC.

However there is a flaw in that this code still will be clearing cookies for CDN URLS.

The suggestion was to treat all of the paths as part of the same property:
```
const FACEBOOK_DOMAINS = [
  ["facebook.com", "www.facebook.com", "fb.com", "fbcdn.net", "cdn.fbsbx.com"]
  ["instagram.com", "www.instagram.com"]
  ["messenger.com", "www.messenger.com"]
  ["atdmt.com"]
];
```

**Comment by TanviHacks** [comment]
This will go away in 1.4.0 when we fix compatibility with MAC.
