### ISSUE TITLE
Notify users when they have been moved into the facebook container

### ISSUE THREAD

**Issue by pauljt** [mozilla/contain-facebook#12]
I know this is the way contain facebook is supposed to work, but maybe somethjing to think about for future UX improvement. If you try to open a facebook link in any other tab, it silently gets forced into the facebook container. This is the behavior that we want, but its subtle and might confuse users, especially when they are just visiting something which isnt obviously facebook. (like my local cafe's web presence is just a facebook page for example). 

Maybe this is a UX request for containers in general though.

**Comment by maxxcrawford** [comment]
Now that the active Container is appended to the URL bar, this can be closed. 

<img width="152" alt="image" src="https://user-images.githubusercontent.com/2692333/85748179-7d012780-b6cd-11ea-8fcb-a3180f7a1520.png">
