### ISSUE TITLE
cannot login to blablacar.co.uk with facebook

### ISSUE THREAD

**Issue by demoklion** [mozilla/contain-facebook#121]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes
- Facebook Container Version: 1.3.0
- Operating System + Version: windows 10 pro v.1709 b.16299.309
- Firefox Version: 60.0b10 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:
ADB Helper	0.12.0	true	adbhelper@mozilla.org
Auto Tab Discard	0.2.2	true	{c2c003ee-bd69-42a2-b0e9-6f34222cb046}
Bookmark Dupes	5.7	true	bookmarkdupes@martin-vaeth.org
Compat Report	0.1.0	true	{13d75c08-fed6-4ff6-a356-d79509b17e44}
Facebook Container	1.3.0	true	@contain-facebook
Firefox Multi-Account Containers	6.0.0	true	@testpilot-containers
FormApps Extension	2.4.1.26	true	{69F080C9-A1D8-42F8-BD83-3D54D4BC81B3}
Hide W3Schools	1.1.1	true	@hide-w3schools
Live Server Web Extension	1.0.0	true	{cbdcd14f-ec92-4385-9119-549b5a5b5519}
Pushbullet	335	true	jid1-BYcQOfYfmBMd9A@jetpack
Shodan	0.3.2	true	jid1-AWt6ex5aPvWtTg@jetpack
Snooze Tabs	1.1.0	true	snoozetabs@mozilla.com
Test Pilot	2.0.8-dev-259fe19	true	@testpilot-addon
uBlock Origin	1.15.24	true	uBlock0@raymondhill.net
Web Developer	2.0.1	true	{c45c406e-ab73-11d8-be73-000a95be3b12}
Web Scrobbler	2.4.3	true	{799c0914-748b-41df-a25c-22d008f9e83f}
WhatRuns	1.7.0	true	{66d854c2-fd1b-4857-bd0a-7d220e4834da}
Adobe Acrobat	18.0.8	false	web2pdfextension.17@acrobat.adobe.com
Tab Suspender (memory saver)	0.2.6	false	{e225ac78-5e83-484b-a16b-b6ed0924212f}

### Issue
Facebook login doesn't work on [https://www.blablacar.co.uk/login](https://www.blablacar.co.uk/login)

### Actual behavior
Flashes some tiny window, then opens 

`https://www.facebook.com/v2.9/dialog/oauth?app_id=123152947759014&channel_url=https%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FFdM1l_dpErI.js%3Fversion%3D42%23cb%3Df1548417b2d412%26domain%3Dwww.blablacar.co.uk%26origin%3Dhttps%253A%252F%252Fwww.blablacar.co.uk%252Ff318e6f0e2bf92%26relation%3Dopener&client_id=123152947759014&display=popup&domain=www.blablacar.co.uk&e2e=%7B%7D&locale=en_US&origin=1&redirect_uri=https%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FFdM1l_dpErI.js%3Fversion%3D42%23cb%3Df23d41d9025826%26domain%3Dwww.blablacar.co.uk%26origin%3Dhttps%253A%252F%252Fwww.blablacar.co.uk%252Ff318e6f0e2bf92%26relation%3Dopener%26frame%3Df165f0615af9cc8&response_type=token%2Csigned_request&scope=email%2Cuser_birthday%2Cpublic_profile%2Cuser_friends&sdk=joey&version=v2.9` 

in the Facebook container in a new tab.

### Expected behavior
Opens a window to fill-in Facebook login (or just flashes it for a second, since I'm already logged in to Facebook), then closes the window and redirects me to blablacar.co.uk's main page.

### Steps to reproduce
1. Disable built-in Tracking Protection
2. click Continue with Facebook

### Notes
..

**Comment by TanviHacks** [comment]
Login with facebook does not always work with this extension.  If a third party uses login with facebook and acheives the login flow by using url parameters, this will work.  If not, then it will not.

This is by design - because if you logged in with facebook in your regular Container, then facebook would have your identity outside the Facebook Container.  The point of the extension is to make sure this doesn't happen.  This is also noted here - https://support.mozilla.org/en-US/kb/facebook-container-prevent-facebook-tracking#w_how-does-this-affect-facebookaos-features

**Comment by ryanfeeley** [comment]
@TanviHacks We have to do more to support the use case of adding other sites into the Facebook container. Firefox cannot become the browser that you can't use for Pinterest, Airbnb and the thousands of other sites that offer sign in with Facebook.
Add-ons do allow us to do what I've mocked up below, however websites load content from many domains. It will have to be smart about it.
<img width="546" alt="image" src="https://user-images.githubusercontent.com/68213/38578847-1ea8edc4-3cd3-11e8-8eec-5e13e9415010.png">

**Comment by demoklion** [comment]
@TanviHacks seems this issue is better described in #27, you can remove or merge this one with it.

**Comment by maxxcrawford** [comment]
We have this issue on going in #422. Closing this and adding the domain there to be included in testing. Thanks!
