### ISSUE TITLE
Add whatsapp domain to 1.4.0

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/contain-facebook#124]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No:
- Are you using Firefox in a Private Window? Yes/No:
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No:
- Facebook Container Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
..

### Expected behavior
..

### Steps to reproduce
1. ..
2. ..
3. ..

### Notes
..

**Comment by pdehaan** [comment]
I think this may just be reverting https://github.com/mozilla/contain-facebook/commit/cc8bddb8f7eccc99c309e979c56716b8a62edd3b

```
"whatsapp.com", "www.whatsapp.com", "web.whatsapp.com",
```

And possibly "cdn.whatsapp.net", per #104.
