### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ruiamar** [mozilla/contain-facebook#125]
Can't install. In page for installation appears this message: "This add-on requires a newer version of Firefox (at least version 57.0). You are using Firefox 52.0."

I see on about Firefox version: 59.0.2 

- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No:
- Are you using Firefox in a Private Window? Yes/No:
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No:
- Facebook Container Version: 1.3.1
- Operating System + Version: Windows 10
- Firefox Version: 59.0.2 
- User Agent: 	Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0
- Other installed Add-ons + Version + Enabled/Disabled-Status:
 Cookie AutoDelete	2.1.2	true	CookieAutoDelete@kennydo.com
Decentraleyes	2.0.3	true	jid1-BoFifL9Vbdl2zQ@jetpack
Disconnect	5.18.21	true	2.0@disconnect.me
DuckDuckGo Privacy Essentials	2018.3.23	true	jid1-ZAdIEUB7XOzOJw@jetpack
Facebook Video Downloader	0.189	true	{36ea170d-2586-45fb-9f48-5f6b6fd59da7}
Facebook Video Downloader	1.1	true	{9c46f52a-3d2e-4b5e-86ca-32b0353359ce}
Font Finder	0.1.8	true	{a658a273-612e-489e-b4f1-5344e672f4f5}
HTTPS Everywhere	2018.4.3	true	https-everywhere@eff.org
LanguageTool - Grammar and Style Checker	1.0.34	true	languagetool-webextension@languagetool.org
Privacy Badger	2018.4.10	true	jid1-MnnxcxisBPnSXQ@jetpack
Privacy Settings	0.3.4	true	jid1-CKHySAadH4nL6Q@jetpack
Share Backported	1.1.5	true	{1bab54e2-6c60-4ee1-88f7-52b1df77924f}
TextFilter	0.2	true	support@bookbinder.co
uBlock Origin	1.15.24	true	uBlock0@raymondhill.net
Wikiwand: Wikipedia Modernized	5.0.0	true	jid1-D7momAzRw417Ag@jetpack
3P Request Blocker	1.0.26.11	false	{62cc563c-de41-4627-968f-5557946c76fc}
Block Cloudflare MiTM Attack	1.0.14	false	{d86b44dd-ef12-4f28-ab1c-ea32664490ac}
Google Analytics Opt-out Add-on (by Google)	1.0.7	false	{6d96bb5e-1175-4ebf-8ab5-5f56f1c79f65}
HTTPS Everywhere	2018.4.3	false	https-everywhere-eff@eff.org
Mailvelope	2.2.0	false	jid1-AQqSMBYb0a8ADg@jetpack
Priberam - Dicionário On-Line da Língua Portuguesa	3.1.0.1-signed.1-signed	false	priberam@coelhonarede.com

### Actual behavior
..

### Expected behavior
..

### Steps to reproduce
1. ..
2. ..
3. ..

### Notes
..

**Comment by TanviHacks** [comment]
You can try copy/pasting this link to install: https://addons.mozilla.org/firefox/downloads/latest/facebook-container/platform:2/addon-954390-latest.xpi

(don't just click on it, copy and paste it into the url bar.

**Comment by ruiamar** [comment]
It worked. Thank you so much to you.
