### ISSUE TITLE
Make this localizable

### ISSUE THREAD

**Issue by peiying2** [mozilla/contain-facebook#134]
The localization communities are interested in localizing this. Please help prioritize.

**Comment by nukeador** [comment]
Hi,

I want to reinforce this message. 

I've found out this extension is not l10n friendly and can't be localized. It would be great to be l10n ready so we can localize in many other languages to extend its reach ;-)

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization

Context: I'm running a research on addons and localization to inform a campaign at Mozilla Open Innovation team and this was one of the extensions in our radar ;-)

**Comment by groovecoder** [comment]
This is done as of 1.6 release. Localization of the current UI strings is complete in 40+ languages(!) and is being done on Pontoon. https://pontoon.mozilla.org/projects/facebook-container/
