### ISSUE TITLE
Testing results for v1.4.0 build

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/contain-facebook#139]
Hi team,

We have performed a full day of testing on build v1.4.0, and we have also performed regression testing to see if the introduced changes didn’t break something else. Here are the testing results:

### **New issues** ###
1. #131 - The "View Image" context menu option no longer works for web.whatsapp.com
2. #136 - A confirmation page is wrongly displayed and "Facebook" and "Whatsapp" can be wrongly opened in another container if you previously assign them to FB container trough MAC
3. #137 - Facebook Bookmark can be opened in sidebar where Facebook Container has no influence
4. #138 - [MAC compatibility] You can wrongly open any website in the "Facebook" container if it was previously assigned to another container

### **Reopened issues** ###
1. #101 - The "web.whatsapp.com" page doesn't open in a Facebook Container if the website was visited before installing Facebook Container
This was not reopened yet because we don’t have the right to do it. Someone with access please reopen it.

### **Known issues** ###
1. #103 - You cannot log in with "Facebook" on Instagram, if it is assigned to a different container

### **Other observed scenarios** ###
These weren’t logged because we are unsure if they are intended behaviors or really issues.

1. Disabling and re-enabling Facebook Container clears all the logins on the contained domains.

## **QA recommendation** ##
Since we consider most of the issues mentioned above to be easily encountered by end users, from QA point of view, we suggest to **DO NOT SHIP** this version.

The suggested course of actions from QA side is:
- Try to find a better fix for #101 which still occurs after the current fix and is a blocker issue for this release. 
- Fix all the new issues found before releasing, except #137 which is clearly an edge case. 
- Also, the #138 could be the intended behavior in future since we are planning to allow users to add domains to the container, but not for this build.

**Comment by jonathanKingston** [comment]
- [ ] #131
- [ ] #136
- [ ] #137
- [ ] #138
- [ ] #101

**Comment by SoftVision-PaulOiegas** [comment]
@jonathanKingston we'll double check the 3 issues mentioned and reply back today. Thanks for the heads up.

**Comment by SoftVision-PaulOiegas** [comment]
@jonathanKingston Sory for the late reply but we had other tasks in progress today. We have re-verified all 3 issues that you mentioned to be fixed in #130 and all 3 are still reproducible. We have added comments on all 3.
