### ISSUE TITLE
Support isolation of other websites

### ISSUE THREAD

**Issue by pauljt** [mozilla/contain-facebook#14]
This is probably out of scope, but it would seem fairly trival to scale this addon to support other websites. At least in its current form. If we make this add-on more specific  (by blocking subresources etc) it will be less suited to the general isolation case, so maybe this feature request is better suited to Multi-account containers, but just wanted to throw it out there.

**Comment by pmac** [comment]
It would be nice, if feasible, to have a more general purpose version of this that would allow preferably any (or alternately a growing list) website to be walled-off like this. Or even, and I may already have discussed this elsewhere, doing the opposite and walling-off all websites until added to an allow-list for a more general purpose container type.

**Comment by Perflyst** [comment]
There is already such an addon, every new tab opened in a new container and specific rules for websites. It is called [Temporay Containers](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/).

**Comment by TanviHacks** [comment]
Out of scope for now.
