### ISSUE TITLE
Can't use facebook with this extension because loading issue

### ISSUE THREAD

**Issue by hgfeinau** [mozilla/contain-facebook#148]
When I open Facebook with my new container extension, the site opens but a second later the page darkens and a white box appears that is perpetually loading. This never successfully loads and facebook is unusable.

**Comment by maxxcrawford** [comment]
Is this still reproducible on the latest version of the add-on (2.1.1) and Firefox (77.0.1)?

**Comment by hgfeinau** [comment]
Things are working fine at the moment. The problem was a brief interlude.

**Comment by maxxcrawford** [comment]
@hgfeinau Thanks!
