### ISSUE TITLE
In Linux 64 bit do not detect correctly vesion of firefox

### ISSUE THREAD

**Issue by tdancs** [mozilla/contain-facebook#150]
![firefox](https://user-images.githubusercontent.com/18459852/39577513-12000b56-4ed1-11e8-8884-58d89184c2da.jpg)

**Comment by SoftVision-PaulOiegas** [comment]
Hi @tdancs and thanks for your report. Can you please navigate to `about:config` page and check if the `privacy.resistFingerprinting` preference is set to `true`? If yes, please change it to `false` and retry the installation.

**Comment by maxxcrawford** [comment]
Closing this issue for now. Thanks!
