### ISSUE TITLE
Container fails to match domains properly

### ISSUE THREAD

**Issue by Kylotan** [mozilla/contain-facebook#152]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: It says "Firefox will: Remember History"
- Are you using Firefox in a Private Window? Yes/No: No.
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes.
- Facebook Container Version: 1.3.1
- Operating System + Version: Windows 8.1
- Firefox Version: Firefox Quantum 59.0.3 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Facebook Container	1.3.1	true	@contain-facebook
Privacy Badger	2018.4.23	true	jid1-MnnxcxisBPnSXQ@jetpack
React Developer Tools	3.2.1	true	@react-devtools
Pocket	3.0.6.1-signed	false	isreaditlater@ideashower.com
REST Easy	0.3.1.1-signed	false	rest-easy@quickmediasolutions.com
SQLite Manager	0.8.3.1-signed.1-signed	false	SQLiteManager@mrinalkant.blogspot.com
Tab Groups	2.1.4	false	tabgroups@quicksaver

### Actual behavior
1. I am logged in to Facebook within the container, from previous use. However, when I visit Facebook.com from a new tab, it typically fails to open it in the Facebook container, and instead presents me with the Facebook login page, outside of any container.

2. If I then right-click one of the Facebook.com links on that page and choose 'open in new Container tab - Facebook', that link is correctly opened in the Facebook container and I see the page as a logged-in user. 

3a. If I then follow an external link from Facebook, it also opens in the Facebook container.

3b. If I type a new domain (e.g. www.reddit.com) into the URL of my Facebook tab, it opens it in the Facebook container.

### Expected behavior

Step 1 above should be opening in the FB container.
Step 3a should not be opening in the FB container.
Step 3b should not be opening in the FB container (unless this is by design)?

### Steps to reproduce

This is just how it works on my machine when following the above steps, being logged in to Facebook inside the container and then opening new tabs as above.

### Notes
I referred to this new issue at the end of my previous issue, here: https://github.com/mozilla/contain-facebook/issues/84

[about_support.txt](https://github.com/mozilla/contain-facebook/files/1977485/about_support.txt)

**Comment by maxxcrawford** [comment]
Is this still reproducible on the latest version of the add-on (2.1.1) and Firefox (77.0.1)?

**Comment by Kylotan** [comment]
No idea, it's 2 years later and I have no interest in testing anything relating to Facebook.

**Comment by maxxcrawford** [comment]
Thanks!
