### ISSUE TITLE
Getting HTTP 500 on messenger.com with contain-facebook installed.

### ISSUE THREAD

**Issue by GuillaumeRochat** [mozilla/contain-facebook#154]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: It's not greyed out, but it's ticked.
- Facebook Container Version: 1.3.1
- Operating System + Version: Arch Linux on 4.16 and Windows 10
- Firefox Version: Firefox 62 Nightly
- Other installed Add-ons + Version + Enabled/Disabled-Status: Easy-screenshot and uBlock Origin.

### Actual behavior
As soon as I enabled the addon, messenger.com would return 500 errors.
Removing the addon does not fix the issue, messenger.com still returns 500 errors.
Going in other browsers also has the issue (tried google chrome stable release on linux).

Before enabling the addon, messenger.com was working fine.

### Expected behavior
Enabling the addon does not prevent from going on messenger.com
The addon does not impact the behavior of other browsers.

### Steps to reproduce
1. Navigate to messenger.com
2. Notice that it works.
3. Install the addon.
4. Navigate to messenger.com
5. Notice that it does not work.
6. Remove the addon.
7. Navigate to messenger.com
8. Notice that it still does not work.

### Notes
I tried clearing the saved data for facebook.com but there was nothing for messenger.com. It did not change anything. Facebook.com works as intented.

**Comment by jnv** [comment]
I had the same issue yesterday, but it happened in other browsers too and it works today. I think it was some glitch affecting a few users, see if messenger.com works for you now.

**Comment by GuillaumeRochat** [comment]
@jnv You're right, it works now. But it is strange because I did load it before installing the addon on my Windows 10, I was on messenger.com, and as soon as I installed it stopped working. I'm assuming there was something wrong somewhere.
