### ISSUE TITLE
Log in with Facebook problem

### ISSUE THREAD

**Issue by lucaslsf** [mozilla/contain-facebook#156]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: **No**
- Are you using Firefox in a Private Window? Yes/No: **No**
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: **Yes**
- Facebook Container Version: **1.3.1**
- Operating System + Version: **macOS High Sierra 10.13.4 (17E202)**
- Firefox Version: **Firefox Quantum 59.0.2 (64-bit)**
- Other installed Add-ons + Version + Enabled/Disabled-Status:
**(All add-ons are enabled)
Adblock Plus	3.0.4
DuckDuckGo Privacy Essentials	2018.5.1
Facebook Container	1.3.1
LastPass: Free Password Manager	4.10.0.12
Pinterest Save Button	3.0.93
Raindrop.io: "Save Button" for Web	6.0.429
Reddit Enhancement Suite	5.12.2
Simple Translate	1.7.3**

### Actual behavior
When trying to use "login with Facebook" on some sites, like Pinterest, it doesn't work. A new window opens, with seemingly the same page as I came from, and from there when I try clicking again on "login with Facebook", the behavior repeats and a new window opens.

### Expected behavior
Be redirected to a page where I can login with Facebook, and go back to Pinterest, logged in.

### Steps to reproduce
1. Pinterest.com, try logging in with Facebook
2. New window opens up, try clicking "login with Facebook again"
3. Repeat

### Notes
I've had weird behaviours happening with other sites when trying to login with Facebook too. Some of the logins were created using Facebook and there's no other way to get a password/username, so I'm locked out of these services using Firefox

**Comment by ruppalsingh** [comment]
Please see the [project readme here](https://github.com/mozilla/contain-facebook#logging-in-or-creating-accounts-on-other-websites-using-facebook). To quote:

> Logging in or creating accounts on other websites using Facebook
Websites that allow you to create an account or log in using Facebook will generally not work properly.

This is not a bug - it's an intended side-effect.

**Comment by Bsoolius** [comment]
The open link in container is obsolete. If I want to log into soundcloud there is no way to add it to the container? Is there a file that contains the domains or websites that are permitted in the facebook container? It's like I am opening facebook in an incognito session, I can log in without a problem because that incognito session contains my facebook session. 

I'm not sure if I am making sense. I see it as a bug.

**Comment by theprojectsomething** [comment]
Given that using Facebook as an oAuth provider is so common and can be incorporated into a site without tracking code (i.e relying on redirects/url parameters only), is it possible to get either:
- code samples showing some secure workarounds (if they exist?), with caveats of course
- a standard way to check for the add-on (so as to show a warning or provide an alternative sign-in method)
