### ISSUE TITLE
Facebook container doesn't recognize the fb site when accessed

### ISSUE THREAD

**Issue by RatnaNihal** [mozilla/contain-facebook#158]
Dear Firefox,

I installed the facebook container extension and after doing so, firefox isn't recognizing that I'm accessing facebook. I don't see any icon on the firefox search bar as shown in the photo in the extension detail page.

**Comment by SoftVision-PaulOiegas** [comment]
Hi @RatnaNihal and thanks for yoru report. There is a set of questions when you log a new issue that help us a bit to debug the issues logged. I see you have skipped answering them. Can you please do it now so we can help you with the issue?

- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No:
- Are you using Firefox in a Private Window? Yes/No:
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No:
- Facebook Container Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:


After answering them, I'll help you to find out a solution for your problem. Thanks!

**Comment by RatnaNihal** [comment]
Hi Paul,

Thanks for the reply. I am answering the questions as per the order asked.

1. Yes, I have the never remember history option selected.
2. No, I wasn't using private mode.
3. Yes, am able to see.
4. Facebook container 1.3.1
5. Windows 10 Enterprise, 1607, 64 bit OS
6. 60.0.1 (32-bit)
7. No, don't have any other add-ons.

Thanks.

**Comment by SoftVision-PaulOiegas** [comment]
Thanks for answering! 😃 From the first answer we know exactly what the problem is.
> 1. Yes, I have the never remember history option selected.

I'm afraid that using this option makes Facebook Container useless. This option makes your browser behave like it is always in Private Mode (Private Window) and Facebook Container is not working in that mode since you are already not storing any cookies between sessions.
