### ISSUE TITLE
Allow users to add additional domains for this container

### ISSUE THREAD

**Issue by sorinello** [mozilla/contain-facebook#164]
Besides the hardcoded FACEBOOK_DOMAINS variable, allow the users to add their own domains to be included.

Use case: 
1) User wants to allow integration with facebook for certains websites
2) User wants to login using facebook for certain sites

**Comment by NewAlexandria** [comment]
For this, I have been adding those certain sites to the FB container plugin's code.  [See the discussion here](https://github.com/mozilla/contain-facebook/pull/159#issuecomment-418605969)

**Comment by NewAlexandria** [comment]
What additional domains are you thinking?  What is the use case?

**Comment by gaganpreet** [comment]
I'm also interested in this feature. I use Facebook auth in some places and I need to keep using it. If I try "Reopen in container -> Faceboook", the extension doesn't respect that and re-reopens the tab in the original container.

The workaround I'm using for now:

* Disable this extension
* Navigate to the site in a new tab, and set the third party domain to always open in Facebook container
* Enable extension again

**Comment by NewAlexandria** [comment]
Same.  It's been a few months, and I just keep patching my own fork and then using that one in my browser.  Same with Contain Google, and the google apps for drive, etc.

**Comment by 0x3333** [comment]
Well, I managed to add a website to Facebook Container:

1 - Inspect the Facebook Container AddOn: about:debugging#/runtime/this-firefox
2 - Click "Inspect" in the Facebook Container
3 - Go to tab "Console" and type: addDomainToFacebookContainer("https://api.whatsapp.com")

You added https://api.whatsapp.com to the URLs in the Facebook Container, now I can use the API without Facebook Container blocking it.

**Comment by maxxcrawford** [comment]
Update: Our team is on track to have this feature sent to QA next week. Follow along on the progress on Issue #422. 

Duplicate of #422
