### ISSUE TITLE
Facebook Not Contained

### ISSUE THREAD

**Issue by leoleson** [mozilla/contain-facebook#169]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No:
No

- Are you using Firefox in a Private Window? Yes/No:
No

- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No:
Yes

- Facebook Container Version:
1.3.1

- Operating System + Version:
macOS 10.13.6

- Firefox Version:
61.0.1

- Other installed Add-ons + Version + Enabled/Disabled-Status:
Adblock Plus	3.2	true	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
DuckDuckGo Privacy Essentials	2018.7.18	true	jid1-ZAdIEUB7XOzOJw@jetpack
Facebook Container	1.3.1	true	@contain-facebook
Grammarly for Firefox	8.827.1725	true	87677a2c52b84ad3a151a4a72f5bd3c4@jetpack
LastPass: Free Password Manager	4.15.2.17	true	support@lastpass.com
Privacy Badger	2018.7.18.1	true	jid1-MnnxcxisBPnSXQ@jetpack
Proxy SwitchyOmega	2.5.17	true	switchyomega@feliscatus.addons.mozilla.or

### Actual behavior
Open a new tab
Navigate to Facebook
Blue bar no longer appears along the bottom of the tab
Suggested Posts are once again populating my feed

I've disabled, deleted Facebook Container
Quit and restarted Firefox
Reinstalled Facebook container
That didn't fix the issue.

**Comment by SoftVision-PaulOiegas** [comment]
Hi @leoleson and thanks for your report! Is there any chance that you have `privacy.resistFingerprinting` set to `true` in `about:config` page? That could interfere with the extension.

**Comment by leoleson** [comment]
It’s set to false.  See the attached.

**Comment by leoleson** [comment]
I uninstalled Firefox and deleted the Firefox folder from ~Library/Application Support.  I then downloaded the current Firefox installer and reinstalled it.  I added back my extensions and Facebook Container is working normally again.
