### ISSUE TITLE
This Add-on is not showing up on Firefox mobile

### ISSUE THREAD

**Issue by jefferysmall** [mozilla/contain-facebook#176]
I have this add-on installed on the desktop with no problems.  When I try to load it onto my Firefox App  (62.0.1) on my android phone 6.0), it does not show up in a search.  Is there some reason that it is blocked from installation on the mobile app?  If not, what is the installation procedure?

**Comment by SoftVision-PaulOiegas** [comment]
Hey @jefferysmall , the Facebook-Container app was implemented for Desktop only. I don't know if there will be a mobile version in the future.

**Comment by jefferysmall** [comment]
Thanks @SoftVision-PaulOiegas.  I was wondering about this, but didn't see any specific mention.  I'll assume this is the case in the future when apps don't appear on the mobile version.  Regards.

**Comment by ooglyhLL** [comment]
Check out https://github.com/NewAlexandria/contain-facebook (a fork which unfortunately isn't quite up-to-date). It does work with the Android version. Would it be possible to merge relevant differences?
