### ISSUE TITLE
Facebook Contain lost all off my fecebook tabs

### ISSUE THREAD

**Issue by DavidFirefox** [mozilla/contain-facebook#180]
Hello,
When I have install the add-on all of my facebook tabs have go out.
How can I restore them ?
I think the plugin have to advertise user before touching existing tabs.
Visibly the deactivation of the plugin remove all facebook tabs too.

This plugin is very dangerous ...

I hope you have make a backup on my computer before editing my existing tabs.
Thanks in advance
David

**Comment by earthbound19** [comment]
This is by design. The page that lists this add-on and the README.md in this repository both explain that when you install this add-on it logs you out of facebook and destroys all facebook-related data in the browser. That's to get a "clean slate" and stop all facebook-related tracking outside of the new facebook container tab.

It sounds like you are saying the add-on itself should warn you before doing this, however. I agree.

**Comment by groovecoder** [comment]
👍 @earthbound19 the AMO page says "Installing this extension deletes your Facebook cookies and logs you out of Facebook."

**Comment by DavidFirefox** [comment]
Hello,
Thanks for your answers.
@groovecoder "Installing this extension deletes your Facebook cookies and logs you out of Facebook.". I'm sorry but this sentence don't tell about tabs. It tell "logs out".
For me log out is not close tabs, what do you think ?
If I log out to facebook my existing tabs are still alive. I don't see how log out to a website close tabs on firefox.
Sorry if my post is not precise (I'm not very good in English).
I would say this add-on have remove my facebook tabs. If it just logout, it's not a problem, I just have to login in a new tab, and it ok for all of existing tabs when I reload it. It is more clear for you ?

@earthbound19, thanks. 
Ok, but I thinks "facebook-related data" not include closing firefox tabs with facebook.
I thinks it can be a good idea to put it precisely.
I understand why this plug-in work with creating new tabs.
Can you say me where is the log ?
The plugin check that all news tabs are correctly created ?

I hope you re open this ticket with this news elements.
Have a good day
Thanks in advance

**Comment by groovecoder** [comment]
Ah, thanks @DavidFirefox - I've added that text to the AMO page:

"Installing this extension *closes your Facebook tabs*, deletes your Facebook cookies, and logs you out of Facebook."
