### ISSUE TITLE
The page isn’t redirecting properly

### ISSUE THREAD

**Issue by simivar** [mozilla/contain-facebook#186]
- Are you using Firefox in a Private Window? No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes
- Facebook Container Version: 1.4.1
- Operating System + Version: Windows 10 
- Firefox Version: 63.0.1 (64 bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Extensions
Name 	Version 	Enabled 	ID
Dark Reader	4.6.12	true	addon@darkreader.org
Facebook Container	1.4.1	true	@contain-facebook
NordVPN Proxy Extension - Privacy & Security	0.9.21	true	nordvpnproxy@nordvpn.com
uBlock Origin	1.17.2	true	uBlock0@raymondhill.net
xPath Finder	0.9.6	true	{62c1d54c-f371-4d89-8e07-69e67c8ebea8}
Kaspersky Protection	5.1.94.28d-20180412184251	false	light_plugin_A07576A3CEBC4A72A8CF2C925907DB05@kaspersky.com

### Actual behavior
Error "The page isn’t redirecting properly" when clicking on link ~~in Messenger~~ on Facebook.

For example: https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.doctrine-project.org%2Fprojects%2Fdoctrine-orm%2Fen%2F2.6%2Fcookbook%2Fcustom-mapping-types.html%3Ffbclid%3DIwAR2Gn1YR9nr7UKFAUi0JaQLnjpLuereJflEZOaGDL9fIjDfxYql5x9b1HlQ&h=AT3ZqTVXotgxpwZSeFU0XpONs32QLxWPCVI1LZpMcfXA8oOwHVtJbPKo1ktGNgYhHzL701mEF6GGKCDdB0NkVinPBD5ygraz_aLdG4zMIh-nALF9YamkbRIjTDXxb1AjZBaY

### Expected behavior
Redirection to linked page.

### Steps to reproduce
1. Find link ~~in messenger~~ on Facebook to ANY SITE. 
2. Click on the link.

### Notes
It stopped working after updating  Facebook Container to 1.4.1

**Comment by barryHD** [comment]
I'm also running into this issue since updating this morning.

**Comment by lucasberti** [comment]
Working fine on 1.4.2.

**Comment by groovecoder** [comment]
Thanks for the report @simivar. We think we have this fixed in 1.4.2, which I just pushed to AMO this morning. Can you check for addon update(s) and try again on 1.4.2?

**Comment by simivar** [comment]
Indeed version 1.4.2 has fixed the problem. I wonder why it updated my container to 1.4.1 and not 1.4.2 straight away. 

Thanks for such fast reply @groovecoder
