### ISSUE TITLE
contain F8.com

### ISSUE THREAD

**Issue by derpmarine168** [mozilla/contain-facebook#189]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? No:
- Are you using Firefox in a Private Window? No:
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes:
- Facebook Container Version: 1.4.2

### Actual behavior
does not contain f8.com
### Expected behavior
contains f8.com in facebook container
### Steps to reproduce
1. go to f8.com
1. watch as it doesn't go into a container.

**Comment by nemoload** [comment]
@groovecoder Should I add this domain?

**Comment by groovecoder** [comment]
Thanks for the contribution. We are conducting some site audits now, and we will have make an effort to combine GitHub domain requests with domain lists from Disconnect and from other data-sets to come up with an expanded domain list to include in a single new release all at once.

I'm closing this issue for now, but labeling it with `domain-request` so we can look at all issues and PRs with that label when we expand our domain containment list.
