### ISSUE TITLE
Middle-click on a facebook link opens in a foreground tab (instead of background)

### ISSUE THREAD

**Issue by pauljt** [mozilla/contain-facebook#19]
Middleclicking a facebook link results in a new facebook tab container which then gets focus. In the middle click case, the tab usually loads in the background.  Maybe we WANT the foreground to show the container switch, but it feels a bit janky as a user used to middle clicking links.

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Facebook Container (v1.2.5) on latest Firefox Release 59.0.2 (both official version and unbranded one), on Windows 10 x64, Mac 10.13.3 and Ubuntu 14.04 x64. The Facebook links are opened in foreground tabs with the middle-click mouse button.
