### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jbrooks036** [mozilla/contain-facebook#193]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No:
- Are you using Firefox in a Private Window? Yes/No:
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No:
- Facebook Container Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
..

### Expected behavior
..

### Steps to reproduce
1. ..
2. ..
3. ..

### Notes
..

**Comment by groovecoder** [comment]
This add-on isn't yet sufficient to protect you from Facebook's "shadow profiling". But that's definitely something we're considering and looking at now.

**Comment by maxxcrawford** [comment]
I'm closing this issue, but would like to provide a quick update. 

- As of last June, the 2.X version of this add-on blocks all Facebook assets outside of the Facebook Container, which should resist shadow profiling. 
- Developments within Enhanced Tracking Protection (inside of Firefox) also combat shadow profile building (and fingerprinting).
