### ISSUE TITLE
Diasbles messenger

### ISSUE THREAD

**Issue by MohamedRadwan** [mozilla/contain-facebook#194]
I have noticed that when the extension is enabled messenger cannot be reached. Through Facebook or its when visiting messenger.com

**Comment by fredrikbryntesson** [comment]
Also search suggestions and autocompleting when searching is broken.

**Comment by telmer6** [comment]
Messenger seems to work for me, both via the website and Facebook. @MohamedRadwan , you may want to provide a list of other extensions to help Mozilla troubleshoot.

**Comment by MohamedRadwan** [comment]
@telmer6 I disabled all my extensions to try to troubleshoot the issue and seems to be fro this extension. It has only been occurring recently and on and off.

**Comment by peterkydas** [comment]
I've just hit this issue as well after updating to Firefox 66.0. Will crash the tab if Messenger is opened in facebook.com or if visiting messenger.com. Disabled all other add-ons and it appears to be this one causing the issue.

**Comment by stoically** [comment]
Just to be sure - if you disable Facebook Container (will remove cookies) messenger works without problems? If that's the case, could you please try the following (with FC disabled):

- Install https://addons.mozilla.org/firefox/addon/multi-account-containers/
- Long-click on the new tab button until a list of containers appears
- Click "Personal", which opens a new container tab
- Login to facebook/messenger and check if the bug still happens

**Comment by peterkydas** [comment]
Sorry for the late reply. It worked sporadically without FB Container and all add-ons disabled. I re-enabled FB Container and tried again just now and everything seems to be working. I'm not too sure what's going. Maybe FB doing some testing on bypassing these things? I haven't updated Firefox either.
