### ISSUE TITLE
Provide a way to open Facebook links outside Facebook Container

### ISSUE THREAD

**Issue by hackel** [mozilla/contain-facebook#198]
Currently there is no way to open a facebook.com link outside of the Facebook container.  As this is a privacy-oriented extension, this is a concern because sometimes I wish to view Facebook links without being logged in and allowing them to track what I have viewed and associating it with my user profile.  I don't know if it's currently possible to detect, but if I explicitly choose to open a Facebook.com link in a container other than the Facebook container (or "No Container"), it should do what I tell it, instead of always opening it in the Facebook container (which should still happen when I blindly click on a link).

**Comment by jrgifford** [comment]
If you right click and choose "Open Link in New Private Window" it does that, but selecting another container will force it to be in the Facebook container.

**Comment by stoically** [comment]
It's not possible to get the "origin" of a request in the `webRequest.onBeforeRequest` API used by Facebook Container. This would need platform support similar to [webNavigation.TransitionType](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/TransitionType).

However, with Multi-Account Containers you could assign Facebook to "Always open in" a container and the confirm page lets you choose if you want to open in the current or the assigned container, though it doesn't have the feature to contain external links [yet](https://github.com/mozilla/multi-account-containers/issues/847).
