### ISSUE TITLE
Multiple Facebook Acounts

### ISSUE THREAD

**Issue by cweinhofer** [mozilla/contain-facebook#199]
I need to know how to create multiple Facebook containers.

I just installed "Facebook Container" and set it up with my personal Facebook account. Now I want to create a second container for my work Facebook account. But I can't find any information about how to do that with the "Facebook Container" extension. I know I can set up a new generic container with the "Multi-Account Containers" extension, but that container won't have the "Facebook Container" specific features, right?

Also, if I do manage to get two Facebook containers set up, how does the browser know which container to use if I click on a Facebook link?

**Comment by groovecoder** [comment]
You should use Multi-Account Containers for this. You can assign facebook.com to always open into one of your containers. When you click on a Facebook link, it will ask you which container to use.

![image](https://user-images.githubusercontent.com/71928/53029164-e44dfe00-342d-11e9-996c-f82f17cf0894.png)

Just leave the "Remember my decision for this site" un-checked.

**Comment by cweinhofer** [comment]
Just to confirm, in doing what you suggested, I will gain the ability to have multiple FB containers, but loose the special features of "Facebook Container", right?

Also, should I disable "Facebook Container"? I tried doing something like what you suggested but "Facebook Container" recreated it's default FB container and continued grabbing FB links. The containers I created in "Multi-Account Containers" became effectively useless.

**Comment by groovecoder** [comment]
Correct - with multiple facebook accounts you'll have a better experience if you delete the Facebook Container add-on and just use Multi-Account Containers instead.

You *will* lose some of the Facebook Container features like automatically containing other Facebook domains, and stripping `fbclid` click-tracking params. So you will lose some of those protections.

**Comment by cweinhofer** [comment]
Thanks for the clarification. Just for my and other's reference, is there any discussion about enhancing "Facebook Container" to accommodate multiple accounts or will using "Multi-Account Containers" be the recommended solution going forward?

**Comment by groovecoder** [comment]
A little discussion, but the challenges making Facebook Container multi-account are harder than making Multi-Account containers Facebook-aware. :)

**Comment by cweinhofer** [comment]
I can imagine. Actually, after having tried to set up the same site in multiple containers, it seems that Multi-Account Containers doesn't actually handle multiple accounts very well either. 😟

The solution you mentioned above seems to do okay if you have an account split between your default container and a second one, but things start to fall apart of you use two non-default containers or more than two containers.

All that to say, thanks for the work you and other contributors are putting into improving stuff with the containers feature.
