### ISSUE TITLE
Quite strange problem with comments Facebook Container

### ISSUE THREAD

**Issue by Isakku** [mozilla/contain-facebook#210]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? No
- Are you using Firefox in a Private Window? No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes
- Facebook Container Version: 1.3.1
- Operating System + Version:  Linux Mint KDE 18.3
- Firefox Version:  65.0.1 (64-bit) Firefox for Linux Mint
- Other installed Add-ons + Version + Enabled/Disabled-Status: 

Nombre 	Versión 	Activada 	ID
Facebook Container	1.3.1	true	@contain-facebook
Privacy Pass	1.0	true	{48748554-4c01-49e8-94af-79662bf34d50}
Save PDF	0.1	true	{077f4ca9-a296-4624-9524-4e9b3835f512}
SetupVPN - Lifetime Free VPN	3.5.6	true	@setupvpncom

### Actual behavior
Sometimes I cannot write comments in Facebook!

### Expected behavior
I should be able to comments stuff on Facebook, this strange behavior is just a problem I have had recently, I asked FB for help but they didn't say anything. 

### Steps to reproduce
1. ..Open Facebook
2. ..Comment on a post
3. ..FAIL!

### Notes
..I don't know why the extensions button is grayed out, but the "solution" given for that here
http://forums.mozillazine.org/viewtopic.php?f=8&t=2859365
 doesn't work 
kb.mozillazine.org/Locking_preferences
doesn't load.

**Comment by stoically** [comment]
Could you check the "Network"-tab in the developer tools (Ctrl+Shift+I) and see if there are failed requests (these should be red and have a "status" number starting with 4/5) when you try to comment and it doesn't work? If so, please provide a screenshot of the failed requests.

**Comment by Isakku** [comment]
Quite strange. All of them are either blank or have a 200 green status, none of them look to have a 4 or 5 numbered status, and yet my comments arent going throuhg, they always stay gray as if it were taking a long time, but no matter how long I wait, nothing happens.
![fbcommenterrorscreenshot_2019-03-03 josue cortez zarate](https://user-images.githubusercontent.com/16464336/53704197-d8c8e280-3df0-11e9-9943-4a19c8153258.png)

**Comment by stoically** [comment]
Thanks for checking. If I had to guess I'd say that it probably has something to do with the "SetupVPN" Add-on, if you're using it on Facebook. Are you able to test without it?

Facebook Container only intercepts "main_frame" requests - those happen basically if you enter something into the address bar and not when writing comments which are "xmlhttprequest" requests. So it's highly unlikely that Facebook Container is at fault here.

**Comment by Isakku** [comment]
SetupVPN Add-on Just installed it, never used it.
I just disabled all extensions except the Facebook container. No luck, this is still happening.

**Comment by Isakku** [comment]
I think what we really need is a way to clear or reset whatever is inside the Facebook Container addon.

**Comment by Isakku** [comment]
I think what we really need is a way to clear or reset whatever is inside the Facebook Container addon.
Oh, and BTW, the extension has received an update... I just noticed it and applied it.
