### ISSUE TITLE
Like button in this website went through the container

### ISSUE THREAD

**Issue by MarcSallent** [mozilla/contain-facebook#211]
If I understood it correctly, the Like button should not appear outside of Facebook, right?

The like button in this site loads with no problem: [http://hereistoday.com/](http://hereistoday.com/)

- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: **No**
- Are you using Firefox in a Private Window? Yes/No: **No**
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: **Yes**
- Facebook Container Version: **1.4.2**
- Operating System + Version: **OS X El Capitan, 10.11.6**
- Firefox Version: **65.0.1 (64-bit)**
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Bitly | Unleash the power of the link	3.0.4	true	extension@bitly.com
Facebook Container	1.4.2	true	@contain-facebook
Feedly Subscribe Button	0.9.0	true	{a8ffd15d-67d0-427f-80ad-07a7d76431e1}
Firefox Color	2.1.2	true	FirefoxColor@mozilla.com
Google Search "View Image" Button	1.5	true	{23cc126f-bd98-4a53-807a-cbc9af2cfe89}
Greasemonkey	4.7	true	{e4a8a97b-f2ed-450b-b12d-ee082ba24781}
Price Wise	21.0.0	true	shopping-testpilot@mozilla.org
Pushbullet	344	true	jid1-BYcQOfYfmBMd9A@jetpack
Reddit Enhancement Suite	5.14.5	true	jid1-xUfzOsOFlzSOXg@jetpack
Table to Excel	3.3	true	{3602c84f-cc0a-4bb2-a357-f533cc6b24fb}
Test Pilot	3.0.6vffecb95	true	@testpilot-addon
The Camelizer	2.10	true	izer@camelcamelcamel.com
uBlock Origin	1.18.4	true	uBlock0@raymondhill.net
Block Site	0.1.9	false	{54e2eb33-18eb-46ad-a4e4-1329c29f6e17}
Google Translate for Selected Text	1.8.20	false	{8cda9ce6-7893-4f47-ac70-a65215cec288}

### Actual behavior
The Facebook Like button loads bypassing this addon [http://hereistoday.com/](http://hereistoday.com/)

### Expected behavior
The Facebook Like button to not to load

### Steps to reproduce
1. Go to [http://hereistoday.com/](http://hereistoday.com/)
2. See the button at the bottom left corner

**Comment by stoically** [comment]
The Add-on does not prevent loading of Like/Share-Buttons on non-Facebook websites outside of the Facebook Container. However, the cookies connected with your logged-in account in the FC are not available in this case (different container) and so Facebook can't (or it's at least harder) link the visit to the website with your Facebook account (as long as you don't click the button).

**Comment by maxxcrawford** [comment]
@MarcSallent With the release of [https://github.com/mozilla/contain-facebook/releases](2.0), like, share and other SDK-dependent buttons are blocked and disabled outside of the Facebook container.
