### ISSUE TITLE
The wrong webextension menupanel image is displayed

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/contain-facebook#217]
**[Affected versions]:**

- Firefox 65.0.2 (BuildId:20190225143501).
- Firefox 66.0 (BuildId:20190314174725).
- Firefox 67.0b3 (BuildId:20190318154932).
- Firefox 68.0a1 (BuildId:20190318213844).

**[Affected Platforms]:**

- Windows 10 64bit
- macOS 10.13
- Ubuntu 16.04 64bit

**[Steps to reproduce]:**

1. Launch Firefox.
2. Install Facebook Container 1.6.0
3. Observe the Webextension menupanel's image.

**[Expected result]:**

The menupanel's image is displayed as in: https://mozilla.invisionapp.com/share/NCQW7QI4FM9#/screens/350966779

**[Actual result]:**

The wrong Webextension menupanel image is displayed.

**[Additional Notes]:**
Attached screenshots for this:.

Light theme:
![ic](https://user-images.githubusercontent.com/28087895/54605961-28471980-4a53-11e9-9bce-e2edfe598bcc.png)
Dark theme:
![ic2](https://user-images.githubusercontent.com/28087895/54605974-34cb7200-4a53-11e9-9922-b54f55c70329.png)

**Comment by emilghittasv** [comment]
Also, the following webextension menupanel image is displayed after the user accesses the Facebook webpage for the first time: 
![wt](https://user-images.githubusercontent.com/28087895/54607514-3139ea00-4a57-11e9-8d7b-0620947f86a2.png)

**Comment by groovecoder** [comment]
@emilghittasv I'm looking into this. For what it's worth - yes the blue icon badge is intentional.

**Comment by stoically** [comment]
Maybe adding an `!` instead of a whitespace for the badge looks more like it's intended?

**Comment by groovecoder** [comment]
Good idea! @arthur-mozilla - what do you think?
