### ISSUE TITLE
Facebook Container's panel displays horizontal and vertical scrollbars if opened via the Overflow Menu

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/contain-facebook#219]
**[Affected versions]:**

- Firefox 65.0.2 (BuildId:20190225143501).

**[Affected Platforms]:**

- Windows 10 64bit
- macOS 10.13

**[Unaffected Platforms]:**
- Ubuntu 16.04 64bit

**[Steps to reproduce]:**

1. Launch Firefox.
2. Install Facebook Container 1.6.0
3. Pin Facebook Container toolbar button to Overflow Menu
4. Open Facebook Container via Overflow Menu

**[Expected result]:**

The Facebook Container panel is successfully displayed.

**[Actual result]:**

Horizontal and Vertical scrollbars are displayed even though the content successfully fits inside the panel and the scrollbars are not needed.

**[Additional Notes]:**
Attached screenshots for this:.
![scrollbar](https://user-images.githubusercontent.com/28087895/54612302-5cc1d200-4a61-11e9-9222-443ce9718bd0.png)

**Comment by davidolahsv** [comment]
After the fix, on Ubuntu 16.04 both scrollbars appear even if the add-on is not pinned.

**Comment by davidolahsv** [comment]
Tested it yesterday, on Ubuntu the behavior was as expected. Retested today, I had the scrollbars. I thought there was something merged. My bad. Should we create another bug for that?

**Comment by groovecoder** [comment]
Interesting. So just to be clear - you did *NOT* get an updated version from AMO yesterday? (I signed a new release candidate version yesterday, but I want to make sure AMO didn't start sending it out to users! 😨)

**Comment by davidolahsv** [comment]
No worries. I used the candidate version 1.6.0-rc4 signed by you from yesterday.

**Comment by groovecoder** [comment]
Whew, thanks for the confirmation.

**Comment by GeorgiuCiprian** [comment]
Attaching a screenshot with the current behavior of version 1.6.1 of the add-on. Also, we've noticed that a grey bar is displayed just below the text.

![image](https://user-images.githubusercontent.com/43886441/54746438-d75f2e80-4bd4-11e9-89c7-ad9b18b8f3f8.png)

**Comment by GeorgiuCiprian** [comment]
We can confirm that the behavior encountered in https://github.com/mozilla/contain-facebook/issues/219#issuecomment-475178620 is not reproducible anymore on Firefox 65.0 and 66.0 with facebook_container-1.6.2-an+fx.xpi. Tested running Windows 10 x64, macOS 10.13 and Ubuntu 16.04 x64.

The initial problem however, is still present, but after speaking with Luke about it, the appearance of the scrollbar from the overflow menu was not addressed in this PR. 

I re-opened https://github.com/mozilla/contain-facebook/issues/234 for the remaining issue.
