### ISSUE TITLE
Facebook Container's panel displays misleading information on non-Facebook pages

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/contain-facebook#220]
**[Affected versions]:**

- Firefox 65.0.2 (BuildId:20190225143501).

**[Affected Platforms]:**

- Windows 10 64bit
- macOS 10.13
- Ubuntu 16.04 64bit

**[Steps to reproduce]:**

1. Launch Firefox.
2. Install Facebook Container 1.6.0
3. Access the https://www.wikipedia.org/ webpage.
4. Access the https://www.facebook.com webpage in a new tab.
5. Switch back to the Wikipedia tab **before Facebook page successfully loads**.
6. Click on the Facebook Container toolbar button.

**[Expected result]:**

The information from the Facebook Container's panel states that Wikipedia **is not** in the Facebook Container. 

**[Actual result]:**

The information from the Facebook Container's panel states that Wikipedia **is** in the Facebook Container. 

**[Additional Notes]:**

- Please note that the correct String is displayed if the user refreshes the Wikipedia page before opening the Facebook Container panel or if the user waits for the Facebook page to fully load.
- Attached screenshots for this:.

![bg](https://user-images.githubusercontent.com/28087895/54614581-53d2ff80-4a65-11e9-8383-ae7573bce180.gif)

**Comment by groovecoder** [comment]
Marking as dupe because @flodolo caught this in https://github.com/mozilla/contain-facebook/issues/216#issue-422565631 too. I'll be fixing this when I fix that.

**Comment by emilghittasv** [comment]
@groovecoder 
This is also reproducible with https://github.com/mozilla/contain-facebook/releases/tag/1.6.0-rc3

**Comment by groovecoder** [comment]
Ah, I believe this happens because `updateBrowserActionIcon` updates the browserAction icon for *all* tabs. So the background tab fires an event that gets carried over to the other tabs' icon UI. I can fix this pretty quick I think.
