### ISSUE TITLE
The wrong information is displayed inside the Facebook Container's panel for Facebook and non-Facebook pages 

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/contain-facebook#221]
**[Affected versions]:**

- Firefox 65.0.2 (BuildId:20190225143501).

**[Affected Platforms]:**

- Windows 10 64bit
- macOS 10.13
- Ubuntu 16.04 64bit

**[Steps to reproduce]:**

1. Launch Firefox.
2. Install Facebook Container 1.6.0
3. Access the https://www.wikipedia.org/ webpage.
4. Click the Facebook Container toolbar button.
5. Access the https://www.facebook.com/ webpage.
6. Click the Facebook Container toolbar button.

**[Expected result]:**

Facebook Container's panel displays the following information:
**non-Facebook tabs:** https://mozilla.invisionapp.com/share/NCQW7QI4FM9#/screens/350966783
**Facebook tabs:** https://mozilla.invisionapp.com/share/NCQW7QI4FM9#/screens/350966781

**[Actual result]:**

The following information is displayed:
**non-Facebook tabs:**
![non-Facebook pages](https://user-images.githubusercontent.com/28087895/54615642-1ec7ac80-4a67-11e9-8d47-e653c7ed3dcc.png)

**Facebook tabs:** 
![facebook pages](https://user-images.githubusercontent.com/28087895/54615666-28511480-4a67-11e9-88d5-c1c89cd36298.png)

**Comment by groovecoder** [comment]
Marking as dupe because @flodolo caught this in https://github.com/mozilla/contain-facebook/issues/216#issue-422565631 too. I'll be fixing this when I fix that.

**Comment by emilghittasv** [comment]
@groovecoder 
The Facebook Container's panel for **non-Facebook** webpages **looks good**.
The Facebook Container's panel for **Facebook webpages** still **looks different** (same as in the attached screenshot) from the mockup.

Tested with https://github.com/mozilla/contain-facebook/releases/tag/1.6.0-rc3

**Comment by groovecoder** [comment]
I've verified from mheubusch in Slack that, regardless of the mockup content, the final panel copy should be:

### non-Facebook copy
```
$URL$ is not in the Facebook Container
This site is outside of the Facebook Container. This makes it harder for Facebook to track you around the web.
```

### Facebook copy
```
$URL$ is in the Facebook Container
(image of Facebook + Suitcase)
This icon appears in the address bar when you visit websites like Facebook.com, Instagram.com, or Messenger.com that are in the Facebook Container.```
```

I'm sending a PR against this issue to update the panels to the above copy as the final copy for 1.6. I.e. ...

### non-Facebook screenshot
![image](https://user-images.githubusercontent.com/71928/54697122-01dcb900-4afb-11e9-978b-21d364b3ab0a.png)

### Facebook screenshot
![image](https://user-images.githubusercontent.com/71928/54697167-17ea7980-4afb-11e9-8a6f-0f1850da5f6d.png)
