### ISSUE TITLE
The Facebook Container's icon is not visible while the "Default" theme is applied

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/contain-facebook#227]
**Affected versions**
- Nightly 68.0a1
- Release 66.0
- Release 65.0 

**Affected platforms**
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64
- Win 7 x86

**Steps to reproduce**
1. Install the facebook_container-1.6.1-an+fx.xpi from [here](https://github.com/mozilla/contain-facebook/releases/tag/1.6.1)
3. Make sure that "Default" theme is applied in Firefox.
4. Inspect the Facebook Container's icon from the tab bar.

**Expected result**
- The Facebook Container's icon is correctly displayed.

**Actual result**
-  The Facebook Container's icon is not visible in tab bar, or becomes barely visible only by hovering with the mouse cursor over it.

**Additional notes**
- please see the attached image when the cursor is not hovered over the icon.

![image](https://user-images.githubusercontent.com/43886441/54745098-666a4780-4bd1-11e9-9895-8b54c8f9a0a1.png)

- and when the cursor is hovered over the icon.

![image](https://user-images.githubusercontent.com/43886441/54745105-6cf8bf00-4bd1-11e9-9eb7-e441436ceb59.png)

**Comment by groovecoder** [comment]
Ah, I'm running with Mac OS "Dark" appearance by default. I'll update our `default_icon` to the darker icon so it will work for "Light" system themes, which seem to be more popular per Firefox telemetry. (With lots of assumptions baked in.)

![image](https://user-images.githubusercontent.com/71928/54759137-7d05a400-4bbb-11e9-8a89-9554b01f97b7.png)

**Comment by GeorgiuCiprian** [comment]
We are no longer reproduce this issue on facebook_container-1.6.2, using Firefox 65.0, 66.0 under Windows 10 x64, macOS 10.13 and Ubuntu 18.04 x64.
