### ISSUE TITLE
Wrong message right after install

### ISSUE THREAD

**Issue by designakt** [mozilla/contain-facebook#228]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? *No*
- Are you using Firefox in a Private Window? *No*
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? *Yes*
- Facebook Container Version: 1.6.1
- Operating System + Version: Windows 10, latest release
- Firefox Version: latest Nightly
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Facebook Container	1.6.1	true	@contain-facebook
favicon-customizer	0.5	true	favicon-customizer@muffinresearch.co.uk
Global Consent Manager	1.3.2	true	we@globalconsentmanager.com
Shortkeys (Custom Keyboard Shortcuts)	2.2.7	true	Shortkeys@Shortkeys.com
Sync Tab Groups	0.8.1	true	sync-tab-groups@eric.masseran
Terms of Service; Didn’t Read	2.0.0	true	jid0-3GUEt1r69sQNSrca5p8kx9Ezc3U@jetpack
uBlock Origin	1.18.6	true	uBlock0@raymondhill.net

### Actual behavior
Clicking on FBC rigth after install from GitHub shows GitHub is part of the Firefox container - which it isn't.
![fbc_1 6 1 - right after install - wrong icon color - wrong infromation](https://user-images.githubusercontent.com/8145891/54754138-17c5a900-4be3-11e9-898e-affca5bf8d82.PNG)

### Expected behavior
correct message is displayed

### Steps to reproduce
1. install FBC from GitHub
2. click on FBC icon after install
3. see wrong message

**Comment by groovecoder** [comment]
@ShivangiKakkar - do you want to take this one? I think you'll just need to add a call to `updateBrowserActionIcon` at the bottom of `init` in `background.js` - like we do with `maybeReopenAlreadyOpenTabs`.

Or you might be able to put the `updateBrowserActionIcon` call *inside* the existing `tabsOnUpdated` in `maybeReopenAlreadyOpenTabs` and remove the `tabUpdateListener` completely? (I didn' see the `tabsOnUpdated` handler when I added `tabUpdateListener`)

**Comment by ShivangiKakkar** [comment]
@designakt Hey! I am not able to reproduce it. I tried your steps. Can you help me reproducing it?

**Comment by designakt** [comment]
Happy to help. What do you want me to do?
(I will try reproduce in a blank profile with today's Nightly as a first step.)

**Comment by designakt** [comment]
reproduce issue in latest Nightly on a fresh profile, with latest facebook container version (1.6.2), see gif for details:
![fbc_1 6 2 - right after install - wrong infromation](https://user-images.githubusercontent.com/8145891/54823536-76a12600-4ca8-11e9-8fd0-05fa63510436.gif)

**Comment by ShivangiKakkar** [comment]
@designakt Thanks I got it! :)

**Comment by stoically** [comment]
@ShivangiKakkar Are you already working on a fix? Otherwise I would like to pick it up.

**Comment by ShivangiKakkar** [comment]
@stoically Yeah, giving it a try. :)

**Comment by ShivangiKakkar** [comment]
> @ShivangiKakkar Are you already working on a fix? Otherwise I would like to pick it up.

Feel free to make a PR if you got the solution :D
