### ISSUE TITLE
Make repo public at launch

### ISSUE THREAD

**Issue by pdehaan** [mozilla/contain-facebook#25]
Per https://github.com/mozilla/contain-facebook/commit/7cf1a9a08cfa3f8ff8910eaf99a3f7e0b1b1a9e0#r28218790 comment:

https://github.com/mozilla/contain-facebook/blob/5e287b4990ff51017b142c65c3c6b54f029857fe/manifest.json#L20

I don't think this works, unless we make this repo public at launch.
Otherwise it's 404 city whenever a user clicks the link from about:addons.

**Comment by groovecoder** [comment]
Made the repo public.
