### ISSUE TITLE
Log in with facebook does not work

### ISSUE THREAD

**Issue by Japjappedulap** [mozilla/contain-facebook#252]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? **No**
- Are you using Firefox in a Private Window? **No**
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? **Yes**
- Facebook Container Version: **1.6.5**
- Operating System + Version: **Ubuntu 18.04 LTS**
- Firefox Version: **66.0.2**
- Other installed Add-ons + Version + Enabled/Disabled-Status: **None**

### Actual behavior
Entered website where I usually log in with facebook, which worked in the past. Try to log in with facebook, a new firefox window opens up when I click on the login button, with some link to facebook, but the window stays blank white and nothing happens.

### Expected behavior
The window to close, as when the extension is disabled, and log me using facebook.

### Steps to reproduce
1. In my case, the website I tried to log in was [this](https://www.hipmenu.ro/?l=en#home)
2. Click log in in the right part of the navbar
3. Modal opens, click 'Log in with facebook'
4. New window opens, stays blank forever.

### Notes
I've noticed that logging in works when disabling the extension(so rationally this is caused by the extension). Also, I've been using this extension a while now, and also that website, occasionally. I've never experienced this problem in the past, so it must be some new updates that screwed up somewhere.

**Comment by vargaendre** [comment]
Hi, I am noticing the same issue.

**Comment by timhodgson** [comment]
Same issue.  Only remedy I have found is to turn containers off.

**Comment by maxxcrawford** [comment]
You'll need to add this website to the Facebook Container. Follow the directions [from the docs](https://github.com/mozilla/contain-facebook/blob/master/docs/container-management.md). Thanks!
