### ISSUE TITLE
How can I create mulitple containers?

### ISSUE THREAD

**Issue by GildedHonour** [mozilla/contain-facebook#253]
How can I create mulitple containers?

**Comment by groovecoder** [comment]
You should use the Multi-Account Containers add-on: https://addons.mozilla.org/firefox/addon/multi-account-containers/

**Comment by GildedHonour** [comment]
I asking "how can I use Facebook container" for that and not "Firefox containers"? Otherwise, why to use "Facebook container" in the first place if "Firefox containers" exists?
