### ISSUE TITLE
Why does it open Instragram in this container?

### ISSUE THREAD

**Issue by GildedHonour** [mozilla/contain-facebook#254]
Why does it open Instragram in this container? How to prevent it from doing so? For Instagram I might have a separate Firefox container.

**Comment by groovecoder** [comment]
Instagram is owned by Facebook, so we put the site into the same container.

For separate containers, we suggest using Multi-Account Containers.

**Comment by GildedHonour** [comment]
But that doesn't mean that one always wants to have FB linked to their IG

**Comment by groovecoder** [comment]
This add-on tries to contain Facebook tracking for the most popular user scenarios. For separate FB and IG accounts, we have the Multi-Account Containers add-on.
