### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by MTX281** [mozilla/contain-facebook#255]
Using facebook container, used to work and now it doesn't. 

- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes
- Facebook Container Version: 1.6.5
- Operating System + Version: win7
- Firefox Version: 66.02
- Other installed Add-ons + Version + Enabled/Disabled-Status: ublock/ strict popup blocker/adblock plus/ unpay wall all enabled

### Actual behavior
..

### Expected behavior
..

### Steps to reproduce
1. ..
2. ..
3. ..

### Notes
..

**Comment by groovecoder** [comment]
Please add the steps to reproduce and the actual and expected behaviors to re-open this issue.
