### ISSUE TITLE
Confirm blocked URLs include all Facebook-owned URLs

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/contain-facebook#261]
Confirm that we're blocking all known Facebook domains: 

References: 
+ https://github.com/jmdugan/blocklists/blob/master/corporations/facebook/all
+ https://disconnect.me/trackerprotection/blocked

**Comment by groovecoder** [comment]
Note: our official block-list is from Disconnect. The jmdugan list looks more comprehensive, but we may be able to just block Facebook TLDs. I have code to help [canonicalize](https://github.com/mozilla/blok/blob/master/src/js/canonicalize.js) and [find all hosts](https://github.com/mozilla/blok/blob/master/src/js/lists.js#L1) for a domain.
