### ISSUE TITLE
Update styling of panels in v1.6

### ISSUE THREAD

**Issue by e-pang** [mozilla/contain-facebook#264]
<img width="448" alt="Screen Shot 2019-04-10 at 14 25 52" src="https://user-images.githubusercontent.com/30128313/55903904-a1daaf00-5b9c-11e9-8c8c-698fe12fcea1.png">

The styling of panels (ex. spacing and margins) needs to be updated to match specs
https://github.com/mozilla/contain-facebook/issues

**Comment by groovecoder** [comment]
Thanks @e-pang. I think I've filed these as separate issues, all labeled with "panel" and all in the "2.0" milestone. Do these look right:

https://github.com/mozilla/contain-facebook/issues?q=is%3Aopen+is%3Aissue+label%3Apanel+milestone%3A2.0

**Comment by e-pang** [comment]
great, thanks @groovecoder! 

Guessing we're only covering v2.0 for now? Just wanted to double check cause some of the panels update with each version.

**Comment by groovecoder** [comment]
Yup, we're staying focused on 2.0 for now. If we need more updates in 2.x releases we'll make them as we go.

**Comment by maxxcrawford** [comment]
@e-pang Do these issues still exist?

**Comment by e-pang** [comment]
nope, closing!
