### ISSUE TITLE
please add facebookcorewwwi.onion to the facebook sites.

### ISSUE THREAD

**Issue by xaiki** [mozilla/contain-facebook#267]
### Actual behavior
when connecting to the onion site the extensions excludes it

### Expected behavior
onion site should be considered facebook too

### Steps to reproduce
1. install tor
2. configure ff to use tor
3. go to https://facebookcorewwwi.onion

**Comment by stoically** [comment]
Duplicate of https://github.com/mozilla/contain-facebook/pull/147#issuecomment-426373134
