### ISSUE TITLE
Blank page or log in fails when you try to log into certain websites using the Facebook authentification

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/contain-facebook#27]
**[Affected versions]:**
- Firefox 59.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Facebook Container" add-on (1.2.0) installed.
- Be logged in a valid Facebook account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to https://pinterest.com/ (blank page) or https://www.instagram.com (login fail).
2. Click the "Continue with Facebook"/"Log in with Facebook" button and observe the behavior.

**[Expected result]:**
- You are redirected to the Pinterest page / Instagram log in form populated with FB credentials.

**[Actual result]:**
- Pinterest: The Facebook authentification tab becomes blank and you cannot access your Pinterest account.
- Instagram: You are wrongly redirected again to the sign up form each time you click the "Log in with Facebook" button.

**[Notes]:**
- Blank page issue is also reproducible on https://www.emag.ro/.
- This issue is also reproducible if you are not logged into your Facebook account.
- Attached screen recordings of the issue:
Pinterest
![log in pinterest 1](https://user-images.githubusercontent.com/17258026/37786130-8acf1380-2e04-11e8-82f2-74dedfc0e9c8.gif)

Instagram
![instagramfacebook authentification](https://user-images.githubusercontent.com/17258026/37786149-91cd42ec-2e04-11e8-8e6a-3b7c908d8e50.gif)

**Comment by jquentin** [comment]
Sooo, still broken ? I can't sign in to soundcloud on FF.

**Comment by groovecoder** [comment]
Oh, if you want you can actually try using the new 1.7.x release candidate to see if it fixes this login.

https://github.com/mozilla/contain-facebook/releases/tag/1.7.0

**Comment by maxxcrawford** [comment]
@jquentin Opening an issue to add login support for Soundcloud. Thanks!

**Comment by maxxcrawford** [comment]
Pinterest login with Facebook has been added with the release of [2.0](https://github.com/mozilla/contain-facebook/releases/tag/2.0.0). Closing for now. Please open an new issue if a site does not have badge/prompt support. 

![image](https://user-images.githubusercontent.com/2692333/58980323-a8009c80-8795-11e9-851b-8db048b60e70.png)

**Comment by maxxcrawford** [comment]
@SoftVision-PaulOiegas I opened an issue to add login support to emag.ro.

**Comment by gymvipsan** [comment]
> @SoftVision-PaulOiegas I opened an issue to add login support to emag.ro.

Ok, logging in via FB to emag.ro is now working. I have already tested from the [vipsangym](https://vipsangym.ro) account
