### ISSUE TITLE
Clicking the “Connect with Facebook” button doesn't work on several websites

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/contain-facebook#282]
[Notes]:
- Due to the short time frame of testing the add-on, we were only able to test it on Windows OS.
- We will also verify the logged issues on other platforms tomorrow in order to check if they are reproducible there as well. 

[Affected versions]:
- Firefox Nightly 68.0a1 (2019-04-22)

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set with the "false" value.
- Have the “facebook_container-2.0.0” add-on installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to https://www.fandom.com/register website.
3. Click the "Connect with Facebook" button.
4. Observe what happens next.

[Expected result]:
- The Facebook login panel is opened in a new window.

[Actual result]:
- Nothing happens, the Facebook login panel is not opened.

[Notes]:
- This is also reproducible with the Quora website:
-> https://www.quora.com/topic/Nintendo-Switch
-> https://www.quora.com/Why-do-people-praise-Dark-Souls-so-much-I-got-it-for-Switch-and-after-getting-past-the-first-boss-I-was-confused-where-to-go-and-what-to-do-The-game-didnt-even-explain-what-half-the-items-in-my-inventory-do
- Please see the attached screen recording with the issue.

![button doesn't work](https://user-images.githubusercontent.com/26000308/56504723-1fe67080-6522-11e9-9fc6-8caf08511df2.gif)

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is also reproducible on Mac 10.14 and Linux 16.04 x64. Also after further investigation, we noticed that this issue is also reproducible on the www.zillow.com website.
