### ISSUE TITLE
Clicking inside the blue interstitial pop-up doesn't redirect you to the Facebook login page

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/contain-facebook#283]
[Notes]:
- Due to the short time frame of testing the add-on, we were only able to test it on Windows OS.
- We will also verify the logged issues on other platforms tomorrow in order to check if they are reproducible there as well. 

[Affected versions]:
- Firefox Nightly 68.0a1 (2019-04-22)

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set with the "false" value.
- Have the “facebook_container-2.0.0” add-on installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to https://www.quora.com/ website.
3. Click the Facebook Container badge from the right side of the "Continue with Facebook" button.
4. Click inside the blue pop-up and observe what happens next.

[Expected result]:
- The Facebook login page is opened in a new window.

[Actual result]:
- Nothing happens, the Facebook login page is not opened.

[Notes]:
- This is also reproducible with the Twitch website:
-> https://www.twitch.tv/
- Please see the attached screen recording with the issue:

![blue popup](https://user-images.githubusercontent.com/26000308/56505225-bb2c1580-6523-11e9-9502-73a3233192ee.gif)

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is also reproducible on Mac 10.14 and Linux 16.04 x64.

**Comment by maxxcrawford** [comment]
This has been resolved. Now, after clicking "Allow" on the interstitial, the page waits for a new popup or reloads the page automatically (adding it to the container)
