### ISSUE TITLE
The Facebook Container badge is displayed only after the “Connect with Facebook” was previously clicked and it cannot be dismissed on the https://www.twitch.tv/ website

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/contain-facebook#285]
**[Notes]:**
- Due to the short time frame of testing the add-on, we were only able to test it on Windows OS.
We will also verify the logged issues on other platforms tomorrow in order to check if they are reproducible there as well.

**[Affected versions]:**
- Firefox Nightly 68.0a1 (2019-04-22)

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have the xpinstall.signatures.required preferences set to False.
- Have the “facebook_container-2.0.0” add-on installed.

**[Steps to reproduce]:**
1. Open the browser and navigate to the https://www.twitch.tv/ website.
2. Click the “Sign Up” button and observe the “Connect with Facebook” button.
3. Click the “Connect with Facebook” button.
4. Dismiss the “Log In” overlay and observe the behavior.

**[Expected result]:**
Step 2. The “Facebook container” badge is displayed on the top right side of the “Connect with Facebook” button.
Step 4. The “Facebook container” badge is dismissed.

**[Actual result]:**
Step 2. Only the “Sign in with Facebook” button is displayed.
Step 4. The “Facebook container” badge is still displayed.

**[Notes]:**
- Attached a screen recording with the issue: [Link](https://drive.google.com/open?id=1cmhsindDdDX8fJHLneE7b1P0j97b7mUQ)

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is also reproducible on Mac 10.14 and Linux 16.04 x64.

**Comment by maxxcrawford** [comment]
Testing with the latest version, this appears to be resolved. 

<img width="573" alt="image" src="https://user-images.githubusercontent.com/2692333/85499184-c2770500-b5a6-11ea-9f79-4fde584ef13d.png">
