### ISSUE TITLE
The blue interstitial pop-up is not dismissed when clicking outside of it or by pressing the “ESC” key

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/contain-facebook#287]
[Affected versions]:
- Firefox Nightly 68.0a1 (2019-04-22)

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set with the "false" value.
- Have the “facebook_container-2.0.0” add-on installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://www.quora.com/ website.
3. Click the Facebook Container badge.
4. Click outside the blue interstitial pop-up and observe the behavior.

[Expected result]:
- The blue interstitial pop-up is dismissed.

[Actual result]:
- The blue interstitial pop-up is not dismissed.

[Notes]:
- This issue is reproducible on all the tested websites.
- This issue is also reproducible when pressing the "ESC" key.
- The blue pop-up is dismissed only by pressing the Facebook Container badge again.
- Please see the attached screen recording with the issue:

![blue popup](https://user-images.githubusercontent.com/26000308/56582432-f7bd4700-65df-11e9-9ab8-ad3d7004b15d.gif)

**Comment by maxxcrawford** [comment]
This has been resolved with PR #280
