### ISSUE TITLE
The blue box is not displayed near the Facebook Container badge that was clicked in some cases

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/contain-facebook#288]
**[Affected versions]:**
- Firefox Nightly 68.0a1 (2019-04-22)

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the xpinstall.signatures.required preferences set to False.
- Have the “facebook_container-2.0.0” add-on installed.

**[Steps to reproduce]:**
1. Open the browser and navigate to the https://www.imdb.com/ website.
2. Click the “Facebook Container” badge near the Facebook share button.
3. Observe the behavior.

**[Expected result]:**
- A blue box is displayed on the right side of the clicked button.

**[Actual result]:**
- A blue box is displayed on the top left side of the page.

**[Notes]:**
- This issue is also reproducible on the https://www.facebook.com/ website.
- Attached a screen recording with the issue:

![rec of issue -  blue box](https://user-images.githubusercontent.com/37875464/56583237-ca719880-65e1-11e9-922d-4e77792125be.gif)

**Comment by maxxcrawford** [comment]
This has been resolved with the refactoring of how the prompt/badge are placed on the screen _(No longer using pseudo element)_.  

However, in checking IMDB, there's an issue with the Z-Index. Adding that URL to #312 

![image](https://user-images.githubusercontent.com/2692333/57789777-32a62c80-76ff-11e9-8929-f315cf3254e0.png)
