### ISSUE TITLE
The login window on Linkedin becomes blank after submitting the valid credentials

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/contain-facebook#289]
[Affected versions]:
- Firefox Nightly 68.0a1 (2019-04-22)

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set with the "false" value.
- Have the “facebook_container-2.0.0” add-on installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://www.linkedin.com/start/join website.
3. Click the "Continue with Facebook" button.
4. Enter your valid credentials and press the "Log in" button.
5. Observe the behavior.

[Expected result]:
- You are logged into your Linkedin account.

[Actual result]:
- The login window becomes blank.

[Notes]:
- Please see the attached screen recording with the issue:

![login](https://user-images.githubusercontent.com/26000308/56583344-060c6280-65e2-11e9-8bd4-96343f32873c.gif)

**Comment by maxxcrawford** [comment]
Opened two issues to resolve this: 
+ #297 
+ #298
