### ISSUE TITLE
The Pinterest login panel is displayed several times even after previously submitting the valid credentials

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/contain-facebook#290]
[Affected versions]:
- Firefox Nightly 68.0a1 (2019-04-22)

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set with the "false" value.
- Have the “facebook_container-2.0.0” add-on installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://www.pinterest.com website.
3. Click the Facebook Container badge.
4. Click inside the blue pop-up.
5. Enter your valid credentials and press the "Log in" button.
6. Observe the behavior.

[Expected result]:
Step 6 - You are logged into your Pinterest account.

[Actual result]:
Step 6 - The Pinterest login panel is displayed again.

[Notes]:
- By clicking again the Facebook Container badge will open another login panel in a new window, which automatically closes after ~3 seconds, and the previous login page refreshes.
- You are logged in to your Pinterest account only after the 4th try. 
- Please see the attached screen recording with the issue:

![pinterest login](https://user-images.githubusercontent.com/26000308/56587956-1c6aec00-65eb-11e9-8649-3a9e0710bc14.gif)

**Comment by maxxcrawford** [comment]
See #283 – Duplicate issue. The automatic page refresh solves this.
