### ISSUE TITLE
The Facebook Register/Login page displays 11 Facebook Container badges

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/contain-facebook#292]
[Affected versions]:
- Firefox Nightly 68.0a1 (2019-04-24)

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set with the "false" value.
- Have the “facebook_container-2.0.0” add-on installed.
- You are not logged in your Facebook account.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.facebook.com website.
3. Observe the way the Register/Login page is displayed.

[Expected result]:
- The Register/Login page is correctly displayed, without the Facebook Container badges.

[Actual result]:
- There are 11 Facebook Container badges displayed, most of them on the footer area of the page.

[Notes]:
- Please see the attached screenshot with the issue:

![Facebook page badges](https://user-images.githubusercontent.com/26000308/56646046-71f4d680-6687-11e9-99b1-29ff4e5fbae9.jpg)

**Comment by maxxcrawford** [comment]
The FBC detection no longer fires on Facebook-container websites.
