### ISSUE TITLE
Several websites are not opened in a Facebook Container tab after requesting to sign in with the Facebook Account

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/contain-facebook#293]
[Affected versions]:
- Firefox Nightly 68.0a1 (2019-04-24)

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set with the "false" value.
- Have the “facebook_container-2.0.0” add-on installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://www.imdb.com/ website.
3. Click the "Sign in" yellow button from the top right side of the page.
4. Click the "Sign in with Facebook" button.
5. Enter your valid Facebook credentials and click the "Log in" button.
6. Observe what happens next.

[Expected result]:
- You are logged into your account and the tab is opened in a Facebook Container.

[Actual result]:
- You are logged into your account but the tab is not opened in a Facebook Container.

[Notes]:
- This issue is also reproducible on www.aliexpress.com website.
- There are many other websites on which we can't test the login flow since they are blocked by other issues:
-> www.twitch.tv, www.quora.com: blocked by #283
-> www.fandom.com, www.zillow.com: blocked by #282 
-> www.espn.com: blocked by #286
-> www.linkedin.com: blocked by #289
- Please see the attached screen recording with the issue:

![container](https://user-images.githubusercontent.com/26000308/56657717-7332fd00-66a1-11e9-8684-2efe54e3d9b5.gif)

**Comment by Toldry** [comment]
I have this issue when logging in to Tinder too; facebook container causes it to be impossible to log in to Tinder because it relies entirely on facebook identity

**Comment by groovecoder** [comment]
@maxxcrawford - want to check our latest with imdb and Tinder?

**Comment by maxxcrawford** [comment]
@Toldry @groovecoder Would it make sense to add Tinder to the default list of sites in the container, knowing it's a requirement?

**Comment by maxxcrawford** [comment]
Adding Tinder login detection support: 

![image](https://user-images.githubusercontent.com/2692333/57869812-72d2e100-77cb-11e9-9305-87bc3236b2e9.png)

**Comment by maxxcrawford** [comment]
IMDb still has an issue with the z-index. It's part of #312.

**Comment by Toldry** [comment]
@maxxcrawford I tried opening Tinder again and it still doesn't work. I also can't see the container logo like in the screenshot you posted.

 Is there some manual update I need to do for it to work? (such as downloading and installing specific branch) or should the prod version be working?

**Comment by MrNessuno** [comment]
![immagine](https://user-images.githubusercontent.com/20603088/87966963-5a8cdf00-cabe-11ea-860b-590c115a0192.png)
New tinder version, can't login.

**Comment by maxxcrawford** [comment]
@MrNessuno It's working for me. Which language/locale are you viewing the site in? I can help debug. 

<img width="525" alt="image" src="https://user-images.githubusercontent.com/2692333/87968355-e6cee000-ca85-11ea-9b3f-b15684644812.png">

Additionally, you can add this website to the Facebook Container and side-step this issue. Follow the directions [from the docs](https://github.com/mozilla/contain-facebook/blob/master/docs/container-management.md).

**Comment by MrNessuno** [comment]
> 
> 
> @MrNessuno It's working for me. Which language/locale are you viewing the site in? I can help debug.
> 
> <img alt="image" width="525" src="https://user-images.githubusercontent.com/2692333/87968355-e6cee000-ca85-11ea-9b3f-b15684644812.png">
> 
> Additionally, you can add this website to the Facebook Container and side-step this issue. Follow the directions [from the docs](https://github.com/mozilla/contain-facebook/blob/master/docs/container-management.md).

Italian, and i also tried to open in the Facebook Container but had same issue, at this point... can be related to another addon? I think I should check that

**Comment by MrNessuno** [comment]
> 
> 
> @MrNessuno It's working for me. Which language/locale are you viewing the site in? I can help debug.
> 
> <img alt="image" width="525" src="https://user-images.githubusercontent.com/2692333/87968355-e6cee000-ca85-11ea-9b3f-b15684644812.png">
> 
> Additionally, you can add this website to the Facebook Container and side-step this issue. Follow the directions [from the docs](https://github.com/mozilla/contain-facebook/blob/master/docs/container-management.md).

Nothing, i tryed to disable all addons except Multi-Container and Facebook Container, and I still can't login with Facebook/can't click on the facebook button

**Comment by maxxcrawford** [comment]
@MrNessuno Did you add this site to the Facebook Container? (Is it loading Facebook resources?)

**Comment by MrNessuno** [comment]
> 
> 
> @MrNessuno Did you add this site to the Facebook Container? (Is it loading Facebook resources?)

Ye, I opened it in a Facebook Container. I also disabled Firefox anti-tracking protection because when I tried with no addons that was blocking the button. But as I said with only the Facebook addon the button is blocked.
