### ISSUE TITLE
Block facebook.com when its a subresource

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/contain-facebook#3]
If a webpage attempts to load facebook.com as a third party, intercept the request and block it.  So if cnn.com tries to load an image or iframe to facebook.com, it will get blocked before a request is ever made.

Share buttons, likes, comments coming from facebook, signing in with facebook - will never work.

If this is too restrictive, we can consider having an option so that users can opt out of this restriction.

**Comment by groovecoder** [comment]
Note: this issue has been revived as a potential feature for "[Facebook Container 2.0](https://docs.google.com/document/d/1Ehe4A8L1mv4N521hg6fbl9cEzogR_r6Zv1dz75QFcKs/edit)".

@shivangikakkar will plan to explore this.

**Comment by maxxcrawford** [comment]
2.0 blocks all FB-domain resources on any website outside of the container!
