### ISSUE TITLE
Firefox 66.0.3 Legacy Extension

### ISSUE THREAD

**Issue by ZeeAli415** [mozilla/contain-facebook#305]
Facebook Container has been placed in Legacy Extension and has been disabled from newest Firefox. 

Update:
Seems like it is a Firefox issue with all extensions, and in process of fixing it.
AdBlocker Extension twitter response on issue:
https://twitter.com/getadblock/status/1124497137461383169

**Comment by GitMoMan** [comment]
Just had the same trouble with FF 66.0.3 with all my extensions and themes. Plus, 66.0.3 won't even download anything. Just keeps saying download failed, check connection. Funny that my connection is perfectly fine.

**Comment by stoically** [comment]
This is due to an expired certificate in Firefox itself. Please follow https://bugzilla.mozilla.org/show_bug.cgi?id=1548973 to track progress.
