### ISSUE TITLE
Addon cannot be downloaded due to corruption

### ISSUE THREAD

**Issue by chuacw** [mozilla/contain-facebook#306]
Unable to download Facebook Container

### Actual behavior
Unable to download addon due to
![image](https://user-images.githubusercontent.com/1757930/57174676-11c71700-6e75-11e9-80d5-eb9dae7d3966.png)

### Expected behavior
Addon downloaded

### Steps to reproduce
1. Go https://support.mozilla.org/en-US/kb/facebook-container-isnt-working which gives the link to download Facebook Container https://addons.mozilla.org/firefox/downloads/latest/facebook-container/platform:2/addon-954390-latest.xpi. 

2. Try to download https://addons.mozilla.org/firefox/downloads/latest/facebook-container/platform:2/addon-954390-latest.xpi. 

Using: 68.0a1 (2019-05-03) (64-bit)

**Comment by mgdegroot** [comment]
Same issue here. Also fails to install when directly install from file (downloaded from the github releases). Apparently the issue is the signing cert from Mozilla which is expired (see the reddit thread https://www.reddit.com/r/firefox/comments/bkhtv8/heres_whats_going_on_with_your_addons_being/)

**Comment by martin03** [comment]
Starting in Firefox version 57, only extensions built using WebExtensions APIs will work. Not sure if your add-ons are affected? See Firefox add-on technology is modernizing and these Frequently Asked Questions for details.
[https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct](url)

**Comment by stoically** [comment]
This is due to an expired certificate in Firefox itself. Please follow https://bugzilla.mozilla.org/show_bug.cgi?id=1548973 to track progress.
