### ISSUE TITLE
About last Firefox update

### ISSUE THREAD

**Issue by Julmath** [mozilla/contain-facebook#308]
Heya, looks like Firefox's last update broke your add-on, which is quite ironic as you are Mozilla. Well, you might want to look into this. Thanks for your work!

**Comment by tulsamensshop** [comment]
Mozilla released a statement regarding this issue. It also includes immediate steps to resolve the issue. https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Comment by maxxcrawford** [comment]
Mozilla released a statement regarding this issue. It also includes immediate steps to resolve the issue: https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Comment by groovecoder** [comment]
Yeah, sorry for the inconvenience. The Add-ons team had quite a bit of work restoring everything.
