### ISSUE TITLE
fix tests with browser.runtime.getBrowserInfo() calls

### ISSUE THREAD

**Issue by groovecoder** [mozilla/contain-facebook#313]
All but 2 of the [test failures in the `add-sites-to-FBC`](https://travis-ci.org/mozilla/contain-facebook/builds/529466728) branch (which will become the 2.0 release) are caused by this code in `setupContainer`:

```js
    const info = await browser.runtime.getBrowserInfo();
    if (parseInt(info.version) < 67) {
      FACEBOOK_CONTAINER_DETAILS.color = "blue";
      FACEBOOK_CONTAINER_DETAILS.icon = "briefcase";
    }
```

I think this is because [`webextensions-jsdom`](https://github.com/webexts/webextensions-jsdom) doesn't fill in the `getBrowserInfo()` method?

@stoically - can you look at how we might fix this so we can get a green build in the `add-sites-to-FBC` branch?

**Comment by stoically** [comment]
Yep, the browser stub provided by `sinon-chrome` inside `webextensions-jsdom` doesn't fake any api behavior, and thus doesn't return info from `getBrowserInfo`. I've added returning of [faked data for `getBrowserInfo`](https://github.com/webexts/webextensions-api-fake/blob/7e52cfe875be6f056fb2c68f64bd17973bcd7a03/src/apis/runtime.js#L16-L22) (taken from the MDN example) to `webextensions-api-fake` and bumped the needed dependencies in https://github.com/mozilla/contain-facebook/commit/69897ba01ea9d5f7b6b0f6149ba572efce8c867c to pick up the change.
