### ISSUE TITLE
fix Redirect Canceling tests to work with blockFacebookSubResources

### ISSUE THREAD

**Issue by groovecoder** [mozilla/contain-facebook#314]
In the new `add-sites-to-FBC` branch that will become 2.0, after fixing https://github.com/mozilla/contain-facebook/issues/313, only these 2 test failures remain:

```
  1) Redirect Canceling
       when other onBeforeRequestHandlers are faster and redirect with the same requestId
         should not open two tabs:

      AssertionError: expected {} to deeply equal { cancel: true }
      + expected - actual

      -{}
      +{
      +  "cancel": true
      +}

      at Proxy.assertEqual (node_modules/chai/lib/chai/core/assertions.js:1020:19)
      at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
      at Context.it (test/features/redirect-canceling.test.js:26:31)

  2) Redirect Canceling
       when redirects change requestId midflight
         should not open two tabs:

      AssertionError: expected {} to deeply equal { cancel: true }
      + expected - actual

      -{}
      +{
      +  "cancel": true
      +}

      at Proxy.assertEqual (node_modules/chai/lib/chai/core/assertions.js:1020:19)
      at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
      at Context.it (test/features/redirect-canceling.test.js:65:31)
```

These seem to fail because we have a new `blockFacebookSubResources` `onBeforeRequest` listener, which returns `{}` for many requests.

@stoically - is there a way to update these tests so they only test the `containFacebook` listener?

**Comment by stoically** [comment]
Thanks for looking after a green build!

https://github.com/mozilla/contain-facebook/commit/8273de581bca6998b7e5ab8bf14c3447b84cb94e fixes those tests by adjusting the number when accessing the webRequest response (always +1 because of the additional `blockFacebookSubResources` listener).
