### ISSUE TITLE
Disable Like and Share buttons for 2.0

### ISSUE THREAD

**Issue by e-pang** [mozilla/contain-facebook#324]
Should Like and Share buttons be disabled for 2.0?

Tested on: https://www.buzzfeed.com

Update and show tooltip on click/hover of the button/badge
Updated content: "Facebook Container has disbled this button and blocked Facebook from tacking your visit to this page."

**Comment by arthur-mozilla** [comment]
They don't need to be disabled, but we should say they are disabled if they still work. We should say only "We have blocked Facebook from tracking your visit to this page."

**Comment by arthur-mozilla** [comment]
See also #328

**Comment by maxxcrawford** [comment]
This has been resolved. See quick screen recording of click on all the share links from this page: 
https://www.buzzfeed.com/shelbyheinrich/19-travel-hacks-need-to-know-before-your-next-trip?bfsource=sectionsvariant

![May-15-2019 10-39-48](https://user-images.githubusercontent.com/2692333/57789089-dbec2300-76fd-11e9-98ee-c875eb4316af.gif)
