### ISSUE TITLE
Facebook Container 1.7.0 breaks https://telemetry.mozilla.org/update-orphaning/

### ISSUE THREAD

**Issue by tdsmith** [mozilla/contain-facebook#327]
- Facebook Container Version: 1.7.0
- Operating System + Version: MacOS 10.14.4
- Firefox Version: Dev edition 67.0b17
- Other installed Add-ons + Version + Enabled/Disabled-Status:

```
Certainly Something (Certificate Viewer)	1.2.1	true	a2fff151f5ad0ef63cbd7e454e8907c1fa9cc32008f489178775570374f408a7@pokeinthe.io
Cisco Webex Extension	1.1.0	true	ciscowebexstart1@cisco.com
Facebook Container	1.7.0	true	@contain-facebook
FoxyProxy Standard	6.3	true	foxyproxy@eric.h.jung
Google Translator for Firefox	3.0.3.3	true	translator@zoli.bod
hotfix-update-xpi-intermediate	1.0.3	true	hotfix-update-xpi-intermediate@mozilla.com
LastPass: Free Password Manager	4.27.2.10	true	support@lastpass.com
uBlock Origin	1.18.16	true	uBlock0@raymondhill.net
Vidyo Replay Download	1.4	true	{522ada98-fe79-4881-93ab-b7ace8c7d7c4}
Zoom Scheduler	2.1.2	true	{bf855ead-d7c3-4c7b-9f88-9a7e75c0efdf}
```

### Actual behavior

Page does not render charts on load.

### Expected behavior

Page should render charts on load.

I disabled uBlock Origin for the page and nothing changed. Disabling Facebook Container in about:addons and reloading restores the page functionality.

### Steps to reproduce
1. Visit page
2. Expect charts

**Comment by arthur-mozilla** [comment]
This might be a hint of a bigger underlying problem where we are blocking content that is unrelated to Facebook. Could there be a regex matching issue?

**Comment by tdsmith** [comment]
The page calls a Javascript method using `<body onload="initDashboard()">`; if I switch to the console tab and call `initDashboard()` by hand, the page populates correctly.

**Comment by groovecoder** [comment]
For what it's worth, THANK YOU FOR FOX-FOODING AND FILING THIS! This revealed a bug with the way we were binding to `window.onload` which would have broken many websites, regardless of whether they had Facebook sub-resources or not. 🙇
