### ISSUE TITLE
Some Facebook buttons are said to be disabled even though they don't track and still work

### ISSUE THREAD

**Issue by arthur-mozilla** [mozilla/contain-facebook#328]
I visited this page: https://theintercept.com/2019/05/09/watch-interview-with-democratic-congresswoman-and-2020-presidential-candidate-tulsi-gabbard/

And saw this:
<img width="394" alt="image" src="https://user-images.githubusercontent.com/48572191/57505259-78e92f00-72ac-11e9-88a2-c1053124aa4d.png">

But if I click on the Facebook button, it opens a popup that lets me share the page to Facebook.

I would suggest either
* not badging the button at all
* badging the button, but with a message that says "Facebook Container has confirmed that this Facebook button is not tracking you."

**Comment by GeorgiuCiprian** [comment]
Hi @groovecoder, it seems that I can reproduce this issue with https://www.pbs.org/newshour/politics/former-cia-chief-brennan-to-brief-dems-on-iran as well. The share button works even though is supposed to be blocked. 

Let us know please if we should file a new bug for this?
