### ISSUE TITLE
Add CODEOWNER to force review of l10n changes

### ISSUE THREAD

**Issue by flodolo** [mozilla/contain-facebook#329]
The latest strings went out without any kind of l10n review. That's not how it should work, and at this point I just hope there are no issues.

Please add a CODEOWNER ([example](https://github.com/mozilla/blurts-addon/blob/master/CODEOWNERS)) so that I get pinged when someone touching the `en`folder. You'll need to add me as contributor.

**Comment by groovecoder** [comment]
Fixed in https://github.com/mozilla/contain-facebook/commit/cffb9cb571d3bfbc0bcfeec9fb6120a6042294b8
