### ISSUE TITLE
 On Pinterest the badge is duplicated, both the 28px by 28px and the 17px by 17px are displayed

### ISSUE THREAD

**Issue by obotisan** [mozilla/contain-facebook#332]
**Affected versions:**
- Firefox 66.0.5

**Affected Platforms:**
 - Windows 10 x64
- Ubuntu 18.04 x64
- macOS 10.13

**Prerequisites:**
- Have the [facebook_container-1.7.0](https://github.com/mozilla/contain-facebook/releases/tag/1.7.0) add-on installed.

**Steps to reproduce:**

1. Go to https://www.pinterest.com/.
2. Zoom in on the badge to see it better.

**Expected result:**
- The 28px by 28px is displayed. 

**Actual result:**
- Both the 28px by 28px and the 17px by 17px are displayed. 

**Notes:**
- Please see the attached image with the issue: 
![Screen Shot 2019-05-08 at 15 42 24](https://user-images.githubusercontent.com/42799381/57524775-898fb880-7331-11e9-9fc7-ae865a375f2d.png)

**Comment by maxxcrawford** [comment]
Related issue: #278

**Comment by maxxcrawford** [comment]
![image](https://user-images.githubusercontent.com/2692333/57875844-7e2d0900-77d9-11e9-831b-521e7b0c49a6.png)
