### ISSUE TITLE
The badge remains displayed after dismissing the FBC panel.

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/contain-facebook#333]
**Affected versions:**
- Firefox  66.0.5 

Affected Platforms:
- Windows 10 x64
- Ubuntu 18.04 x64
- macOS 10.13

**Prerequisites:**
- Have the latest f[acebook_container-1.7.0 add-on installed](https://github.com/mozilla/contain-facebook/releases/tag/1.7.0).

**Steps to reproduce:**
1. Go to this [website](https://www.quora.com/Why-do-people-praise-Dark-Souls-so-much-I-got-it-for-Switch-and-after-getting-past-the-first-boss-I-was-confused-where-to-go-and-what-to-do-The-game-didnt-even-explain-what-half-the-items-in-my-inventory-do).
2. Click on the "Sign In" button.
3. Click on the "Continue with Facebook" button from the pop-up.
4. Dismiss the panel by clicking on the "X" button.

**Expected result:**
- The FBC badge is not displayed on the webpage.

**Actual result:**
- The FBC badge remains displayed on the webpage.

Notes:
- I was also able to reproduce this issue on https://www.pinterest.com, therefore other websites could be affected.
- Please observe the screencast with this issue [here](https://drive.google.com/open?id=1T7jHqBLRKmqV2-GwGCgzj4UhQjLGaDxh).

**Comment by maxxcrawford** [comment]
This is an issue with the Z-Index on the prompt not being high-enough. There is an issue open to resolve this: #312. Closing this as a duplicate.

Additionally – the "X" press from Quora dismisses the login pop-up and has no interaction with the FBC prompt/panel. Thanks!
