### ISSUE TITLE
Back button unavailable after accessing the facebook page from menshealth.com

### ISSUE THREAD

**Issue by csasca** [mozilla/contain-facebook#335]
**Affected versions:**
- Firefox 66.0.5

**Affected Platforms:**
- Windows 7 x64
- Windows 10 x64
- Ubuntu 18.04 x64
- macOS 10.13

**Prerequisites:**
Have the [facebook_container-1.7.0](https://github.com/mozilla/contain-facebook/releases/tag/1.7.0) add-on installed.

**Steps to reproduce:**
1. Go to [Menshealth.com.](www.menshealth.com)
2. Click on the three lines button in order to open the left sided vertical menu.
3. Expand Follow from the list.
4. Click on Facebook.

**Expected result:**
- The link is opened on the same tab, and the back button will still be actionable.

**Actual result:**
- The link will be redirected on a new tab, rendering the back button useless.

**Notes:**
- Please see the attached screen recording with the issue: https://drive.google.com/open?id=1van2Ie6VJel27tW1FY0motWjF_MEnZ7-
- Another webpages affected by this issue: [wellsfargo](https://www.wellsfargo.com/), [Quizlet](https://quizlet.com/)

**Comment by maxxcrawford** [comment]
This is on ongoing/known issue. See #24 for more information. 

As of now, the only immediate work around is to re-open your previous tab (that was closed by the add-on). To do this, use the [shortcut](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_windows-tabs) `Command + Shift + T`. This will open up the previous state, giving you access to that specific tab's browsing history.
