### ISSUE TITLE
The login with facebook buttons are not actionable on Hi5

### ISSUE THREAD

**Issue by csasca** [mozilla/contain-facebook#336]
**Affected versions:**
- Firefox 66.0.5

**Affected Platforms:**
- Windows 7 x64
- Windows 10 x64
- Ubuntu 18.04 x64
- macOS 10.13

**Prerequisites:**
- Have the [facebook_container-1.7.0](https://github.com/mozilla/contain-facebook/releases/tag/1.7.0) add-on installed.

**Steps to reproduce:**

1. Go to [Hi5](https://secure.hi5.com/).
2. Click on either one of the two facebook login buttons.

**Expected result:**
- A popup requesting the user to login with the facebook account will be shown.

**Actual result:**
- Nothing happens.

**Notes:**
- Please see the attached screenshot with the two facebook buttons: 
![2019-05-08 17_22_51-hi5 - The social network for meeting new people](https://user-images.githubusercontent.com/50486883/57526465-27858200-7336-11e9-8a14-e2ab6438b884.png)

**Comment by csasca** [comment]
Hi @maxxcrawford. We have a similar issue with this one on (https://uk.match.com/). By clicking on login, the "Continue with Facebook" will be greyed out completely, and by disabling the plugin, the button will have the correct behavior. 

Will this be fixed too from this patch or should we log a new issue on this?

**Comment by maxxcrawford** [comment]
@csasca A separate ticket please! It's easier to address each not supported website on a case-by-case basis. Thanks!

**Comment by obotisan** [comment]
We verified the fix on Windows 10 x64, Ubuntu 18.04 x64 and macOS 10.13 by using FBC 1.7.1 and the bug is not reproducing anymore. 
However, we found other two issue. They are logged: #354 and #353.

**Comment by hughpuppies** [comment]
My problem is that somehow when I used the facebook login with Hi5 when I signed up, stupid me I know been doing that for 4 and a half years, suddenly facebook decides too blaock my url login so now I can access my account.  This is what I get when I try to use the facebook hi5 login.  This URL Is Blocked: The URL "https://secure.hi5.com/f32ec7f84dd904" has been blocked from Facebook.
