### ISSUE TITLE
FBC tool-tip appear as cut off on hovering 

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/contain-facebook#343]
**Affected versions:**
- Firefox 66.0.5

**Affected Platforms:**
 - Windows 10 x64
- Ubuntu 18.04 x64
- macOS 10.13

**Prerequisites:**
- Have the latest [facebook_container-1.7.0](https://github.com/mozilla/contain-facebook/releases/tag/1.7.0) add-on installed.

**Steps to reproduce:**
1. Go to this [website](https://www.amazon.com/Longwu-Womens-Casual-Bandage-Blue-XL/dp/B07QTYVNRD/ref=lp_18665827011_1_1?srs=18665827011&ie=UTF8&qid=1557498392&sr=8-1).
2. Hover over the purple badge from the Facebook share button.

**Expected result:**
- FBC tool-tip is properly displayed.

**Actual result:**
- FBC tool-tip appear as cut off. 

**Notes:**
- Please see the attached screenshot:

![Screenshot from 2019-05-10 17-35-02](https://user-images.githubusercontent.com/43886441/57535006-fa42cf00-7349-11e9-85a4-2d6478c1399f.png)

**Comment by obotisan** [comment]
We verified the fix on Windows 10 x64, Ubuntu 18.04 x64 and macOS 10.13 by using FBC 1.7.1 and the bug is not reproducing anymore.
