### ISSUE TITLE
Show suitcase icon on facebook.com panel if fence is not available for containers

### ISSUE THREAD

**Issue by arthur-mozilla** [mozilla/contain-facebook#346]
On this panel, it shows what the user should expect on the address bar:

![image](https://user-images.githubusercontent.com/48572191/57552995-6f021300-7322-11e9-91ed-0966a4b902dd.png)

But before the 67 release, we won't have the fence icon in the container UI. So we should show the suitcase icon in that panel for pre-67.

Please note I'm not suggesting we change the browserAction icon. Seems like that can remain a fence for all versions.

**Comment by maxxcrawford** [comment]
Closed!
