### ISSUE TITLE
Esquire’s facebook page button has badge

### ISSUE THREAD

**Issue by csasca** [mozilla/contain-facebook#349]
**Affected versions:**
- Firefox 66.0.5

**Affected Platforms:**
- Windows 7 x64
- Windows 10 x64
- Ubuntu 18.04 x64
- macOS 10.13

**Prerequisites:**
- Have the [facebook_container-1.7.0](https://github.com/mozilla/contain-facebook/releases/tag/1.7.0) add-on installed.

**Steps to reproduce:**

1. Go to https://www.esquire.com/style/mens-fashion/g26379698/oscars-best-dressed-men-academy-awards/.
2. Scroll down on the page.
3. See the facebook sign from the bottom right in the page.

**Expected result:**
- The Esquire's facebook page does not have the facebook container badge. 

**Actual result:**
- The badge is present on the facebook button. 

**Notes:**
- If hovering the facebook button, "Share on facebook" message will appear.
- Left clicking the button will not do anything, but by accessing the button with middle click, will open a new tab wit the facebook page for the site.
- Please see the attached screenshot with the button
![2019-05-13 17_01_27-The 25 Most Stylish Men to Ever Step Foot on the Oscars Red Carpet](https://user-images.githubusercontent.com/50486883/57628094-ee514a00-75a1-11e9-8f9a-32c3a58cb686.png)
- The same issue is happening on (https://www.cosmopolitan.com/lifestyle/a27432293/weekly-horoscope-may-13-2019/)

**Comment by maxxcrawford** [comment]
Part of the identifiers for share buttons include any element that has its `title` equal to `Share on Facebook`. Both Cosmo and Esquire both have their Facebook page links with this title. This is some standard site overlap, and we'd rather badge more than less.
