### ISSUE TITLE
Log In with facebook is greyed out on https://uk.match.com/

### ISSUE THREAD

**Issue by csasca** [mozilla/contain-facebook#350]
**Affected versions:**
- Firefox 66.0.5

**Affected Platforms:**
- Windows 7 x64
- Windows 10 x64
- Ubuntu 18.04 x64
- macOS 10.13

**Prerequisites:**
- Have the [facebook_container-1.7.0](https://github.com/mozilla/contain-facebook/releases/tag/1.7.0) add-on installed.

**Steps to reproduce:**

1. Go to https://uk.match.com/.
2. Click on the Log in button on the top-right part of the page.
3. Observe the behaviour.

**Expected result:**
- The "Continue with Facebook" can be used as a method of login. 

**Actual result:**
- "Continue with Facebook" is greyed out. 

**Notes:**
- Please see the attached screenshot with the issue: 
![2019-05-13 18_08_15-Online Dating Site - Register For Free on Match UK!](https://user-images.githubusercontent.com/50486883/57632745-e8139b80-75aa-11e9-8c53-fd3cbd5fad5b.png)

**Comment by maxxcrawford** [comment]
@csasca It's greyed out as the plugin is blocking the subresources. We're adding detection support. You'll be able to add this site to the container in the next release, allowing FB resources to loaded on the page, restoring functionality. 

![image](https://user-images.githubusercontent.com/2692333/58187391-48c26880-7c7c-11e9-9aec-e1b58aa1b783.png)
