### ISSUE TITLE
forms broken in Jenkins

### ISSUE THREAD

**Issue by arthur-mozilla** [mozilla/contain-facebook#359]
From leo in Mozilla: "Just had a bizarre error from the facebook container 2.0 beta linked in tl;dr - it was breaking (some) scripts in jenkins, meaning I couldn't submit any forms"

**Comment by maxxcrawford** [comment]
@arthur-mozilla Can you direct me to a site to verify? I have a fix in the works.

**Comment by LeoMcA** [comment]
I found some time to try again with the [latest version of the addon](https://github.com/mozilla/contain-facebook/releases/tag/1.7.3), and the issue doesn't appear any more.

This issue can be closed :)

**Comment by maxxcrawford** [comment]
@LeoMcA Thank you!
