### ISSUE TITLE
Fence icon is over page content instead of over facebook share icon

### ISSUE THREAD

**Issue by dholbert** [mozilla/contain-facebook#363]
- Facebook Container Version: 1.7.0
- Operating System + Version: Ubuntu 19.04 (Linux)
- Firefox Version: Nightly 68.0a1 (2019-05-14)
- Other installed Add-ons + Version + Enabled/Disabled-Status: None

### Actual behavior
Fence icon is at seemingly-arbitrary position, covering up page content.

### Expected behavior
Fence icon should be over Facebook Share button.

### Steps to reproduce
1. Visit https://mpowerd.com/products/base-light

### Notes
Here's a screenshot:
![Screenshot from 2019-05-15 10-16-52](https://user-images.githubusercontent.com/426803/57795451-dccf8580-76fa-11e9-9377-58e515eef46f.png)

**Comment by maxxcrawford** [comment]
This has been resolved in 1.7.1 Release: 

![image](https://user-images.githubusercontent.com/2692333/57798614-c3d2ce80-7712-11e9-8b00-29d530fd5c8d.png)

**Comment by dholbert** [comment]
I've now installed version 1.7.1, and I've confirmed that this is fixed there. Thanks!
