### ISSUE TITLE
https://sso.mozilla.com/workday doesn't finish loading if I have FB Container enabled

### ISSUE THREAD

**Issue by dholbert** [mozilla/contain-facebook#365]
- Facebook Container Version: 1.7.1
- Operating System + Version: Ubuntu 19.04 (linux)
- Firefox Version: Nightly 68.0a1 (2019-05-15) (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status: None (using a fresh profile)

### Actual behavior
https://sso.mozilla.com/workday ends up redirecting to blank page (with URL bar showing https://www.myworkday.com/vhr_mozilla/login-saml.flex )

### Expected behavior
https://sso.mozilla.com/workday should redirect to functional workday page (and URL bar should end up at https://www.myworkday.com/vhr_mozilla/d/home.htmld )

### Steps to reproduce
1. Install FB Container from https://github.com/mozilla/contain-facebook/releases/tag/1.7.1
2. Visit https://sso.mozilla.com/workday 
3. Log in with MoCo credentials (if you're not already authenticated with SSO)

CC @chutten

**Comment by dholbert** [comment]
(The issue goes away if I disable the FB container addon.)

**Comment by groovecoder** [comment]
Thanks for the heads-up!

**Comment by groovecoder** [comment]
I spot-checked that this is fixed in https://github.com/mozilla/contain-facebook/pull/367.
