### ISSUE TITLE
Add ESLint and run on CI

### ISSUE THREAD

**Issue by pdehaan** [mozilla/contain-facebook#37]
Not high priority, but would be very nice to have if this is a long-living project.
It recently caught a couple of potential issues with a PR, so would be nice to run linting automatically on every commit and just not some weird franken-script that lives solely on my machine.

Other benefits include:
- we could run linting and build the add-on automatically on Circle-CI and save the XPI/ZIP as a build artifact. Not sure if this would be a huge improvement over loading the manifest.json via about:debugging.

**Comment by jonathanKingston** [comment]
This should be resolved by: https://github.com/mozilla/contain-facebook/pull/62

**Comment by groovecoder** [comment]
Fixed.
