### ISSUE TITLE
Page Load/Firing Issue

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/contain-facebook#372]
Fighting `window.load` vs `domContentLoaded` events to run `CheckIfURLShouldBeBlocked` and `contentScriptSetTimeout` functions.

**Comment by maxxcrawford** [comment]
@groovecoder Opening this issue to solve the race condition issues the `content_script` is having.

**Comment by groovecoder** [comment]
This should be fixed as of https://github.com/mozilla/contain-facebook/pull/378 right?

**Comment by maxxcrawford** [comment]
Weird. Yeah – It should've auto-closed?

**Comment by maxxcrawford** [comment]
@groovecoder Bad commit message. Needs more `#`: 
![image](https://user-images.githubusercontent.com/2692333/58054644-cbceac00-7b20-11e9-8126-b6e7e108d9c8.png)

**Comment by groovecoder** [comment]
Gotta include "Fixed **#**372"
