### ISSUE TITLE
Update Screenshot on AMO to match 1.9 release 

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/contain-facebook#383]
## Issues

- [ ] Update screenshot icon to fence (from briefcase) 
- [ ] Update the colour.
- [ ] Add some additional screen shots as well.

URLs:
+ AMO Page: https://addons.mozilla.org/en-US/firefox/addon/facebook-container/

## Screenshot

Previous thumbnail (PNG, 640x480) 

![image](https://user-images.githubusercontent.com/2692333/58110582-71335f80-7bb5-11e9-8bf9-72fd6e06d51f.png)

**Comment by e-pang** [comment]
- Remove the current screen with the Pink drop-down
- Keep the fast company screen
- Add in additional attached screens

I exported them at 2x (1280x960) so they will display sharp on retina screens. 
Let me know if this is okay.

![Screen 1@2x](https://user-images.githubusercontent.com/30128313/58355152-71e02600-7e41-11e9-84d4-822da8cc5153.png)
![Screen 2@2x](https://user-images.githubusercontent.com/30128313/58355153-71e02600-7e41-11e9-8942-e7bebd52e5db.png)
![Screen 3@2x](https://user-images.githubusercontent.com/30128313/58355154-71e02600-7e41-11e9-9545-037d37df915a.png)
![Screen 4@2x](https://user-images.githubusercontent.com/30128313/58355217-a18f2e00-7e41-11e9-8af0-dd3cac982b2e.png)

**Comment by e-pang** [comment]
Note, these screens shouldn't not be updated until https://github.com/mozilla/contain-facebook/issues/411 is closed. The badged icon is shown in the screens.

**Comment by e-pang** [comment]
Created new versions of the screens so they are no longer blocked by #411 which from my understanding is impossible. I've updated the screens so they show the purple rectangle with the "!" when a Facebook tracker is detected.

![1](https://user-images.githubusercontent.com/30128313/76534964-9056f280-6450-11ea-99ec-a32c4dddc1a7.png)
![2](https://user-images.githubusercontent.com/30128313/76534969-91881f80-6450-11ea-813c-378ed7063318.png)
![3](https://user-images.githubusercontent.com/30128313/76534980-92b94c80-6450-11ea-81b7-525f9c712eb9.png)
![4](https://user-images.githubusercontent.com/30128313/76534985-9351e300-6450-11ea-91a5-f1805e07e3b6.png)

**Comment by maxxcrawford** [comment]
This has been resolved! 
<img width="926" alt="image" src="https://user-images.githubusercontent.com/2692333/85498154-c6a22300-b5a4-11ea-8e39-b4d9029081ab.png">

@e-pang Can you verify? https://addons.mozilla.org/en-US/firefox/addon/facebook-container/

**Comment by e-pang** [comment]
Thanks Maxx!
