### ISSUE TITLE
Latest version breaks Rocket Loader

### ISSUE THREAD

**Issue by geocom** [mozilla/contain-facebook#384]
The latest version of Facebook Container seems to break rocket-loader which in turns breaks Javascript loading on the web site. You can see this happening on geekzone.co.nz going back to 1.6.5 resolves the issue 

### Actual behavior
Rocket Loader fails with a permission error (Error: Permission denied to access property "__rocketLoaderInlineHandlerProxy")

### Expected behavior
Rocket Loader should be able to run

### Steps to reproduce
1. Goto geekzone.co.nz with 1.0.9
2. Open Web Inspector the error message above will be in the console and all JS on the page will be commented out and will not run

Optional
1. Downgrade to 1.6.5 and goto geekzone.co.nz
2. Open web Inspector and there will be no error message and the JS will be uncommented

### Notes
Container Version: 1.0.9
Have tried on two computers one Linux one macOS both have the same issue

**Comment by maxxcrawford** [comment]
Thanks for logging this! 

Looks this is an issue with overwriting the `window.onload` function. PR coming in hot. We'll have this resolved in the next release, slated to be pushed out in the next week.

**Comment by freitasm** [comment]
Thanks for the quick action!

**Comment by maxxcrawford** [comment]
@geocom @freitasm Did the new version resolve this issue for you?

**Comment by geocom** [comment]
Hi Max yep it did fix the issue. Thanks for pushing this through quickly.

**Comment by freitasm** [comment]
Hi @geocom 

I had disabled RocketLoader because of this issue and enabled it again earlier today - have you tested since?

**Comment by geocom** [comment]
Yea just reloaded now and it's working fine.

**Comment by freitasm** [comment]
@geocom Thanks!

**Comment by maxxcrawford** [comment]
Excellent. Glad to hear it! 😄
