### ISSUE TITLE
Small fence icons everywhere in the page

### ISSUE THREAD

**Issue by esteves023** [mozilla/contain-facebook#387]
- Facebook Container Version: 1.9.0
- Operating System + Version: Windows 10 home 2018
- Firefox Version: 67.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: 

Bypass Paywalls	1.5.5	true	
Facebook Container	1.9.0	true	
uBlock Origin	1.19.2	true	
Video Speed Controller	0.5.1	true	
uMatrix	1.3.16	false	
Video DownloadHelper	7.3.5	false	

### Actual behavior

Fence icons are at seemingly-arbitrary positions, covering up a lot of page content.

### Expected behavior

Fence icons should be over Facebook buttons OR nowhere at all (preferably) 

### Steps to reproduce

1. Visit: https://www.estadao.com.br/

### Notes

Screenshot: 

![estada](https://user-images.githubusercontent.com/37459493/58194309-8be00400-7c9b-11e9-8f91-e03733be9fdd.JPG)

**Comment by SBeausoleil** [comment]
I have the same issue on imgur.com. The icons are not even on Facebook links so it is becoming a nuisance.

**Comment by g3rain1** [comment]
I have it too. Mostly on Imgur.  Even if it worked correctly I'd prefer an option not have any fence icons anywhere.

**Comment by maxxcrawford** [comment]
@g3rain1 Can you provide a link/screenshot for Imgur?

**Comment by g3rain1** [comment]
@maxxcrawford https://i.imgur.com/PsXt8lF.jpg

**Comment by maxxcrawford** [comment]
@esteves023 – We're looking more into the estadao.com.br domain. The script is identifying Facebook share buttons that are off-canvas/hidden, which is why they're floating off by themselves.

**Comment by maxxcrawford** [comment]
@g3rain1 Interesting. We used imgur.com as a test domain and have not seen that behavior before (See screenshots below from a quick test I ran in the past 10 mins).

Can you please provide steps to replicate this behavior? The expected behavior is ONE badge on the Facebook share button at the end of each post. 

---

**_Imgur.com Screenshots - v1.9.0_** 

![image](https://user-images.githubusercontent.com/2692333/58206170-d1093380-7ca5-11e9-8d84-b6fc42cfbc80.png)

![image](https://user-images.githubusercontent.com/2692333/58206179-d36b8d80-7ca5-11e9-911c-cadefc869849.png)

**Comment by maxxcrawford** [comment]
@g3rain1 These issues aren't actually related. I opened a new one #389 – Let's move further discussion about Imgur there.

**Comment by g3rain1** [comment]
@maxxcrawford  I just browse the site. Nothing special. The icons seem to accumulate over time. Refreshing the tab makes them go away.

**Comment by esteves023** [comment]
Is there anyway to provide an option to hide those fence icons altogether? Because I have the same issue on other websites as well and it's going to be impossible to fix it for all of them

**Comment by maxxcrawford** [comment]
@esteves023 Yes – We're working on a feature to dismiss/hide badges while still blocking Facebook resources.

**Comment by Darxide23** [comment]
Happening to me everywhere, not just Imgur. Can't wait for that "hide badges" option. There really is no reason the icon even needs to exist.

**Comment by calvinmorett** [comment]
Is there a fix incoming to toggle or disable the icon from showing up?

**Comment by Darxide23** [comment]
> Is there a fix incoming to toggle or disable the icon from showing up?

A year and a half later? It's looking less and less likely.

**Comment by plyoung** [comment]
Where is the option to hide the icon?  How hard can it be to allow us to hide it?
