### ISSUE TITLE
mime type found when FBC it's on. @ storiesig.com

### ISSUE THREAD

**Issue by Barticf** [mozilla/contain-facebook#388]
- Facebook Container Version: 1.9.0
- Operating System + Version: Win 7
- Firefox Version: 67.0
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Steps to reproduce
1. Turn on this plugin, log in FB
2. Go to site to https://storiesig.com/stories/dbstf
3. Videos not working (No video with supported format and mime type found). + Images don't show

### Notes
If I just turn on this plugin without login to FB there is no problem with playing videos in this site

**Comment by maxxcrawford** [comment]
The latest version of the add-on blocks all Facebook, Instagram and Messenger resources. This included hosted/embedded media. The video on this page comes directly from Instagram's CDN (`https://scontent-sjc3-1.cdninstagram.com…`) and is blocked. 

We're developing a feature to add sites to the Facebook container. Follow along here: #370
