### ISSUE TITLE
Elsevier ScienceDirect broken if container is enabled

### ISSUE THREAD

**Issue by drnixon** [mozilla/contain-facebook#390]
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0
Facebook Container	1.9.0
macOS 10.14.5

### Actual behavior
Elsevier journal article pages fail to load completely, showing only article title and abstract; download links on page are nonfunctional.

### Expected behavior
Page should load fully. Container reports no Facebook trackers are detected on page, yet content is not loaded fully. Comparing source in Safari vs. Firefox shows that some page content is dynamically generated using unique identifiers; Javascript looks like it is obfusticating links to CDNs using various methods of encoding or concatenating code.

### Steps to reproduce
1. Visit article page such as https://www.sciencedirect.com/science/article/pii/S107474271830265X
2. Watch as page does not load fully
3. Disable Container, reload, watch page content appear

**Comment by maxxcrawford** [comment]
Is this still reproducible on the latest version of the add-on (2.1.1) and Firefox (77.0.1)? I loaded the test site and it seemed to load the same when the add-on was enabled and not. Thanks!

**Comment by drnixon** [comment]
Firefox 78 beta + Facebook Container 2.1.1 shows no conflict at this point. Whatever was broken before has been fixed, it seems.

**Comment by maxxcrawford** [comment]
Thanks!
