### ISSUE TITLE
Images sourced from instagram blocked

### ISSUE THREAD

**Issue by BradCOnGitHub** [mozilla/contain-facebook#391]
- Facebook Container Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
Instagram images in normal pages don't load

### Expected behavior
Images should load

### Steps to reproduce
I have an instagram feed in my feedly (rss reader). The images no longer show up inside of feedly.

https://feedly.com/i/subscription/feed%2Fhttps%3A%2F%2Frsshub.app%2Finstagram%2Fuser%2Fnathanwpylestrangeplanet

https://www.instagram.com/nathanwpylestrangeplanet/

**Comment by maxxcrawford** [comment]
The latest release of this add-on blocks all resources from any Facebook, Instagram or Messenger domain, including CDN/Media. This is expected behavior. 

We're working on a feature #370 to add sites to the Facebook container, allowing resources (including media) to be loaded within the next week.

**Comment by BradCOnGitHub** [comment]
FWIW (and I know I'll be ignored), I don't -want- this to happen. Having Facebook in the container is enough because it keeps my login contained. Simple resources like images loaded outside the container wouldn't be tied to my account so I still want to see them if they are part of another domain.
