### ISSUE TITLE
Facebook Container is Blocking the images of my blog

### ISSUE THREAD

**Issue by mingogomes** [mozilla/contain-facebook#392]
Hey,

Even deactivating all the ads on my website, the plugin keeps blocking the images of the website. I don't know if this is normal.

Thanks

**Comment by maxxcrawford** [comment]
@mingogomes Can you provide a link to your website? 

Note that the latest release of the add-on block all resources (including images, video and scripts) from Facebook and Instagram on websites not in the Facebook container.

**Comment by mingogomes** [comment]
Hey Max,
Sure, sorry, I though I had share it.
Is newesc.com

**Comment by maxxcrawford** [comment]
We have a feature (#370) coming in the next release to manually add non-FB websites to the container to resolve issues like this. We’ll keep you posted. Leaving this issue open for now!

**Comment by mingogomes** [comment]
Thanks for your response.
I don't know why my website is being targeted into Facebook Container. I have another one, but in Portuguese, with the same plugins, theme and everything, but don't have this problem:
newesc.pt

Is great that the #370 is gonna create this option to the user, but my problem is that I don't know why the extension is blocking the images :(

**Comment by maxxcrawford** [comment]
Just checked the error log – https://newesc.com/ uses the same __rocketLoaderInlineHandlerProxy as #384. It will be resolved next week in our next release. Thanks!

Screenshot of the site working correctly with the PR: 

![image](https://user-images.githubusercontent.com/2692333/58293440-18b5bb00-7d8b-11e9-906d-36ae61209c10.png)

**Comment by maxxcrawford** [comment]
@mingogomes Did the new version resolve this for you?

**Comment by mingogomes** [comment]
@maxxcrawford is working perfectly now :D
Thanks a lot
