### ISSUE TITLE
Recent change breaks Words With Friends

### ISSUE THREAD

**Issue by NginUS** [mozilla/contain-facebook#393]
- Facebook Container Version:  1.9.0
- Operating System + Version: Linux Mint 18.3 (Ubuntu 16.04 LTS)
- Firefox Version: 67.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: 
Auto Reload Tab
Disable HTML5 Autoplay
Disable Tab Detach 2
Evernote Web Clipper
Facebook Container
Firefox DevTools ADB Extension
Firefox Pioneer
htofix-update-xpi-intermediate
HTTPS Everywhere
iGive Button
In-Page Pop-Up Reporter
Joplin Web Clipper - Disabled
MTurk Suite
No Coin - Disabled
NoScript Security Suite
Old Reddit Redirect
Pretty New Tab Image
Privacy Badger
Reddit Enhancement Suite
Save Page WE
Tabloc
Tampermonkey (TurkerviewJS)
uBlock Origin
Undo Closed Tabs Button
Dark Reader - Disabled
One-click Screenshot - Disabled
RedditNotifier-WE
Redirector - Disabled
Video Background Play Fix

### Actual behavior
Screen stays on 'loading moves'

### Expected behavior
Game loads & works

### Steps to reproduce
1. Log into Facebook
2. Open Words With Friends via link orbookmark
3.

### Notes
Tried disabling the following to isolate Facebook Container:
-NoScript 
-uBlock
-Privacy Badger
...None helped. Works instantly upon disabling Facebook Container.

**Comment by maxxcrawford** [comment]
Can you provide the specific website URL this isn't working in?

**Comment by NginUS** [comment]
> Can you provide the specific website URL this isn't working in?

https://apps.facebook.com/wordswithfriends/?ref=br_rs

**Comment by NginUS** [comment]
Still an issue with Facebook Container version 2.

**Comment by NginUS** [comment]
Issue persists:
Linux Mint 18.3
Facebook Container 2.0
Firefox 67.0.4

**Comment by NginUS** [comment]
I see that this is no longer the only game being affected, with a new issue being posted with regards to the 'Angry Birds' game as well (https://github.com/mozilla/contain-facebook/issues/480). With this in mind, I'll update the details surrounding 'Words With Friends' still not working since this issue was posted initially.

Linux Mint 18.3 (Ubuntu 16.04 LTS)
Facebook Container 2.0.1
Firefox 68.0.1

Installed & Enabled Add-Ons:
Amazon Smile
Auto Reload Tab
Catbox Uploader
Disable HTML5 Autoplay
Disable Tab Detach 2
Discogs Search
Facebook Container
Firefox DevTools ADB Extension
Firefox Pioneer
HTTPS Everywhere
iGive Button
In-Page Pop-Up Reporter
MTurk Suite
NoScript
Old Reddit Redirect
Pretty New Tab Image
Privacy Badger
Reddit Enhancement Suite
Tabloc
Tampermonkey (TurkerviewJS)
uBlock Origin
Undo Closed Tabs Button (revived)


The URL where the failure occurs: https://apps.facebook.com/wordswithfriends/?ref=br_rs

The failure manifests as the game logo spinning with the text 'Loading moves...', which remains indefinitely.

Needless to say, I'd very much like to limit Facebook via the 'Facebook Container' Add-On's functionality, & hope that issues such as this can be resolved such that I will no longer have to choose between one or the other.

**Comment by maxxcrawford** [comment]
@NginUS Hey there – I found the root issue, I think. I will add the domain `https://apps.facebook.com` to the default sites list inside the FBC. This should allow the Facebook SDK to load.

**Comment by NginUS** [comment]
> @NginUS Hey there – I found the root issue, I think. I will add the domain `https://apps.facebook.com` to the default sites list inside the FBC. This should allow the Facebook SDK to load.

Ok, thanks. Let me know when I can update & I'll check again.

**Comment by NginUS** [comment]
Still no change using Firefox 68.0.2 & Facebook Container 2.0.2

**Comment by mbroo** [comment]
Appears to still be an issue with Firefox 69.0.2 & Facebook Container 2.0.3

**Comment by mbroo** [comment]
Appears to still be an issue with Firefox 70 & Facebook Container 2.0.3

**Comment by maxxcrawford** [comment]
@mbroo Try adding [zynga.com](zynga.com) to the Facebook Container first (via the doorhanger). I confirmed it works with the latest release.
