### ISSUE TITLE
Breaking 'gab.com'

### ISSUE THREAD

**Issue by ronaaron** [mozilla/contain-facebook#394]
I've been using the Facebook container just fine, and have had no problems using gab.com.

But as of this morning, I can't access gab.com *if* the FB container is active.  If I disable it, I can access gab just fine.

**Comment by maxxcrawford** [comment]
We have a fix in for this: PR #384. It will be resolved next week in our next release. Thanks!

**Comment by maxxcrawford** [comment]
@ronaaron Did the new version resolve this for you?

**Comment by ronaaron** [comment]
On 28/05/2019 3:41, Maxx Crawford
      wrote:
    
    
      
      @ronaaron
        Did the new version resolve this for you?
    
    
    
    Yes it did, thank you!
    
    
      
        [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mozilla/contain-facebook/issues/394?email_source=notifications\u0026email_token=AECUVBV4VKHIODCZ734S4DDPXR5UZA5CNFSM4HOZ4XYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWKVUAI#issuecomment-496327169",
"url": "https://github.com/mozilla/contain-facebook/issues/394?email_source=notifications\u0026email_token=AECUVBV4VKHIODCZ734S4DDPXR5UZA5CNFSM4HOZ4XYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWKVUAI#issuecomment-496327169",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
      
    
    
      
        
          Ron Aaron | 
           CTO  Aaron High-Tech, Ltd |
          +1 516.373.0794 / +972 52.652.5543 |
          
            GnuPG Key: 91F92EB8
