### ISSUE TITLE
Breaking raider.io

### ISSUE THREAD

**Issue by nina-j** [mozilla/contain-facebook#396]
### Version/OS Information
- Facebook Container Version: 1.9.0
- Operating System + Version: Antergos Linux + Windows 10
- Firefox Version: 66.0.3
- Other installed Add-ons + Version + Enabled/Disabled-Status:
![image](https://user-images.githubusercontent.com/28903001/58249062-26088080-7d5e-11e9-935a-55559d717dd3.png)

### Actual behavior
raider.io loads with black screen if the Facebook container is enabled. If disabled, raider.io loads just fine. Facebook container detects no trackers on raider.io.

### Expected behavior
raider.io loads as expected with Facebook container enabled, no previous issues.

### Steps to reproduce
1. Enable Facebook container
2. Visit raider.io and login

**Comment by maxxcrawford** [comment]
This uses the same __rocketLoaderInlineHandlerProxy as #384. It will be resolved next week in our next release. Thanks!

**Comment by maxxcrawford** [comment]
@nina-j Did the new version resolve this for you?

**Comment by nina-j** [comment]
@maxxcrawford It did! Thanks.
