### ISSUE TITLE
Facebook Container blocking ability to download pdfs from ScienceDirect.com

### ISSUE THREAD

**Issue by FSDKNS** [mozilla/contain-facebook#397]
- Facebook Container Version: 1.90
- Operating System + Version: Windows 10 Version 10.0.17134
- Firefox Version: 67.0
- Other installed Add-ons + Version + Enabled/Disabled-Status:
![Extensions](https://user-images.githubusercontent.com/50951213/58250460-cc777480-7da4-11e9-99b6-6fc2b1546abd.PNG)

### Actual behavior

Upon clicking "Download PDF", a new tab is opened and remains blank.

### Expected behavior

Upon clicking "Download PDF", a new tab should open with the PDF open.
### Steps to reproduce
1. You will need access to a database which allows you to see and download the articles on sciencedirect.com .
2. Have Facebook Container enabled.
3. Search for any article.
4. Click on "Download PDF".

### Notes
I tried isolating the issue and found Facebook Container to be the problem. This occurs even if I have an external application listed as default in the settings to open pdfs. Pretty annoying when trying to find sources for reports.

**Comment by maxxcrawford** [comment]
Are there any specific console errors? We have a PR in the queue to resolve a `window.onload` overwrite Issue. They may be related.

**Comment by maxxcrawford** [comment]
Just checked – this site uses the same `__rocketLoaderInlineHandlerProxy` as #384. It will be resolved next week in our next release. Thanks!

**Comment by maxxcrawford** [comment]
@FSDKNS Did the new version resolve this for you?

**Comment by FSDKNS** [comment]
@maxxcrawford Yep it did, thanks!
