### ISSUE TITLE
Language change bar doesn't work on opensubtitles.org

### ISSUE THREAD

**Issue by vesterlay** [mozilla/contain-facebook#398]
- Facebook Container Version: 1.9.0 
- Operating System + Version: Windows 10 
- Firefox Version: Firefox Developer Edition 68.0b3 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:
![extensions](https://user-images.githubusercontent.com/39202451/58276307-659f8e80-7d97-11e9-85e6-62c4baec1ffc.png)

### Actual behavior
Language changing bar is appearing but it's broken. 

### Expected behavior
Bar is working correctly so that you can change language of subtitles. 

### Steps to reproduce
1. Visit this site

**Comment by maxxcrawford** [comment]
This uses the same `__rocketLoaderInlineHandlerProxy` as #384. It will be resolved next week in our next release. Thanks!

**Comment by maxxcrawford** [comment]
@vesterlay Did the new version resolve this for you?
