### ISSUE TITLE
Kickstarter "continue with Facebook" is broken

### ISSUE THREAD

**Issue by arthur-mozilla** [mozilla/contain-facebook#400]
Kickstarter "continue with Facebook" button doesn't do anything. Also, there is no badge.

https://www.kickstarter.com/login?ref=nav

![image](https://user-images.githubusercontent.com/48572191/58286702-2e63ba00-7d64-11e9-8704-93fc1215d8dc.png)

**Comment by maxxcrawford** [comment]
Added site support to the PR #385: 

![image](https://user-images.githubusercontent.com/2692333/58292962-2702d780-7d89-11e9-99e4-ebf793e37775.png)
