### ISSUE TITLE
FB Container causes error to occur in jQuery/Zurb Foundation Javascript

### ISSUE THREAD

**Issue by peginald** [mozilla/contain-facebook#403]
On my web site (which to my knowledge does not reference Facebook at all) I get a Javascript error when trying to lazy load some images (functionality coded using jQuery and Zurb Foundation).

Error: Permission denied to access property "apply".
Error in javascript/foundation6/foundation.min.1558640810.js:1

This only occurs when the FB Container is enabled and does not occur in Chrome or Edge browsers. It has only started snce I updated FF yesterday and I have the latest version of FB Container.

My site is NSFW (toys for adults, no rude pics) but if you are want to look and won't lose your job, it is jodivineDOTcom

I believe this may be related to issues #402 and #393 and has only started happening yesterday (which naturally occurred while I was setting up a new server and so I spent hours on a wild goose chase assuming it was something I had done!).

![Capture](https://user-images.githubusercontent.com/50987696/58322425-d9ce4680-7e18-11e9-98f3-23b6302b544a.JPG)

**Comment by maxxcrawford** [comment]
Searching and stumbled across another add-on dealing with the same issue. Looking into this now! 

https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/241

**Comment by maxxcrawford** [comment]
We have a PR (#385 ) in that solves for instances like this. Tested the site with that PR and did not get the `apply` issue! This will be in next week. Thanks! 

![image](https://user-images.githubusercontent.com/2692333/58331351-8f3fd080-7dfe-11e9-9a7a-a20d55333a3c.png)

**Comment by maxxcrawford** [comment]
@peginald Did the new version resolve this for you?

**Comment by peginald** [comment]
Yes, all working now, thanks for your help.
