### ISSUE TITLE
Breaks institutional Elsevier research joural access

### ISSUE THREAD

**Issue by ericjbringley** [mozilla/contain-facebook#405]
Using the latest update pushed by the firefox extension publisher, the container disables institutional access for Elsevier journals via Science Direct. You are unable to view the paper or download the paper. Disabling the extension and reloading the page allows you to view the full text on the webpage and then download the paper as expected. 

### Steps to reproduce
1. Log into University VPN or other institutional Elsevier journal access for science direct. 
2. Try to view an article without success (abstract loads but the full text does not for journals that you should have institutional access to)
3. Try to download an article without success. 
4. Disable extension and reload the webpage. Full text, figures, citations, references and download links work again. 

### Notes
Ubuntu 16.04LTS, Firefox 67.0, 22 May 2019 Extension update

**Comment by maxxcrawford** [comment]
@ericjbringley Can you please [update to the latest version](https://support.mozilla.org/en-US/kb/how-update-add-ons) of the release ([1.9.2](https://github.com/mozilla/contain-facebook/releases/tag/1.9.2)) and check again?

**Comment by maxxcrawford** [comment]
@ericjbringley Can you also provide which version of the add-on you're using?

**Comment by ericjbringley** [comment]
@maxxcrawford I've now got version 2 and it works again.
