### ISSUE TITLE
floating facebook-container-icon after scrolling down at LifeHacker

### ISSUE THREAD

**Issue by dholbert** [mozilla/contain-facebook#406]
- Facebook Container Version: ~1.9.0~ Edit: 1.7.3 (not sure where the 1.9.0 number came from, but I've now [installed 1.7.3](https://github.com/mozilla/contain-facebook/releases/tag/1.7.3) which I think is newest)
- Operating System + Version: Ubuntu 19.04
- Firefox Version: Nightly 69 2019-05-24
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
Floating facebook container icon near top right corner, not covering up any visible Facebook button.

### Expected behavior
No such floating icon.

### Steps to reproduce
1. Visit https://lifehacker.com/what-to-do-if-you-miss-your-flight-1834889383 in a maixmized (or at least pretty-large) window.
2. Scroll down the page a bit.
3. Look at the top right corner.

Screenshot:
![image](https://user-images.githubusercontent.com/426803/58370968-9b409680-7ec1-11e9-84e2-8768602a5ad8.png)

**Comment by maxxcrawford** [comment]
I have a PR in to resolve this. 🏄 

![image](https://user-images.githubusercontent.com/2692333/58731463-61d1c480-83b4-11e9-9331-f00b23dc32b2.png)
