### ISSUE TITLE
Broken on theguardian.com

### ISSUE THREAD

**Issue by jeremysanders** [mozilla/contain-facebook#409]
- Facebook Container Version: 1.9.1
- Operating System + Version: Ubuntu 18.04 (x86-64)
- Firefox Version: 67.0 (Ubuntu provided version)
- Other installed Add-ons + Version + Enabled/Disabled-Status: uBlock origins 1.19.6 (occurs even if this extension is disabled for the site)

### Actual behavior
On the comments section of theguardian.com, multiple facebook container icons get scattered over the comments section. This doesn't happen immediately, but occurs if you click through the multiple pages of comments on an article. e.g.

![image](https://user-images.githubusercontent.com/274711/58412589-0e3f3e00-8077-11e9-8600-e9f7c4950ae4.png)

There appears to be more than one icon per comment and they cover the comments.

### Expected behavior
Icons should appear where the facebook  share button is and not over the comments.

### Steps to reproduce
1. Browse to https://www.theguardian.com/
2. Go to an article with comments, e.g. https://www.theguardian.com/commentisfree/2019/may/24/next-tory-leader-panel-theresa-may-conservatives#comments
3. Scroll through the comments, click forward to the next page of comments a few times.

**Comment by maxxcrawford** [comment]
Dug into the CSS: It's using `transform: scale(0)` to hide the hover/toggle object. This makes it "visible" to the detection script, even though it's not actually visible.
