### ISSUE TITLE
badge hover text goes under a content image

### ISSUE THREAD

**Issue by arthur-mozilla** [mozilla/contain-facebook#413]
Seen on https://www.theguardian.com/world/2019/may/27/abortion-democrats-republicans-state-laws

![image](https://user-images.githubusercontent.com/48572191/58524522-55aff200-817d-11e9-9351-1a7416052e02.png)

**Comment by maxxcrawford** [comment]
Resolved! Note – This won't be fixed everytime. The badge only matches the `z-index` of the blocked element and its' parents. 

![image](https://user-images.githubusercontent.com/2692333/58677505-d14aa400-8321-11e9-93d4-b947c1c97965.png)

**Comment by maxxcrawford** [comment]
Resolved! Note – This won't be fixed everytime. The badge only matches the `z-index` of the blocked element and its' parents. 

![image](https://user-images.githubusercontent.com/2692333/58677505-d14aa400-8321-11e9-93d4-b947c1c97965.png)
