### ISSUE TITLE
Facebook Container appears to make browser hang when new tabs are opened

### ISSUE THREAD

**Issue by Vinnl** [mozilla/contain-facebook#416]
- Facebook Container Version: 1.9.1 currentl
- Operating System + Version: Ubuntu 18.04
- Firefox Version: 67
- Other installed Add-ons + Version + Enabled/Disabled-Status:

> Behind The Overlay Revival	1.8.3	true	{c0e1baea-b4cb-4b62-97f0-278392ff8c37}
> Decentraleyes	2.0.11	true	jid1-BoFifL9Vbdl2zQ@jetpack
> Feed Preview	7	true	feed-preview@code.guido-berhoerster.org
> Firefox Lockwise	2.2.2-alpha	true	lockbox@mozilla.com
> Firefox Multi-Account Containers	6.1.0	true	@testpilot-containers
> Firefox Pioneer	1.0	true	pioneer-opt-in@mozilla.org
> GNOME Shell integration	10.1	true	chrome-gnome-shell@gnome.org
> HTTPS Everywhere	2019.5.13	true	https-everywhere@eff.org
> In-Page Pop-up Reporter	1.6	true	{feb799e2-29e2-4e35-b862-cc4e1842b6f5}
> Panorama View	0.8.3	true	{60e27487-c779-464c-8698-ad481b718d5f}
> Plaudit	0.1.25	true	{82c27c82-29f7-477c-8588-6255c1b59a2a}
> Privacy Badger	2019.2.19	true	jid1-MnnxcxisBPnSXQ@jetpack
> React Developer Tools	3.6.0	true	@react-devtools
> Reddit Enhancement Suite	5.16.7	true	jid1-xUfzOsOFlzSOXg@jetpack
> Smart Referer	0.2.10	true	smart-referer@meh.paranoid.pk
> Subtle Improvements for Hacker News	1.3.0	true	{472cf3ad-cd7a-4d6f-bb67-845a78eef45f}
> Switch Container	0.8	true	{c580e2d6-885a-4cb9-af49-59b3b48350e9}
> Tab Center Redux	0.7.1	true	{0ad88674-2b41-4cfb-99e3-e206c74a0076}
> Test Pilot	3.0.6vffecb95	true	@testpilot-addon
> Total Suspender	3.3	true	{77497113-dd7f-4e91-b31f-9c1625e884c7}
> uBlock Origin	1.19.6	true	uBlock0@raymondhill.net
> Vim Vixen	0.22	true	vim-vixen@i-beam.org
> Ad Analysis for Facebook - DISABLED	1.1.0	false	AdAnalysisForFacebook@firefox.com
> Add-on Compatibility Reporter	2.2.4	false	compatibility@addons.mozilla.org
> Cast Kodi	3.3.3	false	castkodi@regseb.github.io
> Data Selfie	0.1.2	false	{87dfccf4-b6eb-4297-948a-ac6fd273cbb5}
> DITM	1.1.5	false	ditm@unmht.org
> Facebook Container	1.9.1	false	@contain-facebook
> Facebook Political Ad Collector	1.8.4	false	{b73c39bb-a086-4964-8091-672c3dcf1bc9}
> OpenLink Structured Data Sniffer	2.16.33	false	osds@openlinksw.com
> Redux DevTools	2.17.1	false	extension@redux.devtools
> Side View	0.4.3710	false	side-view@mozilla.org
> Simplify Gmail	1.4.0	false	{a4c1064c-95dd-47a7-9b02-bb30213b7b29}
> Snooze Tabs	1.1.1	false	snoozetabs@mozilla.com
> Tab Groups	2.1.4	false	tabgroups@quicksaver
> Temporary Containers	0.97	false	{c607c8df-14a7-4f28-894f-29e8722976af}
> Terms of Service; Didn’t Read	2.0.0	false	jid0-3GUEt1r69sQNSrca5p8kx9Ezc3U@jetpack
> Tree Style Tab	3.0.15	false	treestyletab@piro.sakura.ne.jp
> VimFx	0.20.10	false	VimFx@akhodakivskiy.github.com
> Vimium	1.64.6	false	{d7742d87-e61d-4b78-b8a1-b469842139fa}
> Wildfire	1.3.9	false	support@wildfire.ai

### Actual behavior

When I open a new tab, Firefox freezes for a bit. After waiting a few seconds I can scroll the page again or switch to other tabs.

### Expected behavior

For Firefox to behave normally.

### Steps to reproduce

I'm not quite sure how this happens and if it happens for everyone. It started happening for me about a week ago, I think. I checked a few things, then checked which extensions had recently updated. One of those was Facebook Container, and after I disabled it it disappeared - and it reappears when I enable it.

**Comment by maxxcrawford** [comment]
@Vinnl Can you verify this behavior with ONLY the Facebook Container add-on enabled? We want to narrow the field some. I'm closing the issue for now. Please re-open it if the problem persists.
