### ISSUE TITLE
Breaks magicseaweed forecasts website

### ISSUE THREAD

**Issue by gsalgado** [mozilla/contain-facebook#423]
I've recently noticed that with the FB container extension enabled, the map in the middle of 
https://magicseaweed.com/Spain-Portugal-Surf-Forecast/8/ does not load. I was able to reproduce this on a fresh profile with the following versions:

Ubuntu 19.04
Firefox 67.0
Facebook container 1.9.1
No other extensions

### Actual behavior
Map contained in the page does not load 

### Expected behavior
Map should load

### Steps to reproduce
1. Start firefox using a fresh profile and access https://magicseaweed.com/Spain-Portugal-Surf-Forecast/8/; you should see a map of West Europe
2. Install FB Container
3. Reload the URL above, and the map is gone

**Comment by maxxcrawford** [comment]
@gsalgado Can you please [update to the latest version](https://support.mozilla.org/en-US/kb/how-update-add-ons) of the release ([1.9.2](https://github.com/mozilla/contain-facebook/releases/tag/1.9.2)) and check again?

**Comment by gsalgado** [comment]
Just tested and issue is still present in 1.9.2

**Comment by maxxcrawford** [comment]
@gsalgado Did some further digging. 

Got this error on that page with FBC running: 

```
Error: Script error for: facebook
http://requirejs.org/docs/errors.html#scripterror
```

This is may be a site-specific issue. I'm tagging the two devs on the magicseaweed project on Github.

@ljwall @buxton Can you please take a look?

**Comment by ljwall** [comment]
Hi, yep, I can reproduce.

We're loading assets with requirejs, which is inserting a script tag into the `head` to load `https://connect.facebook.net/en_US/sdk.js`. It seems this is being blocked by the the FB container extension --- is that the expected behaviour? Requirejs is picking up an error event on the script tag

Either way, the map (plus other some other components) ought to load independent of the Facebook sdk; will take a look at fixing. Thanks!

**Comment by maxxcrawford** [comment]
@ljwall Blocks the SDK is expected behavior – this add-on blocks all Facebook-specific resources from loading on any page not inside the Facebook (Facebook-owned domains, facebook.com, etc) container. Thank you!

**Comment by maxxcrawford** [comment]
@gsalgado Is this still reproducible in [v2.1.1](https://github.com/mozilla/contain-facebook/releases/tag/2.1.1)?

**Comment by ljwall** [comment]
@maxxcrawford pretty sure we fixed the issue on our side --- apologies for not returning to this ticket to let you know. FB sdk being blocked should not prevent other js from loading (in particular the map). I've test with facebook-container 2.1.1 and all seems good. If anyone sees further issue please go ahead and tag me.

**Comment by gsalgado** [comment]
I can't reproduce it either
