### ISSUE TITLE
medium.com floater badge

### ISSUE THREAD

**Issue by arthur-mozilla** [mozilla/contain-facebook#425]
For example:
https://medium.com/mofed/css-line-clamp-the-good-the-bad-and-the-straight-up-broken-865413f16e5

![image](https://user-images.githubusercontent.com/48572191/58597234-df1dfd80-822b-11e9-9e11-8158aa278363.png)

**Comment by arthur-mozilla** [comment]
Even when the Facebook button is visible, the badge sometimes sticks to it and sometimes floats away.

**Comment by maxxcrawford** [comment]
Same/similar problem that's occurring with #389 on Imgur.

**Comment by maxxcrawford** [comment]
Note – I have a PR in #427 in that will land tomorrow/Monday to resolve this!
