### ISSUE TITLE
1.9.1 breaks Kibana front end for ELK stack application

### ISSUE THREAD

**Issue by jyentile** [mozilla/contain-facebook#426]
- Facebook Container Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
Loading an ELK stack throws exceptions with contain-facebook 1.9.1 enabled. Errors reported by Kibana as shown in screenshot and in txt below:

TypeError: _define.modules is undefined
Error: [ng:btstrpd] App Already Bootstrapped with this Element 'document'

<img width="1792" alt="Screenshot 2019-05-29 19 15 07" src="https://user-images.githubusercontent.com/1228593/58597568-8c057400-8246-11e9-8e34-4799eb20a55d.png">

### Expected behavior
App works as designed and Kibana loads correctly with contain-facebook disabled (and also worked as designed prior to 1.9.1 update)

### Steps to reproduce
1. 
2.
3.

**Comment by bvschaik** [comment]
"App already bootstrapped" leads me to think this has the same cause as #420; I proposed a fix in PR #421.

**Comment by jyentile** [comment]
Tested...appears to be resolved in 1.9.2 (which is now in AMO, BTW). Thanks for quick turnaround!

**Comment by maxxcrawford** [comment]
Excellent. Thanks to @bvschaik! 🎉
