### ISSUE TITLE
Floating badge icon on techgenix.com

### ISSUE THREAD

**Issue by cpeterso** [mozilla/contain-facebook#428]
- Facebook Container Version: 1.9.1
- Operating System + Version: Windows 10
- Firefox Version: 69 Nightly

### Actual behavior

The Facebook Container badge is floating over the article text as you scroll down the page.

### Expected behavior

The badge should stay at the top of the page or disappear after the page starts scrolling.

### Steps to reproduce
1. Load http://techgenix.com/app-v-or-windows-containers/
2. See the Facebook Container badge hovering over the article's banner image.
3. Scroll down the page.

### Screenshot

![image](https://user-images.githubusercontent.com/629193/58668926-4d77c400-82ef-11e9-9a80-6b34cf172b2e.png)

**Comment by maxxcrawford** [comment]
This seems to be resolved in the last version of the add-on: [1.9.2](https://github.com/mozilla/contain-facebook/releases/tag/1.9.2). Can you [update your add-on](https://support.mozilla.org/en-US/kb/how-update-add-ons) and re-verify? Closing for now, but re-open it if the problem persists. 

_*Note – we published the update around 11am CDT today, so it should rolled out to all active users within the first 24 hours._

**Comment by cpeterso** [comment]
👍 I upgraded to version 1.9.2 and I can no longer reproduce the bug. (I don't see a Facebook badge on the page at all.)

**Comment by maxxcrawford** [comment]
Strange – it should be badging this button instead. 

![image](https://user-images.githubusercontent.com/2692333/58726272-ec132c00-83a6-11e9-9158-cd49b8539f65.png)

**Comment by cpeterso** [comment]
> Strange – it should be badging this button instead.

Hmm. I see the Facebook badge (correctly attached to the "SHARE ON FACEBOOK" button) now. 👍

**Comment by maxxcrawford** [comment]
Awesome! Thanks for filing this issue.
