### ISSUE TITLE
Web page reloads every 1.5 s when Facebook Container is enabled

### ISSUE THREAD

**Issue by larsheriksen** [mozilla/contain-facebook#429]
- Facebook Container Version: 1.9.1
- Operating System + Version: Windows 7 and 10 tested
- Firefox Version: 67.0
- Other installed Add-ons + Version + Enabled/Disabled-Status:
ETP Search Volume Study	1.2	true	etp-search-volume-study@shield.mozilla.org
Facebook Container	1.9.1	true	@contain-facebook
Adobe Acrobat	18.0.2	false	web2pdfextension.17@acrobat.adobe.com
HTTPS-everywhere	2019.5.13	false	https-everywhere@eff.org
Office Launcher	1.0	false	officelaunch@microsoft.com
Ta skjermbilder av hele nettsider - FireShot	0.98.96	false	{0b457cAA-602d-484a-8fe7-c1d894a011ba}

### Actual behavior
The web-store "https://hallstrom.mamutweb.com/" (and presumably other *.mamutweb.com webstores, as well as certain other websites out there) reload constantly (about every 1-5 seconds). The reloading and reformatting during regeneration makes the website almost impossible to use.

### Expected behavior
Load once and stable display of the web page.

### Steps to reproduce
1. Enable Facebook Container
2. Open "https://hallstrom.mamutweb.com/"

**Comment by maxxcrawford** [comment]
I checked this site against our PR that we're merging into today and did not see any of the issues. That may resolve it – but I also checked it against the current main release and also was unable to reproduce it. Can you disable your other add-on's and confirm the behavior is isolated to this add-on?

**Comment by larsheriksen** [comment]
After reinstalling Facebook Container, I no longer have the problem. The version of Facebook Container has also changed from 1.9.1 to 1.9.2. I don’t know whether that is the reason. This was on a PC with Windows 10.

 

Tested today also on the other computer running Windows 7. The reinstalled Facebook Container is now at version 2.0. Again, problem is gone.

 

Case closed I think.

 

By the way, I did try disabling my other add-ons. Disabling all add-ons removed the problem, but it reappeared once I re-enabled Facebook Container. I tried this several times. But now the problem seems to be gone. J

 

Fra: Maxx Crawford [mailto:notifications@github.com] 
Sendt: 3. juni 2019 15:55
Til: mozilla/contain-facebook
Kopi: larsheriksen; Author
Emne: Re: [mozilla/contain-facebook] Web page reloads every 1.5 s when Facebook Container is enabled (#429)

 

I checked this site against our PR that we're merging into today and did not see any of the issues. That may resolve it – but I also checked it against the current main release and also was unable to reproduce it. Can you disable your other add-on's and confirm the behavior is isolated to this add-on?
