### ISSUE TITLE
"Like <website>" button doesn't get updated with the "check" sign after liking a website by clicking the same button

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/contain-facebook#43]
**[Notes]:**
- This is also reproducible on other websites, such as:
https://uk.news.yahoo.com/
www.9gag.com

**[Affected versions]:**
- Firefox 59.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Facebook Container" add-on (1.2.3) installed.
- You must be logged in to Facebook.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to https://www.betterhelp.com/ website and scroll to the bottom of the page.
3. Click the "Like 855K" button from the right side of the page.
4. Click the "Like" button from the newly opened tab and observe what happens next.

**[Expected result]:**
- The newly opened tab is closed and the "Like 855K" button from the website is updated displaying a "check" sign.

**[Actual result]:**
- "Go back to (website link)" is displayed in tab and the "Like 855K" button from the website doesn't update.

**[Additional Notes]:**
- Attached a screen recording of the issue: 

![like button not updating](https://user-images.githubusercontent.com/26000308/37973737-da360b80-31e3-11e8-8e05-c14bb54b44b2.gif)

**Comment by TanviHacks** [comment]
This is as expected  Like buttons on non-facebook pages won't work.

**Comment by maxxcrawford** [comment]
This issue has changed, as the Like button has now been completely removed by blocking Facebook resources. 

Related issue: #277 

![image](https://user-images.githubusercontent.com/2692333/58981374-e0a17580-8797-11e9-9939-e1813e545ca1.png)
