### ISSUE TITLE
No tracker but gate still shown

### ISSUE THREAD

**Issue by danm** [mozilla/contain-facebook#430]
On the page https://www.bbc.co.uk/news/business-48473259 (and all other news pages), `Facebook Container` shows there being no trackers, but will still put a Gate icon on a button which allows a user to like/ share the story.

It is my understanding that the BBC went to special measures in order not to add *any* FB tracking to our news pages.

We have two FB icons on our page, and only one has the gate icon on it. Is there anything we can do, either by committing to this project, or adjusting code on our page to avoid the gate?

It is important to us as a public organisation that we are clear where data goes and we do not share to 3rd parties within our own platform. I'd like to avoid people believing we have FB tracking.

thoughts?

<img width="895" alt="Screenshot 2019-06-04 at 19 51 29" src="https://user-images.githubusercontent.com/6394846/58905659-2ca1db00-8702-11e9-88c3-3f636d364d48.png">
<img width="890" alt="Screenshot 2019-06-04 at 19 51 19" src="https://user-images.githubusercontent.com/6394846/58905660-2ca1db00-8702-11e9-8c05-ed2a7502a544.png">

**Comment by maxxcrawford** [comment]
We'll look into this and get back to you. Thanks! 

cc/ @groovecoder @arthur-mozilla

**Comment by paglias** [comment]
Hi, we're having the same problem on Habitica.com when logged in. We do not include any FB script but only provide share links. Same behavior as reported by @danm 
<img width="1433" alt="Schermata 2019-06-05 alle 20 04 37" src="https://user-images.githubusercontent.com/589911/58979330-1c573200-87ce-11e9-8297-56bf058721a8.png">

**Comment by maxxcrawford** [comment]
From #483 / @michal-minich : 

> As an user, now I think marking a ordinary FB link can be useful. This time
it is very clear for user that the link goes to FB - it contains text
"Share on Facebook" (and has simple FB icon). But often there are link with
text which makes it unclear it goes to FB. In that case it is useful to
mark it.

Still I would suggest different kind of icon mark for blocked content, VS
just an adding marking label for ordinary link.

**Comment by Krinkle** [comment]
Hovering the gate icon above the regular hyperlink to Facebook shows: "_Facebook Container has disabled this button and blocked Facebook from tracking your visit to this page._"

This text seems to be aimed at tracking-buttons that allow Facebook to track you before interacting with the link (which is indeed how those buttons work), but that is not the case here.

Perhaps it should say something along the lines of "_Facebook Container has disabled this regular link to facebook.com to make sure you don't accidentally click it. Unlike tracking links, this regular link would only allow Facebook to track your visit to this page after clicking it._"

**Comment by e-pang** [comment]
When hovering the button the badge and tooltip appear. To make it clear that there are no trackers on the button before interaction update string to: 

"If you click this button, Facebook will be able to track your visit to this site."

<img width="1267" alt="fbc" src="https://user-images.githubusercontent.com/30128313/64288895-34eff900-cf31-11e9-86a5-fa09ba23f587.png">

**Comment by technotarek** [comment]
One thing that isn't mentioned above and makes this issue a bit more troubling than it might seem at first glance is that, at least in some cases, Facebook Container disables the safe / non-tracking links. It's more than just warning the user; it's actually preventing proper usage of the site. See https://github.com/mozilla/contain-facebook/issues/516.

**Comment by dend** [comment]
This is a problem on docs.microsoft.com - we have customers who are reporting that we are using Facebook tracking pixels, when the only thing that we are doing is providing a link to share on Facebook, which does not execute anything client-side.
