### ISSUE TITLE
Blacklist facebook.com too

### ISSUE THREAD

**Issue by crazyyzarc** [mozilla/contain-facebook#434]
Can I remove Facebook.com from the scope of protection of Facebook Containers? I do not use Facebook and therefore I want to keep everything as small as possible.

**Comment by maxxcrawford** [comment]
Can you elaborate? I'm not understanding what you'd like to do.

**Comment by crazyyzarc** [comment]
I want to block Facebook completely, but Facebook Container contains a whitelist for the following domains:
facebook.com
instagram.com
messenger.com

How do I remove this whitelist?

**Comment by groovecoder** [comment]
Where do you see those domains included in a whitelist? Do you mean the "Sites allowed in Facebook Container" panel?

**Comment by maxxcrawford** [comment]
@crazyyzarc 

I believe you're referring to this panel:

![image](https://user-images.githubusercontent.com/2692333/59208263-575eba00-8b6e-11e9-80a7-3623a6c13298.png)

This site list is the core purpose of the Facebook Container. It puts those specific sites (all known owned/controlled websites from Facebook) into their own container. [This container](https://support.mozilla.org/en-US/kb/containers#w_what-are-containers) is walled off from the rest of the browser, which includes your site preferences, logged in sessions, and advertising tracking data. 

By using this add-on, you're keeping Facebook portioned from the rest of your browser, thus blocking it.
