### ISSUE TITLE
The Plugin blocks buttons without facebook contact (like Shariff buttons)

### ISSUE THREAD

**Issue by AlbiWe** [mozilla/contain-facebook#441]
The detection of Facebook buttons is not yet perfect. For example, the Shariff button is blocked, which is unnecessary. It restricts functionality . 

see https://github.com/heiseonline/shariff

**Comment by maxxcrawford** [comment]
This in an ongoing issue currently for non-privacy invading share buttons being badged. 

Marking as a duplicate of #430
