### ISSUE TITLE
Auto switch to facebook container not working

### ISSUE THREAD

**Issue by SushilShrestha** [mozilla/contain-facebook#444]
Before last update, facebook used be on facebook tab automagically even if I didn't open it on the facebook tab manually. Now the function is broken and when I open facebook on normal tab it won't automagically switch to facebook tab. I have to manually go to facebook tab and open facebook.

- Facebook Container Version: June 11, 2019
- Operating System + Version: MacOS Sierra
- Firefox Version: 67.0.2
- Other installed Add-ons + Version + Enabled/Disabled-Status:

Awesome Screenshot - Capture, Annotate & More	3.0.24
BuiltWith	2.1
Facebook Container	2.0
Firefox Multi-Account Containers	6.1.0
JSON Lite	19.3.1
Privacy Badger	2019.2.19
The Camelizer	2.10
uBlock Origin	1.20.0

### Actual behavior
facebook.com should open automagically on facebook tab

### Expected behavior
have to manually switch to facebook tab

**Comment by maxxcrawford** [comment]
Is this still reproducible on the latest version of the add-on (2.1.1) and Firefox (77.0.1)?

Additionally, can you confirm this behavior exists when you have Multi-account Containers disabled?

**Comment by SushilShrestha** [comment]
Yup the problem still persist with following configuration

- Facebook Container Version: 2.1.1
- Operating System + Version: MacOS Catalina
- Firefox Version: 77.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status:


BuiltWith	2.1
Facebook Container	2.1.1
JSON Lite	19.6.0
Privacy Badger	2020.6.2
React Developer Tools 4.7.0
uBlock Origin	1.27.10

**Comment by maxxcrawford** [comment]
@SushilShrestha Thanks for confirming. We'll dig in.  

I am still having trouble reproducing the issue. If you have any additional debug information you can provide, it's much appreciated!

**Comment by SushilShrestha** [comment]
I managed to fixed the issue by reinstalling the addon( should have tried that earlier). I think the issue was related to normalization of storage data or something (from about:debugging console). 
As of now, it's working fine. Thanks 🎉

**Comment by maxxcrawford** [comment]
Awesome! Thanks!
