### ISSUE TITLE
Does not work with Honey extension in Firefox at same time

### ISSUE THREAD

**Issue by MTX281** [mozilla/contain-facebook#445]
- Facebook Container Version: 11.3.5
- Operating System + Version: Win7pro
- Firefox Version: 67.0.2 64bit
- Other installed Add-ons + Version + Enabled/Disabled-Status: Honey, Strict popup blocker, ublock origin,  Adblock

### Actual behavior
Right clicking on links in FB to open in a non fb container still open with FB wrapper link/fb source  in web address. 

### Steps to reproduce
1. refreshed Firefox
2. reinstalled add ons
3. same issue as long as honey was enabled

**Comment by MTX281** [comment]
https://www.joinhoney.com

**Comment by maxxcrawford** [comment]
This is normal Multi-account Container behavior (what this add-on is built on) – any link you click inside a specific container should open in the same contain unless: 

- That URL has been check marked to always open in a specific container 
- In Facebook Containers' case, that URL is on a Facebook-owned domain. 

I recommend installing [Multi-account Container add-on](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) and using their ["right-click to open in a different container" feature](https://support.mozilla.org/en-US/kb/containers#w_open-links-in-new-tabs-and-containers) to get outside of the Facebook container while clicking links from inside Facebook. 

Thanks!

**Comment by maxxcrawford** [comment]
@MTX281 Note – I opened an issue to make sure to add login detection support, which can add the Honey domain to the Facebook container. It doesn't directly resolve your issue, but it does make sure that Facebook login support works on the Honey website.

**Comment by korishan** [comment]
I know this is an old thread, but I found that the Privacy Badger addon for firefox was keeping mine from logging in. I started with "Facebook Container", then moved 1 at a time through "Tampermonkey", "uBlock Origin", and then "Privacy Badger".
