### ISSUE TITLE
Spotify log in causes infinite open/closing tab

### ISSUE THREAD

**Issue by nbreum15** [mozilla/contain-facebook#447]
- Facebook Container Version: 2.0
- Operating System + Version: Windows 10 Version 10.0.17763 Build 17763 
- Firefox Version: 68.0b10
- Other installed Add-ons + Version + Enabled/Disabled-Status:
All addons except Facebook Container are disabled.

### Actual behavior
When I go to www.spotify.com and press Log In goes into an infinite redirect loop, opening and closing the Facebook container.

### Expected behavior
Stay in Facebook Container, and do not redirect back to non-facebook container tab.

### Steps to reproduce
1. Go to www.spotify.com.
2. Press Log In and then Facebook log in.

**Comment by maxxcrawford** [comment]
Did you add Spotify to the Facebook container? (By clicking the “Allow” prompt from the badge)

**Comment by nbreum15** [comment]
I managed to add spotify.com to the Facebook container by:
1. First disabling Facebook Container addon.
1. Open Facebook container through Multi-Account Containers
1. Add spotify.com to Facebook container.
1. Enable Facebook Container addon again, now spotify.com opens in Facebook container.

Is there an easier way to do this, instead of having to disable the Facebook Container addon?

**Comment by maxxcrawford** [comment]
Yes!

1. Go to https://accounts.spotify.com
2. Click the badge
3. Click "Allow" 
4. Login as usual. 

![image](https://user-images.githubusercontent.com/2692333/59937150-5273f300-9417-11e9-9a34-3d7f26ae840b.png)

**Comment by maxxcrawford** [comment]
Actually, I just got the same loop. Looks like accounts.spotify.com is in the Facebook container, but spotify.com is not. Leaving this issue open to be resolved.

**Comment by maxxcrawford** [comment]
@groovecoder We need to look into adding the entire domain (not just the subdomain) to the contain when a user clicks allow.

**Comment by ultreson** [comment]
Quick question, how can one whitelist websites manually in facebook container? That would solve the problem, wouldn't it? Spotify facebook login still doesn't work as of the latest version.

**Comment by maxxcrawford** [comment]
@ultreson The feature you're describing is nearly complete. Follow the progress on Issue #422!
