### ISSUE TITLE
When you change the color of the Facebook container in options (black is ugly) it reverts back to black

### ISSUE THREAD

**Issue by hfball** [mozilla/contain-facebook#448]
- Facebook Container Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Steps to reproduce
1.
2.
3.

**Comment by hfball** [comment]
This used to be blue, and I prefer it that way, but I can't make it stay blue. Annoying.

**Comment by piecevcake** [comment]
I want it pink or red- I had it set then it CHANGED with an update?
How to change the colour?
I tried changing in multi account containers, didnt change it.
How to change the name (want to shorten it so doesnt take up so much address bar room)
firefox 67.04, windows 8.1

**Comment by maxxcrawford** [comment]
I'm merging this issue with #408
