### ISSUE TITLE
Howto: remove site from container

### ISSUE THREAD

**Issue by leotsarev** [mozilla/contain-facebook#449]
### Actual behavior
Suppose I mistakenly tried to use FB login in some site, despite all warnings and messages. Now this domain permanently stuck in FB container, w/o any simple option to remove it from container

### Expected behavior
Should be simple option to remove it from container. I.E. "Reopen in container" should work or it should be some kind of option/preference

### Steps to reproduce
1. Go to i.e. crowdrepublic.ru
2. Login with FB
3. Say YES to all warnings
4. Observe that crowdrepublic.ru is now in facebook container
5. This will break i.e. ability to pay any money to it
6. Try to reopen in container. Tab will reload, but still in FB container.
7. Try to browse FB container preferences. No luck

### Notes

I'm happy for some kind of temporary workaround, editing some esoteric files etc

**Comment by nbreum15** [comment]
I wrote this workaround in #447 for addings sites to the Facebook container, which I think should work for removing sites as well:

> I managed to add spotify.com to the Facebook container by:
> 1. First disabling Facebook Container addon.
> 1. Open Facebook container through Multi-Account Containers
> 1. Add spotify.com to Facebook container.
> 1. Enable Facebook Container addon again, now spotify.com opens in Facebook container.
> 
> Is there an easier way to do this, instead of having to disable the Facebook Container addon?

**Comment by maxxcrawford** [comment]
Once you've added a site to the container (Using the "Allow" prompt), they show up in the doorhanger panel: 

![image](https://user-images.githubusercontent.com/2692333/59937537-505e6400-9418-11e9-914b-7effad126f16.png)


![image](https://user-images.githubusercontent.com/2692333/59937527-476d9280-9418-11e9-97bf-af57f7b2d11e.png)

To remove a site, click the `X` on the added domain you'd like to remove.

**Comment by leotsarev** [comment]
thanks and sorry for spam
