### ISSUE TITLE
Include other facebook domains: instagram, whatsapp and messenger

### ISSUE THREAD

**Issue by nt1m** [mozilla/contain-facebook#45]
https://instagram.com
https://messenger.com
WhatsApp web client

**Comment by lavacano201014** [comment]
fbcdn.net should also be included, because otherwise when I click "Download" on someone's photo post, it opens the fbcdn.net URL outside the container and I can't click back.

**Comment by TanviHacks** [comment]
@lavacano201014 So downloading photos fails right now?

**Comment by lavacano201014** [comment]
The actual download completes successfully, at the cost of replacing my Facebook tab with an about:blank.

**Comment by Perflyst** [comment]
I add `fbcdn.net` with 8d3a61bd425a3c54ca3e7cc8ef5768531164f2ab in #46. Is there any other url which should be added?

**Comment by nt1m** [comment]
I also found `cdninstagram.com`

**Comment by Perflyst** [comment]
There are a lot of facebook domains, but are they needed? Set they some cookies? It is not the best solution to add all of them, isn't it?

Please write down a reproducible example, which I think is the best way to show the main contributor that these domains are needed.

**Comment by nt1m** [comment]
@groovecoder Could you decide ?

I think the current protection is quite flaky if escaping the "Facebook" container is as easy as viewing a Facebook or instagram photo.

Most instagram photos are served over `cdninstagram.com`, while most facebook photos are served over `fbcdn.net`.

**Comment by nt1m** [comment]
Add-ons like Decentraleyes exist because of the "tracking via CDNs" problem: https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/

**Comment by TanviHacks** [comment]
Does using Instagram automatically mean you are leaking data to Facebook?  You can sign in and use Instagram without Facebook right?  I don't think the user won't be able to login with Facebook (in the current state) and would only be able to login to Instagram using an Instagram account.

**Comment by Perflyst** [comment]
Instagram is owned by Facebook. You shouldn't trust it. The best way is to seperate everything with Temporary Containers.
But this addon should be as easy to use as possible and reach a mass. All Facebook services are likely to communicate with each other. How far one does not know, closed source. But I would recommend putting all Facebook services in a container for this add-on.

**Comment by nt1m** [comment]
@TanviHacks Instagram, like Messenger uses Facebook Login. The add-on in its current state only logged me out from Facebook, but not from the other two sites, which means Facebook can still associate my browser session from just my instagram/messenger usage, and serve me relevant ads.

**Comment by lavacano201014** [comment]
The idea that we shouldn't bother with CDN domains or with Instagram and co just because they aren't the main Facebook website is a pretty harmful way of thinking about this.

Applying a coat of lacquer to the surface isn't going to help when the wood's already rotted to the core.

**Comment by Perflyst** [comment]
Ah, very good point. I hadn't thought of that at all. Instagram can still follow you. Instagram also has a social button similar to Facebook which is displayed on a lot of pages.

Back to the Instagram cdn, I don't get a cookie or something similar from this domain which could track me over several pages...

Another problem is that any Like button can also set a cookie. He could also track the user without a logged in account and identify him if necessary.

**Comment by lavacano201014** [comment]
For tracking "logged out" users, we may need some sort of per-container configuration support in the browser in order to block that.

With that support, I could use ublock to block anything that comes from a Facebook owned domain unless I happen to be in a Facebook container.

At that point though, it might be better to just use a separate browser profile.

**Comment by Perflyst** [comment]
I check all the cdn's. No CDN set a cookie or fill your local storage.
Maybe someone can check which domains are needed, which not.
I know these domains which aren't added anywhere and maybe useful:
*.fbcdn.com
*.fbsbx.com
*.tfbnw.net
fb.me
*.facebook.com.edgesuite.net
*.facebook.com.edgekey.net
*.facebook.net.edgekey.net
facebook-web-clients.appspot.com
fbcdn-profile-a.akamaihd.net
*.fbsbx.com.online-metrix.net

cdninstagram.com
*.cdninstagram.com
instagramstatic-a.akamaihd.net
*.akamaihd.net.edgesuite.net

**Comment by lavacano201014** [comment]
Maybe rename the container to "Facebook, LLC" to make it clear that it's the same company?

**Comment by TanviHacks** [comment]
@ryanfeeley please read through this issue.

Question - would it make sense to separate Instagraom from Facebook?  Where Instagram and Facebook would have separate Cookie Jars (i.e. separate Containers).

**Comment by Perflyst** [comment]
In my opinion, nonsense. If Instagram tracks it gets to Facebook anyway. It all goes into the same database.

**Comment by TanviHacks** [comment]
Thanks!  Just trying to understand the upsides and downsides here.
Wondering if there is any privacy reason that this is not a good idea.

**Comment by marcus-crane** [comment]
Here's a list of Facebook domains: https://github.com/jmdugan/blocklists/tree/master/corporations/facebook

**Comment by ryanfeeley** [comment]
@marcus-crane Thanks for that list! @tanvihacks they should be lumped into the container ASAP before too many people notice and uninstall.

**Comment by pauljt** [comment]
@ryanfeeley see also https://github.com/mozilla/contain-facebook/issues/13 

URLs load as sub-resources are generally less of as issue, so long as the URL of the top-level page (ie what's in the address bar) is isolated.  i.e. loading a fbcdn.com link from a page outside your facebook container won't have a facebook cookie attached.

**Comment by jasonprado** [comment]
I was surprised when I navigated to messenger.com I was logged in, and it's not in a blue tab. Glad y'all are looking at this.

**Comment by oddmean** [comment]
There's also an official Tor hidden service: facebookcorewwwi.onion and some satellite .onion domains for Facebook CDN (like *.fbcdn23dssr3jqnq.onion). Add them to FACEBOOK_DOMAINS array in background.js please. May be the script should even fetch the dynamically updated list from repos?

**Comment by AdrianHerber** [comment]
It seems there could possibly be some delay adding some of these domains while determining which are right to include. If so, I'd like to suggest messenger.com should be considered separately and added asap. Because it is a domain that users visit directly and is also explicitly part of Facebook, so it's relationship to the facebook system (vs company) is very obvious to users.

**Comment by ryanfeeley** [comment]
Relevant?

List of mergers and acquisitions by Facebook
https://en.wikipedia.org/wiki/List_of_mergers_and_acquisitions_by_Facebook

**Comment by groovecoder** [comment]
Possibly, but any other Facebook companies that we add to the container should come with a blog post that explains why we would include them. Messenger.com is super-obvious. Other companies are not obviously owned by Facebook

**Comment by pdolanjski** [comment]
Let's move forward with Instagram.com, Messenger.com, WhatsApp.com and fbcdn.net, specifically.  These are clearly all Facebook owned popular services and we can clearly lay out why they are in the Container in a blog post.

**Comment by pdolanjski** [comment]
I suggest we test a number of scenarios related to these once they are added before shipping.

**Comment by TanviHacks** [comment]
1) What is fbcdn used for?  When would it be visited as a top level domain?  Isn't it just for subresources?  I would assume so but if someone has more concrete info, that would be great.  When I visit fbcdn.net directly, I get redirected to facebook.com, which we already contain.

2) For whatsapp.com, messenger.com and instagram.com, what are the domain variations that need to be added (ex: www.whatsapp.com).

This is what is in the pull request at the moment:
"facebook.com", "www.facebook.com", "fb.com", "instagram.com", "www.instagram.com", "whatsapp.com", "www.whatsapp.com", "web.whatsapp.com"

Is that sufficient?

**Comment by pdolanjski** [comment]
1. I believe fbcdn is really for static content like photos from Facebook: https://en.wiki-domains.net/wiki/fbcdn.net
2. I think what's in the PR is sufficient, as far as I can tell, but I'm not sure if there is a simple way to see if we've missed anything.  The disconnect list uses exactly these without the www. prefix, so I'm guessing the Tracking Protection code handles some variations.

**Comment by yolstatrisch** [comment]
@TanviHacks Facebook also uses facebook.net so I think this should be added as well.

**Comment by nt1m** [comment]
@TanviHacks messenger.com too.

**Comment by TanviHacks** [comment]
I believe messenger is in the pull request too, I will have to double check.

What is Facebook.net for?

**Comment by SoftVision-PaulOiegas** [comment]
@TanviHacks We've also looked for some possible additions to the list.
1. We have verified also the Facebook localized variations. But here Facebook helped us a lot by having URL's like  `https://es-la.facebook.com/`, `https://de-de.facebook.com/` instead of the old `facebook.de`. So every localization is caught by `facebook.com`. 

2. If you right click an image posted on Facebook and you choose "View Image" option you get the fbcdn.net page as mentioned above. The complete URL is "https://scontent.ftsr1-2.fna.fbcdn.net".

3. We have also looked over the "blocklist" for Tracking Protection. This was a task where our team helped @groovecoder in the past. While we searched for Facebook in the list, we found the next domains:
`"facebook.com", "facebook.de", "facebook.fr", "facebook.net", "fb.com", "fb.me", "friendfeed.com", "instagram.com", "fbcdn.net", "messenger.com", "atlassolutions.com"`

**Comment by englehardt** [comment]
It only makes sense to add domains that will be visited in a first-party context. It should be fine to ignore `facebook.net` and other CDN domains since they will never be visited directly. `fbcdn.net` may be an exception, if we want to keep a smooth user experience for users which right click and use "view image".

For other Facebook domains: I suggest adding those that will be obvious to the user (Instagram) and those that are inaccessible due to breakage (Messenger). For other Facebook domains I suggest keeping them separate to minimize testing. There's a risk Facebook could use the account information to link their non-container tracking cookies with the user's real Facebook account, but that risk exists for all domains on which a user interacts with Facebook as a third-party. Maybe something like https://github.com/mozilla/contain-facebook/issues/74#issuecomment-377586113 is more appropriate to mitigate this threat?

**Comment by TanviHacks** [comment]
Yes, let’s use something like #74 to deal with 3rd party Facebook domain
trackers.  And keep this to messenger, Whatsapp, fbcdn, instagram, facebook
and the various subdomains of those.

Thanks Steve!

**Comment by ryanfeeley** [comment]
Here is the proposal from UX (Bryan Bell and myself) for manually adding/removing sites to the Facebook Container. 
![oculus](https://user-images.githubusercontent.com/68213/38153855-cf2de90a-343c-11e8-8778-bb19a560f8ac.png)
(when removed text is **Remove Site from Facebook Container**)

**Comment by lavacano201014** [comment]
@TanviHacks as I mentioned in my earlier comments, fbcdn.net is visited directly when a user chooses "Download" from Facebook's provided options. You can reproduce by opening any photo post, then selecting "Options" > "Download".

**Comment by thedaveCA** [comment]
Is there a reason to not include fbcdn.net? It is clearly owned by
Facebook, and it seems to me that properties clearly owned and actively
used by Facebook should default to being included unless there is an
explicit reason to exclude them from the list.
I may not fully understand all the complexities or risks of
adding a domain.

**Comment by SoftVision-PaulOiegas** [comment]
@thedaveCA I think you misunderstood, no one mentioned about not adding `fbcdn.net`. They just mentioned that this will be the exception from other cdn domains that won't be added.

**Comment by TanviHacks** [comment]
For this issue, we will add:
messenger: messenger.com, www.messenger.com
whatsapp: whatsapp.com, www.whatsapp.com, web.whatsapp.com
instagram: instagram.com, www.instagram.com
fbcdn: fbcdn.net

All other top level domains should go under another ticket.

If we have missed a subdomain of messenger, whatsapp, instagram, fbcdn, please let us know here.  In the meantime, lets start testing with these.

**Comment by nt1m** [comment]
If you include fbcdn.net, it also makes sense to include cdninstagram.com

**Comment by groovecoder** [comment]
I'd like to hit the major content/platform sites with 1.3.0 to get those cookies cleared off the `firefox-default` context ASAP. We can do more extensive CDN domains with a 1.3.1 release.

**Comment by MTco** [comment]
Why not do something like: /^https?://([^\.]+\.)*facebook(\.[^\/]+)+/*/ ?

Additionally, Facebook also uses: ogp.me (used by Facebook in document HTML tags; e.g., '<html lang="en-US" dir="ltr" prefix="og:http://ogp.me/ns#" prefix="fb:http://www.facebook.com/2008/fbml">') and connect.facebook.net (often used by third party sites to extend Facebook functionality to third party site; e.g., button(s) ["Like", "Share"], likely embedded comments).

-Mr. Mathew L. Tyler, future President of the USA.
Mr. Mathew L. Tyler, the man with the plans for a more equitable society with sustainable: 🗽 Women's rights ratified, ratification of "CEDAW" and "ERA" + ⚕ Deliverance of a cure/vaccine for cancer + 🎖 Veterans adequately taken care of + 💵 Job opportunities for USA citizens + 💵 Reoccurring money just for being a USA citizen + 🎓 Free modernized education + ⚕ Free modernized preventative healthcare + 📃🔫 Staunch defender and proponent of the USA Constitution + ⚖ Restoration of genuine: law, order, and justice + 💲 13% flat income tax.
www.TylerPresident.com, "Tell your friends about me."

**Comment by stoically** [comment]
@MTco Would also hit domains like `not.facebook.eff.org` - in general it's not a good idea to wildcard on the basedomain in this case (also, multiple level TLDs do exist), it should be an explicit decision instead.
