### ISSUE TITLE
Add phorest.com support

### ISSUE THREAD

**Issue by tstackhouse** [mozilla/contain-facebook#455]
- Facebook Container Version: 2.0
- Operating System + Version: Windows 10 (1903/18362.175)
- Firefox Version: 67.0.4
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Cisco Webex Extension	1.4.0	true	ciscowebexstart1@cisco.com
Facebook Container	2.0	true	@contain-facebook
Feed Preview	7	true	feed-preview@code.guido-berhoerster.org
HTTPS Everywhere	2019.6.4	true	https-everywhere@eff.org
LastPass: Free Password Manager	4.29.0.4	true	support@lastpass.com
Pay by Privacy.com	1.3.19	true	privacy@privacy.com
Reddit Enhancement Suite	5.16.10	true	jid1-xUfzOsOFlzSOXg@jetpack
Redirect AMP to HTML	2.0.0	true	{569456be-2850-4f7e-b669-71e55140ee0a}
Tree Style Tab	3.1.2	true	treestyletab@piro.sakura.ne.jp
uBlock Origin	1.20.0	true	uBlock0@raymondhill.net
View Image	2.1.1	true	{287dcf75-bec6-4eec-b4f6-71948a2eea29}

### Actual behavior
Unable to use "Login with Facebook" on Phorest (https://www.phorest.com/). The login button does not have the fence icon to add an exclusion, and the page blocks the facebook SDK.  Opening the page manually in the facebook container via TreeStyleTab does not work either, and there is no way to manually allow the site.

### Expected behavior
* Fence icon is on the "Login with Facebook" button
* Clicking the "Login with Facebook" button prompts to add the site to the allowed list and reloads in the container perhaps by returning a stubbed SDK payload to hook into the extension instead of simply blocking it
* A manual method of Allowing a site access to Facebook

### Steps to reproduce
1. Visit https://essensualslondonnj.com/appointments/ (Phorest software loads in an iframe)
2. Click "My Booking History"
3. Attempt to click "Login with Facebook", button activates, but because the Facebook SDK is not loaded, nothing happens and a console error is printed.

### Notes
Console output: 
```
Loading failed for the <script> with source “https://connect.facebook.net/en_US/sdk.js”. essensualslondon:1:1
TypeError: window.FB is undefined booking-5e415284541097f7bc24366cc8f5f32a.js:10:8280
```

**Comment by maxxcrawford** [comment]
@tstackhouse Are you able to add code to Phorest? I can provide details on an ID/class name/data-attribute to add to login button to get it recognized.

**Comment by maxxcrawford** [comment]
@tstackhouse I don't see any way to effectively target the login button. It doesn't contain any separate IDs/class name's compared to the other buttons. I recommend watching this issue: #422

**Comment by tstackhouse** [comment]
@maxxcrawford I am not able to add code, no.  I am just a user on that site.  I'll watch the issue you linked.  Thanks.
