### ISSUE TITLE
This add-on can be very good and useful, but I had to disable it because it uses a lot of the alreay overcrowded URL field with at least three permenent Firefox icons, oftem more, and making ther field absolutely useless if we are using Firefox in a window (that's exactly what windos are for). Why wouldn't it work on the Overfllow Menu, like most other add-ons do? I shallk  keep it disabled, expecting that this unconvenient will be removed.

### ISSUE THREAD

**Issue by Straydog-1st** [mozilla/contain-facebook#458]
- Facebook Container Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behaviour
This add-on can be very good and useful, but I had to disable it because it uses a lot of the already overcrowded URL field with at least three permanent Firefox icons, often more, and making the field absolutely useless if we are using Firefox in a window (that's exactly what window are for).

### Expected behaviour
Why wouldn't it work on the Overflow Menu, like most other add-ons do? I shall  keep it disabled, expecting that this inconvenient will be removed.

**Comment by ronakanowicz** [comment]
Can you share a screen shot of what you're describing?

**Comment by maxxcrawford** [comment]
@Straydog-1st Closing until more information is provided. Thanks!
