### ISSUE TITLE
Suddenly opening hundreds of Facebook tabs

### ISSUE THREAD

**Issue by benji1304** [mozilla/contain-facebook#469]
Exactly the same as this issue.
https://github.com/mozilla/contain-facebook/issues/1
 facebook.com visit results in infinite loop of tabs #1 

Tabs suddenly opening extremely quickly. Have to close the browser to stop. 

Win10
Firefox 67.0.4 (64-bit)

Extension says last updated today. Can't see a version number.

**Comment by andrm** [comment]
Same here. Fedora 30,67.0.4.

**Comment by robbevp** [comment]
Same here.
FF 67.0.4 on macOS 10.14.5 running version 2.0.1 of this extension (last update 8 july 2019)

**Comment by benji1304** [comment]
Disabling the Facebook Container extension works for me, I use Containerise for other URLs.

**Comment by benji1304** [comment]
I've confirmed what someone said over on Containerise. Roll back to the previous version 3.0.1 and the issue no longer happens

**Comment by andrm** [comment]
Works again.

**Comment by maxxcrawford** [comment]
@andrm Thanks for confirming!
