### ISSUE TITLE
How do I allow localhost?

### ISSUE THREAD

**Issue by doguh** [mozilla/contain-facebook#474]
I can't find in the add-on settings, or when clicking on the fence badge a way to allow the current site (in my case localhost).

![fbcontainerbad](https://user-images.githubusercontent.com/34572689/60980443-c594c900-a334-11e9-8147-ad66fb2fe042.png)

How do I do that? Thanks.

**Comment by haydenryan** [comment]
Hi @doguh,
For the time being, until it is added in this version, you can try my fork (https://github.com/GenNextAU/better-facebook-container - download at https://addons.mozilla.org/en-US/firefox/addon/better-facebook-container/) which allows you to whitelist sites from the fence badge - go Sites Allowd in Facebook Container -> Allow [this site] in Facebook Container

**Comment by maxxcrawford** [comment]
To add any website (including `localhost`) to the Facebook Container, follow the directions [from the docs](https://github.com/mozilla/contain-facebook/blob/master/docs/container-management.md). Thanks!
