### ISSUE TITLE
Cannot login on support.logi.com

### ISSUE THREAD

**Issue by electrofloat** [mozilla/contain-facebook#477]
- Facebook Container Version: 2.0.1
- Operating System + Version: Win10
- Firefox Version: 68

### Actual behavior
Cannot login on logi's support site here:
https://id.logi.com/index.html?redirect_uri=https://logitech.zendesk.com/access/jwt&client_id=f4cbf5f1-8df3-4e7b-95dd-98e7c1f84e5e&response_type=token&locale=en-us&return_to=https://support.logi.com/hc/en-us

The login user/pass entry does not appear.

### Expected behavior

The login user/pass entry appears, and user can login.

### Steps to reproduce
1. Visit https://id.logi.com/index.html?redirect_uri=https://logitech.zendesk.com/access/jwt&client_id=f4cbf5f1-8df3-4e7b-95dd-98e7c1f84e5e&response_type=token&locale=en-us&return_to=https://support.logi.com/hc/en-us
2. When addon is enabled, observe that the user/pass entries not appearing
3. When addon disabled , observe that the user/pass entries appear, and user can login.

**Comment by haydenryan** [comment]
Hi @mydexterid 
For the time being, until it is added in this version, you can try my fork (https://github.com/GenNextAU/better-facebook-container - download at https://addons.mozilla.org/en-US/firefox/addon/better-facebook-container/) which allows you to whitelist sites from the fence badge - go Sites Allowed in Facebook Container -> Allow [this site] in Facebook Container

**Comment by maxxcrawford** [comment]
@haydenryan Feel free to open a PR to contribute to this project!

**Comment by electrofloat** [comment]
@maxxcrawford So you released an update without fixing this issue. Nice.

Mozilla.. you are a piece of cr*p.

**Comment by maxxcrawford** [comment]
@electrofloat Flagging this comment as it goes against Mozilla's [code of conduct](https://www.mozilla.org/about/governance/policies/participation/), which [this repository](https://github.com/mozilla/contain-facebook/blob/master/CODE_OF_CONDUCT.md) follows. This is a warning – any further comments of this nature will not be tolerated and you will be blocked from contributing to this repository. 

/cc @groovecoder

**Comment by electrofloat** [comment]
@maxxcrawford yeah you do that! you guys are best at that exactly

**Comment by maxxcrawford** [comment]
To fix this, add this website to the Facebook Container. Follow the directions [from the docs](https://github.com/mozilla/contain-facebook/blob/master/docs/container-management.md).
