### ISSUE TITLE
Angry Birds (Flash) game will not load in Facebook

### ISSUE THREAD

**Issue by techionltd** [mozilla/contain-facebook#480]
- Facebook Container Version: 2.0.1
- Operating System + Version: Mac OS 10.14.5
- Firefox Version: 67.0.4
- Other installed Add-ons 
Awesome Screenshot - Capture, Annotate & More	3.0.24	true	jid0-GXjLLfbCoAx0LcltEdFrEkQdQPI@jetpack
Bitwarden - Free Password Manager	1.40.1	true	{446900e4-71c2-419f-a6a7-df9c091e268b}
ColorZilla	3.3	true	{6AC85730-7D0F-4de0-B3FA-21142DD85326}
Email Tracking for Gmail - Mailtrack	6.13.1	true	mailtrack-extension-v4@mailtrack.io
Emoji Keyboard - Emojis For Firefox	4.2.4	true	@emojikeyboard
Enhancer for YouTube™	2.0.93	true	enhancerforyoutube@maximerf.addons.mozilla.org
Facebook Container	2.0.1	true	@contain-facebook
Font Finder	0.3.3	true	{a658a273-612e-489e-b4f1-5344e672f4f5}
FVD Speed Dial	71.1.1	true	pavel.sherbakov@gmail.com
Grammar and Spell Checker - LanguageTool	2.2.1	true	languagetool-webextension@languagetool.org
Honey	11.3.5	true	jid1-93CWPmRbVPjRQA@jetpack
I don't care about cookies	3.0.2	true	jid1-KKzOGWgsW3Ao4Q@jetpack
IBM Security Rapport	2.1.24	true	rapportext@trusteer.com
Kassi - Kodi/XBMC Remote	2.3.5	true	jid1-xjowF7M9FfgMVQ@jetpack
Merge Windows	1.0.2	true	{6d0b1446-4a7c-40e9-9bcf-568a8e26d00b}
MySessions	2.13.5	true	balyaev@gmail.com
OneNote Web Clipper	3.8.0	true	Clipper@OneNote.com
Play to Kodi	1.9.1	true	{ba707b6e-571d-47c9-a31d-7b94807d6ee2}
Rename Tab Title	1.2	true	renametabtitle@mozilla.org
Search by Image	1.21.1	true	{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}
Tab Auto Refresh	0.1.6	true	{7fee47a1-8299-4576-90bf-5fd88d756926}
Translate Now	4.0.1	true	@translatenow
uBlock Origin	1.20.2	true	uBlock0@raymondhill.net
Image Block X	0.5	false	{0035bf10-3f36-4d60-b92d-08c1a8b060a6}
Pouch - Instant UK Voucher Codes	7.0.27	false	{7c9aa7cd-0b7a-4618-a6c5-42b0ad013d16}
Spoiler Protection 2.0	2.6.0	false	spoilerprotection@wecdev.com

### Actual behavior
When trying to play Angry Birds, the flash game panel does not load and remains blank (white)

### Expected behavior
Angry Birds game will load normally as it does with the extension disabled.

### Steps to reproduce
1. Go to Facebook
2. Open Angry Birds game app in Facebook
https://apps.facebook.com/angrybirds/?fb_source=bookmark&ref=bookmarks&count=0&fb_bmpos=_0

**Comment by mbroo** [comment]
Many other games don't load with this enabled (eg. Words with Friends, Uno, etc)

**Comment by maxxcrawford** [comment]
I found the fix. You'll need to add the AppSpot website (https://angrybirds-facebook.appspot.com) to the Facebook Container. Follow the directions [from the docs](https://github.com/mozilla/contain-facebook/blob/master/docs/container-management.md). 

@mbroo You're correct. By default, this extension blocks non-Facebook/external scripts from loading while inside the Facebook Container.
