### ISSUE TITLE
Addon is blocking ordinary FB link, but should not

### ISSUE THREAD

**Issue by michal-minich** [mozilla/contain-facebook#483]
- Facebook Container Version:  2.0.1
- Firefox Version: 68

### Actual behavior
Addon is blocking simple, ordinary, FB link

### Expected behavior
No-action from addon

### Steps to reproduce
1. See any item on site, for example https://foto.bazos.sk/inzerat/100092763/Canon-EOS-M6.php
2. Link text is "Zdieľajte na Facebooku" (translated: Share on Facebook)

**Comment by maxxcrawford** [comment]
This is the expected behavior. This add-on badges any sharing URL with the following pattern, `"[href*='facebook.com/sharer']"`.

**Comment by maxxcrawford** [comment]
We do have a related issue, #430, reagrding SDK-assisted sharing links, versus anchor-link only sharing.

**Comment by michal-minich** [comment]
As an user, now I think marking a ordinary FB link can be useful. This time
it is very clear for user that the link goes to FB - it contains text
"Share on Facebook" (and has simple FB icon). But often there are link with
text which makes it unclear it goes to FB. In that case it is useful to
mark it.

Still I would suggest different kind of icon mark for blocked content, VS
just an adding marking label for ordinary link.

**Comment by maxxcrawford** [comment]
@michal-minich Copy that. I'm adding your notes to that other related issue. Thanks!
