### ISSUE TITLE
Add whatsapp web to facebook container

### ISSUE THREAD

**Issue by Ailin-Lyons** [mozilla/contain-facebook#486]
I noticed that whatsapp web is not included in the facebook container plugin. Since this is yet another company owned by facebook I feel it would make sense to add.

**Comment by maxxcrawford** [comment]
WhatsApp was added to a previous iteration. However, during testing, it had too many functionality bugs related to it [and was removed](https://github.com/mozilla/contain-facebook/pull/109). 

cc: @groovecoder @TanviHacks @arthur-mozilla

**Comment by rolandog** [comment]
I noticed the following list of domains when checking network requests on Firefox:

* `web.whatsapp.com`
* `mmg.whatsapp.net`
* `media*.giphy.com` (`media0`, `media1`, `media2`)
* `api.giphy.com`

Can adding them be enough to properly contain them as well?

**Comment by revi** [comment]
I thought [giphy](https://en.wikipedia.org/wiki/Giphy) is not a Facebook subsidiary?

**Comment by rolandog** [comment]
Oh, you're totally right, my bad. I just enumerated the domains I saw, but didn't filter them on an owned-by-facebook basis.

**Comment by maxxcrawford** [comment]
Will be considered/covered in #558

**Comment by icorne** [comment]
I had to add web.whatsapp.com to the container otherwise I'd get the following error:
TypeError: t.getHighEntropyValues is not a function
