### ISSUE TITLE
Facebook Suspecting My Account of Spamming

### ISSUE THREAD

**Issue by Lanthanariel** [mozilla/contain-facebook#490]
- Facebook Container Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
Very recently (two days before I reported this issue), Facebook suddenly suspects my account as some kind of spammer or has been taken over by a different entity. It gives me a couple of Captchas, asks me to upload my photo (and rejects a lot of them), then locks my account for a bunch of hours. After the first incidence, I log in, and again it does the same. To experiment, I removed Facebook Container from my Firefox and when I was allowed back into Facebook again, no more issues. Coincidence?

### Expected behavior
See above.

### Steps to reproduce
1. Install Facebook Container
2 Log into Facebook
3. ???
4. No Profit!

### Notes
Please investigate, as I don't think this happens to everyone using your app. Still, it might be worth finding out. For now, I won't use your app as I kinda use FB to talk with my friends and family, or until they lock me out again which means FB Container doesn't have anything to do with it. Take care!

**Comment by maxxcrawford** [comment]
@Lanthanariel Closing this issue for now, as it seems specific to your account. Please let us know if anything has changed!
