### ISSUE TITLE
no icon in containers listing

### ISSUE THREAD

**Issue by TriMoon** [mozilla/contain-facebook#491]
- Facebook Container Version: **2.0.1**
- Operating System + Version: **Linux (Kubuntu 19.04)**
- Firefox Version: **Nightly**
  - **Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0 ID:20190729213839**
- Other installed Add-ons + Version + Enabled/Disabled-Status:
```console
Amazon.com 1.1
Awesome RSS 1.3.5
Bing 1.0
CanvasBlocker 0.5.13 [DISABLED]
Certainly Something (Certificate Viewer) 1.2.3
Compat Report 0.1.0
Containers theme 1.0.3
Context Plus 0.6.0
Debian queries 2.3
Decentraleyes 2.0.12
Disconnect 5.19.3 [DISABLED]
DuckDuckGo 1.0
DuckDuckGo Privacy Essentials 2019.7.19 [DISABLED]
Emoji Cheatsheet for GitHub, Basecamp etc. 2.0.1
Enhancer for YouTube™ 2.0.93
Enterprise Policy Generator 4.4.0 [DISABLED]
Facebook Container 2.0.1
Feedbro 3.42.8
Firefox Lightbeam 2.1.0
Firefox Multi-Account Containers 6.1.0
FoxyProxy Standard 6.6.2
Google 1.0
Greasemonkey 4.9
HTTP/2 Indicator 3.0
IPFS Companion 2.8.3 [DISABLED]
Laboratory 3.0.5 [DISABLED]
MathML Font Settings 0.3.2 [DISABLED]
Native MathML 1.9.4 [DISABLED]
Nightly Tester Tools 4.0
Notes by Firefox 4.3.5 [DISABLED]
Offline QR Code Generator 1.6
PassFF 1.9 [DISABLED]
Plasma Integration 1.5
React Developer Tools 3.6.0 [DISABLED]
Session Sync 3.1.12
Snooze Tabs 1.1.1
Tab Session Manager 4.5.2 [DISABLED]
To Google Translate 3.10
Tree Style Tab 3.1.5
True Sight 1.7.1
Twitter 1.0
Vue.js devtools 5.1.1
Wikipedia (en) 1.0
YouTube Container 1.3.0
eBay 1.0
uMatrix 1.3.16
```

### Actual behavior
When you click the container tabs icon, the Facebook container is listed but has **NOTHING** in front of it.

### Expected behavior
It should have an icon or at least a color circle.

### Steps to reproduce
1. Fresh profile
2. Install this extension
3. Click the container tabs icon.

### Notes
Best would be the ![FB-Icon](https://static.xx.fbcdn.net/rsrc.php/yo/r/iRmz9lCMBD2.ico?_nc_x=Ij3Wp8lg5Kz) icon. :wink: 
Maybe something broke during the efforts of #205 ?

**Comment by dnahol** [comment]
I see this. I'll take a look. 
### Screenshots for reference 
<img width="309" alt="Screen Shot 2019-11-03 at 1 18 33 AM" src="https://user-images.githubusercontent.com/2976514/68082319-53ab2880-fdd8-11e9-8b1d-9e508dfcf421.png">

### Note: icon does show up when hovering over it
<img width="302" alt="Screen Shot 2019-11-03 at 1 18 52 AM" src="https://user-images.githubusercontent.com/2976514/68082313-3a09e100-fdd8-11e9-8e1a-ab0c83b2449c.png">

**Comment by TriMoon** [comment]
The default icons are of little use when users use many containers...
Maybe add a functionality to assign custom icons?
You could add those to the config using data uri's that convert the selected file into base64 :wink:
