### ISSUE TITLE
Alternative Approach

### ISSUE THREAD

**Issue by Lewiscowles1986** [mozilla/contain-facebook#50]
How about blocking all cookies for all domains until they are whitelisted? I Always felt the browser should be the place to implement things like EU cookie legislation anyway and it seems all this does is block requests and cookies.

**Comment by Perflyst** [comment]
You can do this with [uMatrix](https://addons.mozilla.org/en-US/firefox/addon/umatrix/).
Go to the rules tab and add `* * cookie block`. It also blocks scripts and other stuff which can track you until you whitelist them.
