### ISSUE TITLE
Facebook Workplace not managed

### ISSUE THREAD

**Issue by HugoGresse** [mozilla/contain-facebook#501]
- Facebook Container Version:2.0.1
- Operating System + Version: MacOS 10.14.5
- Firefox Version: 69.0b14
- Other installed Add-ons + Version + Enabled/Disabled-Status: AdBlockPlus,bitwarden

### Actual behavior
When reaching my company Facebook workplace (teads.workplace.com) from any link going directly to a post inside, I'm redirected to https://teads.workplace.com/work/landing/input/ which is the login page. 
When using Google SSO to login, I'm redirected to https://teads.workplace.com/work/saml.php. 
From the moment I enable the Facebook Container while a given workplace page is open, Facebook logged me out and I'm redirected to the login page. 

### Expected behavior
*.workplace.com allow me to login to check the post

### Steps to reproduce
Well, I cannot disclose my company credentials... 

### Notes
When I disable the Facebook Container, I'm allowed to login as expected without any issue. 
I've seen https://github.com/mozilla/contain-facebook/pull/459 but I'm already on 2.0.1 :/

**Comment by robpearman** [comment]
Same issue for me, using Facebook Container 2.0.2 with a different SSO / SAML solution, Windows 10, Firefox 68.0.2.

I can see when clicking the 'log in' button on the 'log in' button on https://dxc.workplace.com/work/landing/input/ that the tab changes from the Facebook container to the Default container and assume this is the cause of the problem, cookies stored are then not accessible when redirected back in the Facebook container?

**Comment by eddideku** [comment]
Unfortunately, to get around this I have to disable the plugin. With Firefox account/sync it disables the extensions on all my browsers (ie work laptop, desktop workstation, etc etc). I may be relaxing in the evening surfing the internet and not realize the extension is disabled on my personal PC.

**Comment by Acid-Crash** [comment]
Same here.
It is a bit sad because this issue has been here for some time now.
https://github.com/mozilla/contain-facebook/issues/70

**Comment by elygre** [comment]
Now that workplace is migration to it's own domain (e.g. company.workplace.com instead of company.facebook.com), it would be nice with an option to specify that pages from workplace.com should run outside the container.

**Comment by Acid-Crash** [comment]
After the mentioned migration I still experience the same issues with login. Basically because during that process there is a brief redirect to facebook domain and back to the actual workplace domain.
Not sure if this is the same for everyone.

**Comment by eddideku** [comment]
Hello,

Just checking back on this, still an issue. @Acid-Crash looks like #70 was closed. I personally think this should be a story of its own and not associated with #422

**Comment by chrisaga** [comment]
Bug is still there with Facebook Container 2.1.1
Very annoying :-(

**Comment by maxxcrawford** [comment]
@chrisaga Have you added your custom workplace to the Facebook container through the panel? I created a test workplace account and was able to login/navigate around without issue. I'll create a sample post and try to see if the redirects work.

**Comment by maxxcrawford** [comment]
Confirmed: I was able to go directly to a post without being logged out/redirected. All subdomains from workplace.com are also added to the Facebook Container by default. 

@HugoGresse – We added support for Google, but you have to add it to the Facebook Container to link SSO with a Facebook service. Simply navigate to any *.google.com site and add it to the container via the doorhanger panel.

**Comment by Acid-Crash** [comment]
@maxxcrawford 
The issue described earlier is still here.
https://github.com/mozilla/contain-facebook/issues/501#issuecomment-562215910


![изображение](https://user-images.githubusercontent.com/32600318/79592710-08b17300-80e3-11ea-9e3d-562af1eec150.png)

I am neither able to login nor add URL to Facebook container (due to redirect).

**Comment by maxxcrawford** [comment]
@Acid-Crash Are all the domains in question INSIDE the Facebook Container? As long as all necessary domains are inside the container, there should not be any redirect/non-auth breaks.

**Comment by Acid-Crash** [comment]
@maxxcrawford 
Here is the demo.
![URL](https://user-images.githubusercontent.com/32600318/79595549-b9217600-80e7-11ea-8460-6904cf93f1af.gif)


Here are redirect pattern.
company.workplace.com > sts.company > company.faceboock.com > company.workplace.com

Seems like sts.company is not in FB container.
Tried to add sts.company to FB container. It led to adding whole company to FB container.
Not like I'm happy with adding whole company to FB container.

Still I doubt that I want to add whole sts.company for Work in FB container...

**Comment by chrisaga** [comment]
> @chrisaga Have you added your custom workplace to the Facebook container through the panel? [...]
@maxxcrawford : I tried again and it worked ! thanks a lot ! I guess I missed something the first time.
This time, I just had to add my company login page to the container and it worked.

**Comment by maxxcrawford** [comment]
Awesome. Glad it's working for you!

**Comment by maxxcrawford** [comment]
> > @chrisaga Have you added your custom workplace to the Facebook container through the panel? [...]
> @maxxcrawford : I tried again and it worked ! thanks a lot ! I guess I missed something the first time.
> This time, I just had to add my company login page to the container and it worked.

Awesome. Glad it's working for you!

**Comment by maxxcrawford** [comment]
> @maxxcrawford 
> Here is the demo.
> ![URL](https://user-images.githubusercontent.com/32600318/79595549-b9217600-80e7-11ea-8460-6904cf93f1af.gif)
> 
> 
> Here are redirect pattern.
> company.workplace.com > sts.company > company.faceboock.com > company.workplace.com
> 
> Seems like sts.company is not in FB container.
> Tried to add sts.company to FB container. It led to adding whole company to FB container.
> Not like I'm happy with adding whole company to FB container.
> 
> Still I doubt that I want to add whole sts.company for Work in FB container...
> 

Yeah. Unfortunately, it looks like adding the company URL to the container is the only way to get it to share authorization between the two systems.

**Comment by maxxcrawford** [comment]
This looks resolved as of now. Thanks!
