### ISSUE TITLE
Facebook launches two tabs every time it is entered in address bar

### ISSUE THREAD

**Issue by JJDLA** [mozilla/contain-facebook#509]
- Facebook Container Version: 2.0.2
- Operating System + Version: Mac 10.14.6
- Firefox Version: 69.0b15 
- Other installed Add-ons + Version + Enabled/Disabled-Status:

Adblock Plus - free ad blocker	3.6.3	true	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
Amazon.com	1.1	true	amazondotcom@search.mozilla.org
auto-reader-view	1.0.2	true	@auto-reader-view
AutoPagerize Advanced	0.0.2.1	true	@autopagerizetweaked
Bing	1.0	true	bing@search.mozilla.org
Browsec VPN - Free and Unlimited VPN	3.24.0	true	browsec@browsec.com
Copy On Select	1.0	true	copy-on-select@spyrosoft.com
Disconnect	5.19.3	true	2.0@disconnect.me
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
Facebook Container	2.0.2	true	@contain-facebook
Google	1.0	true	google@search.mozilla.org
LastPass: Free Password Manager	4.31.2.3	true	support@lastpass.com
Livemarks	2.2	true	{c5867acc-54c9-4074-9574-04d8818d53e8}
Load Progress Bar	0.19	true	load-progress-bar@luben.github.com
Multi-Tab Close	0.5.3	true	multitabx@j70.user.github.com
New Tab from Location Bar	3.1.1	true	newtabfromlocationbar@piro.sakura.ne.jp
Open Link with New Tab	1.0	true	Open-Link-with-New-Tab@sienori
ShowPassword	1.1.5	true	bbiclfnbhommljbjcoelobnnnibemabl@chrome-store-foxified-3264527518
Side View	0.4.6423	true	side-view@mozilla.org
Simple YouTube to MP3/MP4 Converter	5.0.0	true	jid0-SQnwtgW1b8BsMB5PLV5WScEDWOjw@jetpack
Snatp Back Button	1.5	true	snap-back-single@codefisher.org
Tab Close Button	1.4	true	{ab300b16-85cb-4380-bdb8-fa96903f2b3c}
Tab Session Manager	4.5.2	true	Tab-Session-Manager@sienori
Twitter	1.0	true	twitter@search.mozilla.org
Undo Close Tab	4.6.1	true	{4853d046-c5a3-436b-bc36-220fd935ee1d}
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org
404 Bookmarks	1.7	false	{5f8d31ba-47fb-4b70-bf8d-d2113f6da22f}
Auto Copy	4.0.0	false	bijpdibkloghppkbmhcklkogpjaenfkg@chrome-store-foxified-1965445564
AutoFill Forms	0.3.2	false	jid1-jJjr0f2lg5yYtf2dD@jetpack
AutoPagerize	0.3.9	false	jid0-tKjnEA5X3eBoP5HnqjBYQ4U3AcM@jetpack
Chrome Store Foxified	3.4	false	Chrome-Store-Foxified@jetpack
Open in Reader View	0.2.1	false	jid0-fgmjSq5kJtop0oO9u5hJj@jetpack
RSS Feed Reader	7.6.6	false	{73239762-0d26-4b2e-82a5-49bfd13457f0}
Show me the password!	2.1.1	false	showmethepassword@alejandrobrizuela.com.ar
Tab Mix - Links	0.1.0	false	webext@tabmixplus.org
Turn Off the Lights for YouTube™	4.0.41.0	false	stefanvandamme@stefanvd.net
uAutoPagerize	0.1.4.1	false	@uautopagerize
ZButton+: Undo Close Tab	1.1.1	false	undoCloseTab@zbutton.ru

### Actual behavior
When launching Facebook two tabs open each time and overwrite existing tabs

### Expected behavior
Single, new tab

### Steps to reproduce
1.Select FB from bookmarks or enter FB
2.Disabling Container cures this issue   
3.

**Comment by forteller** [comment]
I have this same issue. Hard to recommend people use this extension with bugs like this. Hope someone can look into it soon!

Otherwise I'm really grateful for this extension! :)

**Comment by maxxcrawford** [comment]
Is this still reproducible on the latest version of the add-on (2.1.1) and Firefox (77.0.1)?

**Comment by forteller** [comment]
No, it seems to have been fixed. Works for me, at least. Thanks! Fx 78.0.1 is the latest, btw.
