### ISSUE TITLE
Add Komoot FB Login Support

### ISSUE THREAD

**Issue by belegdol** [mozilla/contain-facebook#514]
- Facebook Container Version: 2.0.2
- Operating System + Version: Fedora 30
- Firefox Version: 69
- Other installed Add-ons + Version + Enabled/Disabled-Status:

Nazwa | Wersja | Włączone
----------|-------------|----------
Adblock Plus - darmowy adblocker | 3.6.3 | true
Allegro | 1.0 | true
DuckDuckGo | 1.0 | true
Encyklopedia PWN | 1.0 | true
Facebook Container | 2.0.2 | true
Google | 1.0 | true
Integracja z GNOME Shell | 10.1 | true
Kee - Password Manager | 3.2.7 | true
Livemarks | 2.2 | true
TunnelBear VPN | 3.2.4 | true
Wikipedia (pl) | 1.0 | true
Wolne Lektury | 1.0 | true

### Actual behavior
Progress spinner on facebook login button keeps spinning

### Expected behavior
Log in into komoot

### Steps to reproduce
1. Register on komoot.com or komoot.de with facebook
2. install facebook container
3. try to log in

### Notes
I noticed that the container allows e.g. spotify to be added to a whitelist and logging in with facebook works there despite the extension being installed and enabled.

**Comment by sudofox** [comment]
In the README.md:

https://github.com/mozilla/contain-facebook/blob/master/README.md#logging-in-or-creating-accounts-on-other-websites-using-facebook

>_Websites that allow you to create an account or log in using Facebook will generally not work properly._

**Comment by belegdol** [comment]
I understand, but if an exception for Spotify is possible then why one for komoot would not be?

**Comment by maxxcrawford** [comment]
@belegdol @sudofox While #422 stays unresolved, we want to accommodate specific site support where we can!

**Comment by belegdol** [comment]
It unfortunately appears that komoot have redesigned their website and the container no longer allows to add an exception.
