### ISSUE TITLE
why not remove instagram and messenger also?

### ISSUE THREAD

**Issue by vsrawat** [mozilla/contain-facebook#515]
I installed the extension today and found that you are allowing instagram and messenger as a default, that is not even showing anywhere in option, nor allowing us to remove or delete them.

Why so? What is so sacred about these two?

I am on PC and I don't use instagram, I don't know what messenger you are talking about there.

I don't want these two be allowed in fb container.

Why are you keeping them?

Thanks.

**Comment by subsr97** [comment]
Messenger and Instagram are owned by Facebook.
If you want to allow these sites to be opened outside of the container, you might as well disable the extension.

**Comment by vsrawat** [comment]
How does ownership of sites affect the working of an extenstion? These are different independent urls and if the extensin had not added permission for them a default, or allowed us to remove these permissions, then should the extension in its normal working, blocked translfer of data between three sites?

Why is extension facilitating fb to be owner of other sites?

Thanks?

**Comment by maxxcrawford** [comment]
@vsrawat This is as intended. [Data sharing](https://help.instagram.com/833836199971426) exists (and [continue to grow](https://globalnews.ca/news/4892985/facebook-messenger-whatsapp-instagram-data-sharing/)) between the multiple Facebook-owned sites. We list those three sites as been permanently added the Facebook container, but we target [additional related domains](https://github.com/mozilla/contain-facebook/blob/master/src/background.js#L7-L23). Thanks!

**Comment by vsrawat** [comment]
No sirs, this is ethically wrong.

If fb had bypassed your add-on code and has still communicated with instagram and messenger tabs and sites, even with your add-on installed, active and the two said sites blocked by your add-on, we can't do anything.l

But when you are yourself allowing those two sites, where can we fault with fb. 

I am finding faults with you that you are acting like a paid hacker on behalf of fb that you have allowed their two sister sites
- without telling the users anywhere that you are allowing them.
- without letting users remove that permission of two sites.

That is what is ethically wrong. 

Please give a thought to it, discuss it with your friends and guides whom you think sound ethical advice, and decide whether your decision to act like a stooge of fb is right or wrong.

I have removed your add-on on this basis.

I am sorry if my observation hurt you.

Thanks.
