### ISSUE TITLE
Add Freelancer.com FB Login Support

### ISSUE THREAD

**Issue by tcinotto** [mozilla/contain-facebook#518]
- Facebook Container Version: 2.0.2
- Operating System + Version: mac os 10.14.5
- Firefox Version: 70 nightly & 69 release 
- Other installed Add-ons + Version + Enabled/Disabled-Status: 

### Actual behavior
when i try to click sign in with facebook on freelancer.com nothing happens 

### Expected behavior
when i try to click sign in with facebook on freelancer.com I should be able to sign in through facebook

**Comment by sudofox** [comment]
In the README.md:

https://github.com/mozilla/contain-facebook/blob/master/README.md#logging-in-or-creating-accounts-on-other-websites-using-facebook

>_Websites that allow you to create an account or log in using Facebook will generally not work properly._
