### ISSUE TITLE
Facebook Container Inhibits Comments on Some Web Sites

### ISSUE THREAD

**Issue by TiresOfItAll** [mozilla/contain-facebook#523]
When FB Container is installed the comments facility on TheNewDaily.com.au does not work.  Uninstalling FB Container and all is well.  It has been thus since I installed FB container but just confirmed the link between the comments fail and the extension.   Firefox 69.0.3 and FB Container 2.0.3.

**Comment by maxxcrawford** [comment]
This is expected behavior. All Facebook plugins, including [Comments](https://developers.facebook.com/docs/plugins/comments/) are blocked with this plugin.
