### ISSUE TITLE
How to remove a site from the Facebook list

### ISSUE THREAD

**Issue by ukch** [mozilla/contain-facebook#528]
To reproduce:
* Go to a site that has a FB login button (e.g. meetup.com)
* Click the Facebook login button
* Confirm that you do want this site to be added to the FB container
* Change your mind

At this stage, it seems that the site is in some custom list of 'always open this site in the FB container' with no option to remove it again. Is this correct? Please can you add some way of editing this list.

**Comment by maxxcrawford** [comment]
Follow these steps to remove an added site to the Facebook Container: 

1. Navigate to site that is outside of the Facebook Container 
1. Add site to the container from a login dialog box:
![image](https://user-images.githubusercontent.com/2692333/68231727-35ece780-ffc1-11e9-933e-6e0e01ed028a.png)

1. Reload/refresh the page. It should now be inside the Facebook Container 
![image](https://user-images.githubusercontent.com/2692333/68231785-59179700-ffc1-11e9-9661-d3802869e965.png)

1. Click Facebook doorhanger/panel and select "Sites allowed in Facebook Container"
![image](https://user-images.githubusercontent.com/2692333/68231873-88c69f00-ffc1-11e9-9994-d93e5fbf6de1.png)

1. From the list of sites allowed, click the "X" to remove it. 
![image](https://user-images.githubusercontent.com/2692333/68231886-8f551680-ffc1-11e9-8663-97aecb0534b3.png)

Please reopen this issue if this does not work for you!
