### ISSUE TITLE
kommoot fb login is broken again

### ISSUE THREAD

**Issue by belegdol** [mozilla/contain-facebook#532]
It unfortunately appears that komoot have redesigned their website and the container no longer allows to add an exception.

_Originally posted by @belegdol in https://github.com/mozilla/contain-facebook/issues/514#issuecomment-541914542_

**Comment by maxxcrawford** [comment]
You cann add this website to the Facebook Container. Follow the directions [from the docs](https://github.com/mozilla/contain-facebook/blob/master/docs/container-management.md). Thanks!
