### ISSUE TITLE
Difference to Track-The-Tracker / block all 3rd-party trackers

### ISSUE THREAD

**Issue by fbruetting** [mozilla/contain-facebook#540]
With the new tracker blocking settings of Firefox, is there still a need for this extension? I would assume that the setting to block all 3rd-party trackers would block all FB trackers/cookies/etc. on other sites and so would fulfill the same purpose as this extension. As I’m not really sure if I interpret that correct and because I couldn’t find any further information on that, it would be nice if you could add this topic to the README and the extension description! :)

**Comment by maxxcrawford** [comment]
It is – this add-on still blocks the Facebook SDK and other Facebook assists beyond third-party cookies. Thanks!
