### ISSUE TITLE
Can't log into Messenger, Facebook doesn't load properly

### ISSUE THREAD

**Issue by apizzimenti** [mozilla/contain-facebook#548]
- Facebook Container Version: 2.0.3
- Operating System + Version: macOS Catalina 10.15.1
- Firefox Version: 70.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status: Bitly, Dark Reader, Ghostery, Greasemonkey, Honey, minerBlock, RES, Stack Search, uBlock Origin, Zotero Connector (all enabled, all most recent versions)

### Actual behavior
When attempting to log into Facebook Messenger (www.messenger.com/login) in the browser, the page loads properly, but the login input elements do not. Everything else loads properly (images, buttons, navigation, etc.), but I can't input my login credentials.

When I attempt to load facebook (www.facebook.com), I am logged into facebook, but *only the navbar loads*, nothing else. I can see how many messages or notifications I have, but I can't access them, nor can I navigate to anywhere else on the site; it's just a blue navbar and nothing else.

Furthermore, when I turn off the tab container addon, I'm able to log into and use Messenger and Facebook as normal.

### Expected behavior
As I've used the facebook container in the past, I've been able to use both Messenger and Facebook proper without a hitch. Pages load properly in the tab container, and I'm able to use the sites as normal.

### Steps to reproduce
1. Install newest versions of Firefox and Tab Container
2. ????
3. Be unable to load Messenger and Facebook.

### Notes
I **love** this addon; so much so that I'm not going to use Facebook or Messenger on my computer until we fix the problem. Keep up the great work!

**Comment by vwbusguy** [comment]
I see this as well on Fedora 31 with Firefox 71.0.  If I disable this extension, then facebook loads normally.  With it enabled, it now only shows the navbar and nothing below after logging in.

**Comment by maxxcrawford** [comment]
@vwbusguy @apizzimenti Question: When loading http://www.messenger.com/login — does it open in the Facebook container or a separate/different container? I'm having trouble reproducing this.

**Comment by apizzimenti** [comment]
It opens in a Facebook container tab – here's what gets displayed:

![blank messenger login page](https://user-images.githubusercontent.com/9503402/71050771-bd269280-210b-11ea-8bdd-eb592b4fd7df.png)

I'm fairly certain that it's not an issue with Firefox's cache, as I clear it regularly (and before each time I test this). I've also disabled all my other extensions to see if it's some weird interoperability issue, but that doesn't seem to be the case either.

**Comment by maxxcrawford** [comment]
@apizzimenti Interesting. I'm testing on the [release version of this addon](https://github.com/mozilla/contain-facebook/releases/tag/2.0.3) with a fresh profile in Fx71 and get this: 

![image](https://user-images.githubusercontent.com/2692333/71107650-1d0e4f00-2187-11ea-9cfe-2c698080dc2e.png)

Can you open up dev tools and tell me what resources are being blocked on the network tab? If all is going normal, you shouldn't have anything blocked. Additionally, what are your [ETP](https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop?as=u&utm_source=inproduct) settings?

**Comment by apizzimenti** [comment]
My ETP is set to strict, and it doesn't look like there are any *network* requests being blocked. However, *only when the Facebook container tab is enabled*, an error gets thrown from some javascript file, but there's no error message. Here's the stacktrace:

![](https://user-images.githubusercontent.com/9503402/71134204-efdf9200-21c2-11ea-9e33-e2b413f6511d.png)

I'm guessing this won't be particularly helpful, but this is the only thing that's different between when the Container is enabled versus disabled.

**Comment by owalerys** [comment]
I'm getting the same error as well.

<img width="1855" alt="image" src="https://user-images.githubusercontent.com/8883074/71326213-c4f88500-24c5-11ea-8688-b190c2c12ce5.png">

<img width="753" alt="image" src="https://user-images.githubusercontent.com/8883074/71326216-cf1a8380-24c5-11ea-9914-21421ce945b1.png">

On some hard refreshes, it would actually work. But otherwise, looking in the network tab, there are no blocked requests.

**Comment by owalerys** [comment]
Previously I was getting an `NS_ERROR_FILE_CORRUPTED` in the console.

**Comment by maxxcrawford** [comment]
Is this still reproducible on the latest version of the add-on (2.1.1) and Firefox (77.0.1)?

**Comment by apizzimenti** [comment]
I cannot reproduce it.

**Comment by maxxcrawford** [comment]
Thanks, @apizzimenti! Closing for now.

**Comment by vwbusguy** [comment]
I know this is closed, but https://github.com/mozilla/contain-facebook/issues/548#issuecomment-568295367 was my clue.  Clearing out the corrupted webappsstore.sqlite got it working again for me.  I don't think I was seeing a bug specific to this plugin as much as a general Firefox issue.
