### ISSUE TITLE
Workplace.com

### ISSUE THREAD

**Issue by Greg-Gill** [mozilla/contain-facebook#549]
Suggestion:
Should you maybe include workplace.com as a default Facebook site? It used to be <company>.facebook.com but is now <company>.workplace.com and so might be missed by Facebook container. Thanks for your great work! Much appreciated!

**Comment by maxxcrawford** [comment]
@Greg-Gill It is already is [a default URL](https://github.com/mozilla/contain-facebook/blob/master/src/background.js#L19) for the Facebook Container. However, there's an [open issue](https://github.com/mozilla/contain-facebook/issues/501) for subdomains of workplace.com that make it difficult to use. This is something we're working on. Thanks!

**Comment by maxxcrawford** [comment]
Related issue to #70, #501
