### ISSUE TITLE
Broken facebook site: https://mapwith.ai

### ISSUE THREAD

**Issue by Chaz6** [mozilla/contain-facebook#551]
The facebook domain https://mapwith.ai requires access to www.facebook.com/maps/ml_roads (see also https://github.com/facebookincubator/RapiD/issues/5#issuecomment-515234717).

**Comment by maxxcrawford** [comment]
You'll need to add this website to the Facebook Container. Follow the directions [from the docs](https://github.com/mozilla/contain-facebook/blob/master/docs/container-management.md). Please reopen this if adding the site doesn't get your issue resolved. Thanks!

**Comment by Chaz6** [comment]
This is a Facebook site, and should be included with the extension.

**Comment by maxxcrawford** [comment]
Ahh  – My bad. I read this issue as being broken. Re-opening, and re-labeling. Thanks!

**Comment by Chaz6** [comment]
Thanks! More info - https://github.com/facebookmicrosites/Open-Mapping-At-Facebook/wiki/FAQ
