### ISSUE TITLE
Extension recommended even though Containers global extension installed

### ISSUE THREAD

**Issue by Windyo** [mozilla/contain-facebook#554]
# Actual behavior
When navigating to Facebook, Firefox prompts to install Facebook Container

### Expected behavior
Firefox should detect that Facebook is running within a container from the Containers extension and not prompt to install.

### Steps to reproduce
1. Install Containers extension
2. Go to Facebook.

**Comment by groovecoder** [comment]
To clarify - are you already running with Facebook Container extension? Or with Multi-Account Containers?

**Comment by Windyo** [comment]
The global mutli-account container, which I cofigures a Facebook container for.
________________________________

**Comment by groovecoder** [comment]
Ah, this should be a request to the Firefox Messaging System component in bugzilla. Please copy/file it here:

https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Messaging%20System
