### ISSUE TITLE
Maintain tab order when switching containers

### ISSUE THREAD

**Issue by pauljt** [mozilla/contain-facebook#56]
From email:

> Whenever I navigate to facebook, it seems to close the current tab, and create a new tab at the end of all the tabs that are open.
> 
> This is quite annoying when I have multiple tabs open and I want facebook to be at a certain position, and not having to scroll to the end all the time.

I think this is because when we switch we:
 browser.tabs.create({url: requestUrl.toString(), cookieStoreId: facebookCookieStoreId});
browser.tabs.remove(options.tabId);

IE create a new tab and delete the old one.  (meaning that we get tab on the right most edge). Can we control tab ordering with web extensions? Not sure? Could we just re-use the existing tabId when we swtich?

**Comment by stoically** [comment]
It's possible to give [create](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create) an `index`, so yes, the call to create could use the index of the tab that gets removed.

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Facebook Container (v1.2.5) on latest Firefox Release 59.0.2 (both official version and unbranded one), on Windows 10 x64, Mac 10.13.3 and Ubuntu 14.04 x64. 

However, the fix for this issue introduced a regression, that is being tracked in #73 issue.
