### ISSUE TITLE
Include subdomains when adding sites to the FB Container

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/contain-facebook#567]
## Issue Summary
When someone adds a site to the Facebook Container, it does not include any subdomains for that site. This becomes problematic when a site auths on a separate domain, or the authorized user is redirected to a subdomain after logging in. 

### Example: 
- Spotify authorizes on https://accounts.spotify.com, so it can be added to the FBC, but the main domain, Spotify.com is not.

## Solution: 
- Include wildcard matching for any subdomain to also be included in the Facebook Container

Related issues: 
- #447 
- #422

**Comment by PreciousChaos** [comment]
But how do you add a site to the Facebook Container?? There really should be a clear way to do this. Each update, I keep expecting that it might be more accessible, but no...

**Comment by maxxcrawford** [comment]
@PreciousChaos Currently, the only method is to add sites on sites/pages that offer the ability to "Login with Facebook". Follow #422 for the ability to add any site to the Facebook Container manually.

**Comment by maxxcrawford** [comment]
@PreciousChaos The [newest version](https://github.com/mozilla/contain-facebook/releases/tag/2.1.0) of the add-on has been released! 

---

To **add** a site to the Facebook Container, open the panel on whichever page you wish to include, and click "Allow site in Facebook Container" button. First, it will confirm this action and then add it and reload the page. _Note that `about:` system pages cannot be added_. 

![image](https://user-images.githubusercontent.com/2692333/74570315-f891e180-4f41-11ea-8523-a3e22e647861.png)

To **remove** a site from the Facebook Container, you can do the inverse, by navigating to a page within the Facebook Container<sup>*</sup>, open the panel and click: 

![image](https://user-images.githubusercontent.com/2692333/74570952-c92fa480-4f42-11ea-99ee-b88578d934dc.png)

Additionally, you can manage all the custom sites that have been added by clicking on "Sites Allowed in Facebook Container".  _Note that [Facebook-owned domains](https://github.com/mozilla/contain-facebook/blob/master/src/background.js#L7-L23)_ cannot be removed. 

![image](https://user-images.githubusercontent.com/2692333/74570327-fc256880-4f41-11ea-9ef3-d96786e949d3.png)
