### ISSUE TITLE
The Get Tickets button of bandsintown.com redirects to a blank page when Facebook Container is enabled

### ISSUE THREAD

**Issue by Elcoid** [mozilla/contain-facebook#571]
- Facebook Container Version: 2.0.3
- Operating System + Version: Kubuntu 18.04 LTS, kernel 5.1.5-050105-generic
- Firefox Version: 72.0.1 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Amazon.co.uk	1.1	true	amazon@search.mozilla.org
Bing	1.0	true	bing@search.mozilla.org
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
Ecosia	1.0	true	ecosia@search.mozilla.org
Facebook Container	2.0.3	true	@contain-facebook
Google	1.0	true	google@search.mozilla.org
LEO Eng-Deu	1.0	true	leo_ende_de@search.mozilla.org
Twitter	1.0	true	twitter@search.mozilla.org
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org
Cookie Quick Manager	0.5rc2	false	{60f82f00-9ad5-4de5-b31c-b16a47c51558}
Disable JavaScript	2.3.1	false	{41f9e51d-35e4-4b29-af66-422ff81c8b41}
Ecosia - The search engine that plants trees	4.0.4	false	{d04b0b40-3dab-4f0b-97a6-04ec3eddbfb0}
Forget Me Not - Forget cookies & other data	2.2.6	false	forget-me-not@lusito.info
Invert Colors	0.1.6.1	false	@firefoxinvertcolors
uBlock Origin	1.24.2	false	uBlock0@raymondhill.net
User-Agent Switcher and Manager	0.3.4	false	{a6c4a591-f1b2-4f03-b3ff-767e5bedf4e7}
Video Downloader professional	1.98.2	false	ffext_basicvideoext@startpage24
Video DownloadHelper	7.3.7	false	{b9db16a4-6edc-47ec-a1f4-b86292ed211d}
Web Developer	2.0.5	false	{c45c406e-ab73-11d8-be73-000a95be3b12}

### Actual behavior
When going on the ticket purchase page for any event on bandsintown.com, the page becomes blank and nothing happens.

### Expected behavior
The ticket purchase page should redirect to the event location's website to be able to purchase tickets.

### Steps to reproduce
1. Pick any event on bandsintown.com, for example: https://www.bandsintown.com/e/101635140-billie-eilish-at-chi-health-center-omaha
2. Click on Get Tickets, in the left column under the artist's picture (Depending on when the example page is visited, the button might be gone. In this case, just pick any random event on the website.)
3. The page becomes blank.

### Notes
The same behavior was also observed on Kubuntu 16.04 LTS yesterday, but I don't remember the version numbers of the add-on, Firefox and the kernel.

**Comment by Behrox** [comment]
Facing a similar issue trying to access bitbucket.org with Facebook container enabled

**Comment by maxxcrawford** [comment]
@Elcoid Looks like [bandsintown.com](bandsintown.com) uses Facebook resources to manage the redirects to ticket website. You'll need to add that site to the container to make it work. This is possible with the latest release of the add-on. Be sure you're up to date! 

@Behrox I wasn't able to reproduce the blank page issue on Bitbucket. Can you please provide more info on how to trigger the issue?

**Comment by maxxcrawford** [comment]
Is this still reproducible on the latest version of the add-on (2.1.1) and Firefox (77.0.1)?

**Comment by Elcoid** [comment]
With Facebook Container 2.1.1 on Firefox 80.0.1, the add-on's menu doesn't let me allow the website in the container. I am able to allow other websites however.

**Comment by maxxcrawford** [comment]
@Elcoid Follow these directions [from the docs](https://github.com/mozilla/contain-facebook/blob/master/docs/container-management.md). I was able to add https://www.bandsintown.com to the Facebook Container. Please reopen this if adding the site doesn't get your issue resolved. Thanks!

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/2692333/93421120-19bf0580-f876-11ea-8e42-ba0219b87ee2.png">

@Behrox If the Bitbucket issue persists, please open up a separate issue.
