### ISSUE TITLE
How do I remove the "Facebook ||||" message from FF's URL box?

### ISSUE THREAD

**Issue by tsuchan** [mozilla/contain-facebook#573]
When on the Facebook website, the contain-facebook extension places a message like "Facebook ||||" in the URL box.  It takes so much space, I can't even see the URL any more.  How do I remove that please?  Or is my only option to uninstall the plug-in?
Thanks and kind regards
- Andi

**Comment by maxxcrawford** [comment]
@tsuchan Could you please provide a screenshot?

**Comment by tsuchan** [comment]
Sorry @maxxcrawford ... I stumbled across the solution by accident last week, and by that time I'd forgotten I'd raised a support request:

I self-discovered a solution (by chance) by going to Tools > Options > General tab > Browsing, and turned off "Recommend extensions as you browse" and/or "Recommend features as you browse".

I tried re-enabling them to get you a screenshot, but it's not playing: maybe needs a restart, but it's the feature talked about in this page:
https://support.mozilla.org/en-US/kb/recommendations-firefox?redirectlocale=en-US&as=u&redirectslug=better-recommendations-firefox&utm_source=inproduct

A particular reason it's a hassle to me it that I have a lot of the URL bar real-estate used with my preference for a separate search bar (I re-enable that), and several useful plug-ins accessed through URL-bar buttons.
