### ISSUE TITLE
Facebook tab crashing

### ISSUE THREAD

**Issue by apeters89** [mozilla/contain-facebook#577]
- Facebook Container Version: 2.0.3
- Operating System + Version: Windows Server 2008 Enterprise R2
- Firefox Version: 72.0.2
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
Open a new facebook tab, with Container enabled, and the tab crashes within 10 seconds.  This happens consistently.  Disable Container and facebook operates as expected and the browser does not crash.

### Steps to reproduce
1. Have Facebook Container enabled
2. Open facebook
3. Wait 3-10 seconds.
4. Send crash report.

**Comment by maxxcrawford** [comment]
@apeters89 I wasn't able to reproduce this. Is there any other info you can please provide? 

- Were you logged into Facebook already? 
- You have no other addons installed? 

I'd love to get to the bottom of this. Thanks!

**Comment by apeters89** [comment]
In checking the Firefox version, an update was found.  After the update, Facebook container worked as expected.

I was already logged in to Facebook.

-Aaron Peters

**Comment by maxxcrawford** [comment]
Understand. Thanks!
