### ISSUE TITLE
Door hangers are not displayed for "Allow" and "Remove" functions 

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/contain-facebook#585]
**Affected versions**
* Firefox 74.0b4

**Affected platforms**
* Windows 10 x64
* macOS 10.15
* Ubuntu 18.04 x64

**Steps to reproduce**
1. Download [Facebook Container 2.1.0](https://github.com/mozilla/contain-facebook/releases/tag/2.1.0) .zip file and extract it.
2. Launch Firefox and go to `about:debugging#/runtime/this-firefox`.
3. Click on "Load Temporary Add-on...", then select `manifest.json` from the extracted archived.
4. Navigate to https://www.google.com/ in a new tab.
5. From the Url toolbar, click on the Facebook Container icon.
6. Click on the "Allow Site in Facebook Container" option.

**Expected result**
* A FBC door hanger is displayed with the "Allow" button, as per specs:

![image](https://user-images.githubusercontent.com/43886441/74664959-67bc3f80-51a7-11ea-8b01-ebd02a552ee5.png)

![image](https://user-images.githubusercontent.com/43886441/74664980-74d92e80-51a7-11ea-9a8e-3f7b3143109c.png)

**Actual result**
* There is no confirmation door hanger displayed after allowing or removing a website from FBC.

**Comment by gpalko-SV** [comment]
I've verified the fix on build 2.1.0-rc2 and logged #608
