### ISSUE TITLE
"about:" pages can be added to FBC, the titles are displayed as empty in the list and they can't be removed

### ISSUE THREAD

**Issue by gpalko-SV** [mozilla/contain-facebook#588]
- Facebook Container Version: 2.1.0
- Affected platforms:
      - Windows 10 x64
      - MacOS 10.15
      - Ubuntu 18.04

### Steps to reproduce
1. Add Facebook Container 2.1.0 to Firefox
2. Open any about: page in new tab (e.g about:support)
3. Allow the page in FBC
4. Click the Facebook Container icon and select "Sites Allowed in Facebook Container"

### Actual behavior
1. The page is added to list but the page title is displayed as empty
2. The page remains in the list after removing it from FBC
3. A new entry containing the add-on UUID is added to list after every Remove attempt

### Expected behavior
1. The page titles should be displayed in the Allowed list 
2. The about: pages should be removable from FBC
3. No new items should appear in the allowed list after remove operation 
 
OR

   The user should not be able to add "about:" pages to FBC

### Notes
See the attached screenshot
![aboutPageAdded](https://user-images.githubusercontent.com/55983084/74677050-140a2000-51c0-11ea-9673-23b86d8adaf8.PNG)

**Comment by maxxcrawford** [comment]
IMO I don’t think `about:` pages should be allowed inside the container. I recommend we handle them in the same way removing default Facebook domains (Facebook.com, Instagram.com, etc.) is not allowed.

![image](https://user-images.githubusercontent.com/2692333/74679099-7e03d480-5182-11ea-95e2-31eb14152567.png)

**Comment by gpalko-SV** [comment]
Verified on build 2.1.0-rc2, that about: pages cannot be added to FBC.
