### ISSUE TITLE
Google related pages are unusable, if they're added to FBC 

### ISSUE THREAD

**Issue by gpalko-SV** [mozilla/contain-facebook#591]
- Facebook Container Version: 2.1.0
- Affected platforms:
      - Windows 10 x64
      - MacOS 10.15
      - Ubuntu 18.04

### Steps to reproduce
1. Add Facebook Container 2.1.0 to Firefox
2. Open drive.google.com and sign in(any other google site can be used)
3. Click the Facebook Container icon and select "Allow Site in Facebook Container "

### Actual behavior
The tab is flickering indefinitely, as the redirection to accounts.google.com is not successfully made in order to sign out the user

### Expected behavior
The page should be added successfully to FBC

### Notes
The issue is reproducible on every google related site(docs, spreadsheets, drive, etc.)
If one of the sites is added to FBC, the issue is reproducible on all others

**Comment by maxxcrawford** [comment]
This is a known issue — #567

**Comment by maxxcrawford** [comment]
Fixed by #567
