### ISSUE TITLE
Spotify login page is not loaded, if the page is in FBC

### ISSUE THREAD

**Issue by gpalko-SV** [mozilla/contain-facebook#592]
- Facebook Container Version: 2.1.0
- Affected platforms:
      - Windows 10 x64
      - MacOS 10.15
      - Ubuntu 18.04

### Steps to reproduce
1. Add Facebook Container 2.1.0 to Firefox
2. Navigate to open.spotify.com and log in
3. Click the Facebook Container icon and select "Allow Site in Facebook Container "
4. Click the Log In or Sign Up buttons on the site

### Actual behavior
The Sign Up/Log In page is not successfully loaded

### Expected behavior
The users should be able to log in if the spotify page is added to FBC

**Comment by maxxcrawford** [comment]
This seems related to #567.

**Comment by maxxcrawford** [comment]
@gpalko-SV Confirmed on my end – #567 fixes this.
