### ISSUE TITLE
The Facebook tracker warning icon disappears when opening the door-hanger

### ISSUE THREAD

**Issue by sbadau** [mozilla/contain-facebook#593]
Affected versions
- Firefox 74.0b4

Affected platforms
- Windows 10 x64
- macOS 10.15
- Ubuntu 18.04 x64

Steps to reproduce
1. Download Facebook Container 2.1.0 .zip file and extract it.
2. Launch Firefox and go to about:debugging#/runtime/this-firefox.
3. Click on "Load Temporary Add-on...", then select manifest.json from the extracted archived.
4. Navigate to a site with Facebook trackers, eg https://www.amazon.com/
5. Observe the Facebook Container toolbar icon and click on it.

Expected result
A purple warning is attached over the "fence" icon of the Facebook Container add-on and should be visible while the door hanger is opened.

Actual result
When the Facebook Container toolbar icon is clicked, the purple warning disappears.
For more details, please see the attached video.

![PurpleWarning](https://user-images.githubusercontent.com/56026823/74729537-4a41b100-524d-11ea-9a7d-73a03661b24e.gif)

**Comment by maxxcrawford** [comment]
This is as expected. It's dismissing the notification that something was blocked. Specifically, the message (inside the panel that we've protected the user from Facebook tracking) remains.
