### ISSUE TITLE
Facebook container can't be accessed when the window is minimised 

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/contain-facebook#594]
Affected versions
* Firefox 74.0b4

Affected platforms
* Windows 10 x64
* macOS 10.15
* Ubuntu 18.04 x64

Steps to reproduce

1. Add Facebook Container 2.1.0 to Firefox
2. Navigate to any website
3. Minimise the window and move the window to the end of the desktop
4. Click on the Facebook Container icon

Expected result
There should be a scroll bar displayed to access facebook container options.

Actual result
Facebook container can't be accessed when the window is minimised.

https://imgur.com/a/fSxaQlt

**Comment by sv-hyacoub** [comment]
This issue is only reproducible now when "More tools" button is displayed (>>).

**Comment by maxxcrawford** [comment]
This looks like it's working now in Firefox 76.0.1 on OSX Catalina. Please reopen if this is still an issue. 

![image](https://user-images.githubusercontent.com/2692333/82230285-2562e580-98f1-11ea-84dc-7367605183de.png)
