### ISSUE TITLE
Facebook trackers are not detected when opening a link in a new tab

### ISSUE THREAD

**Issue by sbadau** [mozilla/contain-facebook#595]
Facebook Container Version: 2.1.0

Affected platforms:
- Windows 10 x64
- MacOS 10.15
- Ubuntu 18.04

Steps to reproduce
1. Add Facebook Container 2.1.0 to Firefox
2. Navigate to https://www.amazon.com/ and go to Today's Deals section
3. Navigate through the products, right-click on any product and select "Open link in a new tab"
4. Observe the Facebook Container toolbar icon and click on it
5. Go to the shield icon near the address bar, and look at the Allowed Tracking Content list.

Actual behavior
In step 4 the add-on doesn't detect the Facebook trackers, even if the Facebook trackers are allowed and present in the Tracking Content list.

Expected behavior
In step 4 the addon should detect the Facebook trackers (the purple warning should also be visible).
For more details, please see the attached video.

![NonDetectedTrackers](https://user-images.githubusercontent.com/56026823/74735763-04d7b080-525a-11ea-8087-b9833f3a78c4.gif)

**Comment by maxxcrawford** [comment]
It's still blocking elements – but the `!` notification/tracking text is getting dismissed. New tabs should have no effect on the active/current tab as the panel (and notification) is specific to only the active tab.

**Comment by maxxcrawford** [comment]
@sbadau Can you still reproduce this on the [latest version](https://github.com/mozilla/contain-facebook/releases/tag/2.1.1)?

**Comment by sbadau** [comment]
I can't reproduce this issue as initially logged, I can't see any Facebook trackers in the tracking content list anymore. Followed the exact steps as in the description.
