### ISSUE TITLE
Can't log in to Tinder account through facebook account

### ISSUE THREAD

**Issue by JosephHallenbeck** [mozilla/contain-facebook#602]
I am using Facebook container 2.0.3 in the Firefox 73.0 (64 bit). 
I have tinder account linked with facebook account but I can't log in to the Tinder. Tinder web can't opening in Facebook container tab and I don't see any facebook container sign over "Join through Facebook account" link.

**Comment by maxxcrawford** [comment]
@JosephHallenbeck I'm not able to reproduce it immediately (Same specs except Firefox 73.0.1). 

![image](https://user-images.githubusercontent.com/2692333/74856548-e5975c80-5307-11ea-81fa-6d3b99da6d7a.png)

After clicking on "Sign In", can you click inside the "Get Started" modal. It should trigger the badging system to fire again.

**Comment by JosephHallenbeck** [comment]
Nope. I don't have the smal icon of facebook container over "Log in with facebook". :-/

**Comment by JosephHallenbeck** [comment]
Problem is solved! It is due to the localization. I had tinder web in czech language. When I switched to english localization, the small icon showed up!

**Comment by maxxcrawford** [comment]
That's good. Going forward – we have a new release coming very soon where you can add any site to the Facebook Container manually. Thank you!

**Comment by soffieswan041** [comment]
> I am using Facebook container 2.0.3 in the Firefox 73.0 (64 bit).
> I have tinder account linked with facebook account but I can't log in to the Tinder. Tinder web can't opening in Facebook container tab and I don't see any facebook container sign over "Join through Facebook account" link.

**Comment by maxxcrawford** [comment]
@soffieswan041 Can you include a screenshot? This is what I get when I try to log-in:

<img width="850" alt="image" src="https://user-images.githubusercontent.com/2692333/134408050-7fe1ce66-ffc8-4719-8644-79ee4d37a294.png">

Additionally, you can log in by adding this website to the Facebook Container. Follow the directions [from the docs](https://github.com/mozilla/contain-facebook/blob/master/docs/container-management.md). Please let me know if this method works for you!
