### ISSUE TITLE
Timeline for Release 2.1.0 

### ISSUE THREAD

**Issue by kilasuit** [mozilla/contain-facebook#605]
I see there is lots of new features been added that would be incredibly useful.

How can I install the prerelease?

Or will the prerelease be turning into a release any time soon?

**Comment by maxxcrawford** [comment]
The [latest version](https://github.com/mozilla/contain-facebook/releases/tag/2.1.0-rc3) has been submitted to AMO for approval. It should roll out in the next few days!

**Comment by maxxcrawford** [comment]
@kilasuit If you want to test this build, please do the following: 

### Prerequisites: 
- You must use [Dev edition or Nightly](https://www.mozilla.org/en-US/firefox/channel/desktop/) and set the following pref (via `about:config)`: 
  - `xpinstall.signatures.required` set to `false`

### Install steps: 
- Download this ZIP file of the latest build. 
[https://github.com/mozilla/contain-facebook/archive/2.1.0-rc3.zip](https://github.com/mozilla/contain-facebook/archive/2.1.0-rc3.zip)
- Go to `about:addons`, and click the gear icon and select: "Install Add-on From File…"
![image](https://user-images.githubusercontent.com/2692333/75803573-44b39300-5d44-11ea-955b-a7692efbfa83.png)

**Comment by maxxcrawford** [comment]
@kilasuit The [newest version](https://github.com/mozilla/contain-facebook/releases/tag/2.1.0) of the add-on has been released! It should update automatically on its on, but if you'd like to speed that process up: 

- Go to `about:addons`
- Click the Gear icon
- Select "Check for Updates" 

<img width="339" alt="image" src="https://user-images.githubusercontent.com/2692333/76077701-d995d680-5f66-11ea-8cb4-8739d9a7b05d.png">

**Comment by kilasuit** [comment]
Seems it auto updated for me earlier on this morning 😀

Thanks for all the work you do on this extension
