### ISSUE TITLE
Google related pages added to FBC can't be accessed when logged in using SSO accounts

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/contain-facebook#611]
*  Affected versions
Firefox 74.0 RC Build 2

* Affected platforms
Windows 10 x64
macOS 10.15
Ubuntu 18.04 x64

* Steps to reproduce
1. Download Facebook Container 2.1.0-rc2.zip file and extract it.
2. Launch Firefox and go to about:debugging#/runtime/this-firefox.
3. Click on "Load Temporary Add-on...", then select manifest.json from the extracted archived.
4. Navigate to drive.google.com and sign in using SSO account. (ex. @mozilla.com)
5. Click on the Facebook Container icon and select "Allow Site in Facebook Container".
6. Enter the email address again.

* Expected result
Google related pages added to FBC can be accessed when logged in using SSO accounts.

* Actual result
Google related pages added to FBC can't be accessed when logged in using SSO accounts.

![Screenshot 2020-03-06 at 10 52 05](https://user-images.githubusercontent.com/15101135/76067910-d9aeca00-5f98-11ea-9903-6d358ec67036.png)

**Comment by maxxcrawford** [comment]
Can you confirm this issue exists with the new 2.1.0 version? The version this was tested with in this issue specifically did not have subdonaun support feature added yet.

**Comment by sv-hyacoub** [comment]
Yes, I confirm that this issue exist with the new 2.1.0 version.

**Comment by maxxcrawford** [comment]
At what step do you add the site to the container? I only see the step where you remove it. (Step 5 is only possible if you add the site to the container at some point)

**Comment by sv-hyacoub** [comment]
My bad there. Step 5 should be: Click on the Facebook Container icon and select "Allow Site in Facebook Container".
I'll update step 5.

**Comment by maxxcrawford** [comment]
Ahh – I see the problem. When you enter the SSO address, it sends you a non-Google OAuth site to login to the SSO. This site is NOT in the container. You will need to manually add that site also to the container. 

I don't believe this is a bug, as much as a technicality of how the extension determines sites inside and outside of the container.

**Comment by maxxcrawford** [comment]
@sv-hyacoub Closing this for now. Please reopen if needed.
