### ISSUE TITLE
Facebook container doorhanger isn't correctly displayed when the page is not completely loaded

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/contain-facebook#612]
* Affected versions
Firefox 74.0 RC Build 2

* Affected platforms:
MacOS 10.14

* Steps to reproduce
1. Download Facebook Container 2.1.0-rc3.zip file and extract it.
2. Launch Firefox and go to about:debugging#/runtime/this-firefox.
3. Click on "Load Temporary Add-on...", then select manifest.json from the extracted archived.
4. Access any website and click on the Facebook Container icon.

* Actual behavior
Facebook container doorhanger isn't correctly displayed when the page is not completely loaded
![Screenshot 2020-03-06 at 14 23 50](https://user-images.githubusercontent.com/15101135/76083860-3caf5980-5fb7-11ea-889f-887724589b5b.png)

* Expected behavior
Facebook container doorhanger should be correctly displayed

**Comment by maxxcrawford** [comment]
@sv-hyacoub Can you confirm this is still happening on the [latest release](https://github.com/mozilla/contain-facebook/releases/tag/2.1.1)?

**Comment by sv-hyacoub** [comment]
Can't reproduce it anymore on the latest release.
