### ISSUE TITLE
problem logging in Facebook

### ISSUE THREAD

**Issue by StirlingAustin** [mozilla/contain-facebook#614]
Hello

I installed the Facebook container extension.

Then I found I was no longer able to log in to Facebook, on Firefox and Chrome.

I have deleted the extension, but I still am bloked from logging in.

Please help, screenshot attached.

thanks

Stirling Austin
![FB Container1](https://user-images.githubusercontent.com/357027/76403357-b612c780-637c-11ea-8e76-1cb3a902c761.png)

**Comment by gpalko-SV** [comment]
Hi,
 This is not an issue related to Facebook Container extension or Firefox browser. Looks like your Facebook account is restricted and you should reach out to them to solve this. Thank you!

**Comment by maxxcrawford** [comment]
Please reopen the issue if this continues, @StirlingAustin!
