### ISSUE TITLE
Facebook container signs out facebook each time you attempt and upload of profile picture

### ISSUE THREAD

**Issue by evananyonga** [mozilla/contain-facebook#616]
- Facebook Container Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
Facebook container signs you out each time you attempt and upload of profile picture

### Steps to reproduce
1.
2.
3.

**Comment by maxxcrawford** [comment]
@evananyonga I'm not able to reproduce this. Can you update your profile correctly when the extension is turned off? 

Can you include any other add-ons you have installed?

**Comment by evananyonga** [comment]
I think this issue has been fixed! The behaviour is now normal.
