### ISSUE TITLE
Using Facebook.com in facebook container intermittently renders blank page

### ISSUE THREAD

**Issue by therealthatoneguy** [mozilla/contain-facebook#621]
Steps to reproduce: ?? Intermittent
Workaround is to open Facebook in a new tab. It will then render as expected in a facebook container. Reloading in the existing tab doesn't work.

- Facebook Container Version: 2.1.0
- Operating System + Version: Windows 10
- Firefox Version: 74.0

Extensions:
Amazon.com	1.1	true	amazondotcom@search.mozilla.org
Bing	1.1	true	bing@search.mozilla.org
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
Facebook Container	2.1.0	true	@contain-facebook
Firefox DevTools ADB Extension	0.0.5	true	adb@mozilla.org
Force PDF Download	0.1.3.9	true	{d7f46ca0-899d-11da-a72b-0800200c9a65}
Google	1.0	true	google@search.mozilla.org
McAfee® WebAdvisor	8.0.0.37877	true	{4ED1F68A-5463-4931-9384-8FFF5ED91D92}
Side View	0.4.3710	true	side-view@mozilla.org
Test Pilot	3.0.6vffecb95	true	@testpilot-addon
Twitter	1.0	true	twitter@search.mozilla.org
Urlbar Tips	1.0.1	true	urlbar-tips@shield.mozilla.org
Wayback Machine	1.8.6	true	wayback_machine@mozilla.org
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org
Firefox Multi-Account Containers	6.2.3	false	@testpilot-containers
McAfee® Web Boost	1.0.0.25006	false	{EF0645D5-78D6-4B33-BC45-95B1874977AF}
Min Vid	0.4.9	false	@min-vid
Notes by Firefox	4.3.5	false	notes@mozilla.com
snoozetabs	1.0.20	false	snoozetabs@mozilla.com
Tab Center	1.36.0	false	tabcentertest1@mozilla.com
UI.Vision RPA	5.5.6	false	{190d04a6-e387-4f5b-9751-e0d222cf8275}

**Comment by maxxcrawford** [comment]
Please provide more information on how to reproduce. Thanks!
