### ISSUE TITLE
Ability to not automatically open Facebook in container

### ISSUE THREAD

**Issue by dylanmorroll** [mozilla/contain-facebook#625]
Hi there, I would find it useful if I could have Facebook (or other Facebook owned sites) not automatically open in their container.

This is so that when I'm trying to focus and mindlessly end up opening Facebook, it opens in the default container, where I won't be logged in. This will remind me that I shouldn't be on Facebook, and to go back to work.

However, currently it always opens in the Facebook container, where I am logged in, so I end up mindlessly scrolling anyway!

I figured I can just make my own container and keep myself logged in there and not use this extension - but I don't know if I would miss out on any of the other security features?

This seems to related to issue #198 but a slight variation.

Cheers!

**Comment by maxxcrawford** [comment]
@dylanmorroll Besides opening Facebook-owned sites in the Facebook container, Facebook Containers includes this security feature: It blocks all Facebook-domain assets (seen and unseen) on any non-FB site sites (Examples: [Facebook analytics](https://analytics.facebook.com) or their [SDK](https://developers.facebook.com/docs/javascript/)). Thanks!
