### ISSUE TITLE
Facebook Container FF extension

### ISSUE THREAD

**Issue by Vicantropo** [mozilla/contain-facebook#626]
- Facebook Container Version: 2.1.0
- Operating System + Version: Windows 10
- Firefox Version:  74.0.1 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
Disable in private browsing/window an there's not an option to enable it

### Expected behavior
to be enable in private browsing/window

### Steps to reproduce
1.
2.
3.

### Notes
![SharedScreenshot](https://user-images.githubusercontent.com/63147055/78424858-664ab780-762d-11ea-8de9-122e45d689a1.jpg)

**Comment by maxxcrawford** [comment]
This [is as intended](https://github.com/mozilla/contain-facebook/blob/master/src/manifest.json#L6). Private browsing mode using the [strict mode of Enhance Tracking Protection](https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop#w_strict-enhanced-tracking-protection), which blocks these trackers.
