### ISSUE TITLE
Instagram embeds on forums are broken when extension is enabled

### ISSUE THREAD

**Issue by BootsSiR** [mozilla/contain-facebook#630]
- Facebook Container Version: 2.1.1
- Operating System + Version: Windows 10 1909
- Firefox Version: 75.0

### Actual behavior

![firefox_2020-04-21_09-15-24](https://user-images.githubusercontent.com/350484/79865350-64b11b80-83b1-11ea-9088-1e64a6d4d60b.png)

### Expected behavior

![firefox_2020-04-21_09-16-11](https://user-images.githubusercontent.com/350484/79865359-68dd3900-83b1-11ea-8c52-cad8e4840e03.png)

### Steps to reproduce
1. view embedded instagram post on forum
2. embedded post will not show up
3. disable firefox container
4. refresh page
5. post shows up

### Notes
The forum I'm seeing this on is not open to the public however I've seen it on other forums.  I've added the forum url to the container extension to allow it and it does not change the broken behaviour

**Comment by maxxcrawford** [comment]
Can you confirm that the forum, once added to the Facebook Container, says "Facebook" in the URL bar? The expected behavior, is that once added to the Facebook Container, Instagram (along with any other blocked resources) should load correctly. 

![image](https://user-images.githubusercontent.com/2692333/79877305-b2c61f00-83b1-11ea-92e6-c0854e6714fc.png)

**Comment by BootsSiR** [comment]
@maxxcrawford it is indeed added.  I don't see any unusual messages in the console either.

![image](https://user-images.githubusercontent.com/350484/79878119-73a0c980-83c3-11ea-9674-8b9d9ec209fd.png)

**Comment by joexcool** [comment]
I can confirm the exact same behavior, along with the Facebook fence icon in the address bar.

**Comment by BootsSiR** [comment]
This is resolved.  I did some digging and the site in question uses a 3rd party site to embed content.  I had to whitelist that 3rd party site.
