### ISSUE TITLE
FB container breaks lowes.com

### ISSUE THREAD

**Issue by petteyg** [mozilla/contain-facebook#633]
When browsing lowes.com, there is some missing CSS, and reviews do not appear. If I "Allow Site in Facebook Container", the style changes quite a bit and reviews are suddenly visible. Also, the site login form does not work if not allowed in the container. I find no references to facebook.com in the page source. Is this a bug in FB Container, or does lowes.com have a (very well-hidden; uMatrix shows nothing loaded from facebook domains) dependency on Facebook resources?

**Comment by maxxcrawford** [comment]
@petteyg Looks like Lowes.com does have Facebook-specific assets loading on the site. I loaded the site in Firefox 76.0.1 (Stable release) and filtered [network requests](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_list) to the following: 

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/2692333/81704647-b0e10000-9433-11ea-9f10-3dd77533a680.png">

I don't see the missing review elements you're describing. (I was using this [URL as my test page](https://www.lowes.com/pd/John-Deere-Z335E-20-HP-V-Twin-Dual-Hydrostatic-42-in-Zero-turn-Lawn-Mower-with-Mulching-Capability-Kit-Sold-Separately/1000607721)) 

WIthout Facebook Container - Reviews:
![image](https://user-images.githubusercontent.com/2692333/81705482-b25ef800-9434-11ea-8a79-23edd6ffaaf8.png)

With Facebook Container - Reviews: 
![image](https://user-images.githubusercontent.com/2692333/81705679-eb976800-9434-11ea-9564-074f96c2253d.png)

**Comment by petteyg** [comment]
Well, I did complain to Lowe's about it, and the behavior has changed on my end, also. Looks like they fixed it on their end.

**Comment by maxxcrawford** [comment]
Copy that. Thank you for reporting, regardless! Closing for now.
