### ISSUE TITLE
Container breaks twitch.tv

### ISSUE THREAD

**Issue by petteyg** [mozilla/contain-facebook#634]
After logging in to twitch, and entering the 6-digit code from an email verification, if twitch.tv is not added to FB Container "allowed sites", the page brings up an error saying "invalid CSRF token". With twitch.tv added to allowed sites, login works.

**Comment by maxxcrawford** [comment]
@petteyg To confirm, when logging into Twitch, are you Logging in with Facebook or via first-party account (Email/pwd)? 

I was able to login without issue using a first-party account and through Login with Facebook. There were no visual page breaks, or CSRF token issues.

Can you also please include any other extensions you have enabled and your browser version?

**Comment by petteyg** [comment]
Firefox is 76.0. I also have uMatrix and uBlock. FWIW I cannot reproduce now either, but when I reported the issue I reproduced it over and over by just toggling the "allow in container" option.
