### ISSUE TITLE
The add-on Facebook Container causes, in Firefox, a problem displaying Elementor's widget "Facebook page"

### ISSUE THREAD

**Issue by srpotman72** [mozilla/contain-facebook#635]
Dear, I checked the settings, as per your template and it's all positive. Still the issue is there. Hope you can help.
- Facebook Container Version: 2.1.1.
- Operating System + Version: Windows 10 home 19041.208
- Firefox Version: 76.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status: NA (all de-installed and problem still there.

### Actual behavior
The add-on Facebook Container causes, in Firefox, a problem displaying Elementors (plugin on WordPress) widget "Facebook page". Actually the widget is not shown at all.
You can see the issue on https://aqqii.com/def/ This is a clean installation (only Plugin Elementor) on Theme "Twenty Twenty".
I registered the issue to Elementor and they responded the following : "We kindly recommend reporting this issue to the third-party plugin author, they'd be in a better position to address this issue or assist you with this. If they need any help from us, they can open an issue on our Github account and our developers will be happy to assist. https://github.com/elementor/elementor/issues

### Expected behavior
The add-on Facebook Container should not block the showing of this widget.

### Steps to reproduce
1. Clean WordPress installation
2. Install pagebuilder Elementor PRO
3. use Widget "Facebook page"
4. View the page with Firefox and the addon Facebook Container

### Notes
Thanks for looking into this!

**Comment by maxxcrawford** [comment]
@srpotman72 Facebook Container blocks ALL Facebook resources on pages not inside the Facebook Container. The Facebook widget relies on Facebook assets. Looking for Elemetor's [description of the widget](https://elementor.com/widgets/facebook-widgets/), it includes [Facebook SDK](https://developers.facebook.com/docs/javascript/) integration, which is blocked by this extension. **This behavior is as intended for the extension.**

To get it to load, you'll need to [add any domains](https://github.com/mozilla/contain-facebook/blob/master/docs/container-management.md) you're working on to the Facebook Container. 

![image](https://user-images.githubusercontent.com/2692333/81728632-64f08400-9450-11ea-9b06-66d6d28267b4.png)
