### ISSUE TITLE
Impossible to log in workplace with self hosted SSO 

### ISSUE THREAD

**Issue by mvbentes** [mozilla/contain-facebook#637]
Facebook Container	2.1.1	false	@contain-facebook
Bing	1.1	true	bing@search.mozilla.org
DuckDuckGo	1.0	true	ddg@search.mozilla.org
Firefox Multi-Account Containers	6.2.5	true	@testpilot-containers
Google	1.0	true	google@search.mozilla.org
Kee - Password Manager	3.2.7	true	keefox@chris.tomlinson
MercadoLivre	1.0	true	mercadolivre@search.mozilla.org
Mind the Time	2.2.0	true	jid0-HYNmqxA9zQGfJADREri4n2AHKSI@jetpack
Twitter	1.0	true	twitter@search.mozilla.org
uBlock Origin	1.26.2	true	uBlock0@raymondhill.net
Wikipedia (pt)	1.0	true	wikipedia@search.mozilla.org
Disconnect	5.19.3	false	2.0@disconnect.me
DownThemAll!	4.2.6	false	{DDC359D1-844A-42a7-9AA1-88A850A938A8}
Selenium IDE	3.17.0	false	{a6fd85ed-e919-4a43-a5af-8da18bda539f}
Snooze Tabs	1.1.1	false	snoozetabs@mozilla.com
Video DownloadHelper	7.3.9	false	{b9db16a4-6edc-47ec-a1f4-b86292ed211d}

### Actual behavior
I can not login to my workplace account. When I put my work e-mail address I believe it tries to redirect to a self-hosted (has my company domain address) SSO server. I enter the information and get the second factor token, but then, when I click submit I get to a 404 page on workplace.com. 
I think it is blocking the login process because it happens outside facebook.

### Expected behavior
Be able to use myemployer.workplace.com on the container. I do not have a personal facebook account, so I downloaded the extension just for this.
It works with the multi-account container, probably because it does not try to open outgoing traffic in a different tab. (I am aware I should not have facebook set to a container uppon installing this extension. I tried this after disabling facebookcoantainer extension)

### Steps to reproduce
1.Insert work domain e-mail
2.Get redirected to SSO page
3.Log in and fill 2FA correctly
4.Get redirected to a 404 page in "employer".workplace.com, while still not logged in.

### Notes
It seems to have logged me out correctly from workplace, even though on the work computer and on the company network I did not need to enter credentials.

**Comment by maxxcrawford** [comment]
@mvbentes You'll need to add the SSO website to the Facebook Container. Follow the directions [from the docs](https://github.com/mozilla/contain-facebook/blob/master/docs/container-management.md). Please reopen this if adding the site doesn't get your issue resolved.
