### ISSUE TITLE
Container + Multi Container?

### ISSUE THREAD

**Issue by sraaaaaaaaaaaaaaaa** [mozilla/contain-facebook#641]
- Facebook Container Version: 2.1.1
- Operating System + Version: Windows 10 64bit
- Firefox Version: 76.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status: Blur (disabled), ublock origin, Cookie Auto Delete (whitelisted), Decentraleyes, 1password

### Actual behavior
When I try to make a post in livejournal I am taken to "Error: We're sorry, but there was an error in the information you submitted. Please go back and try again. Comment not posted: POST required, or missing parameter."

The Facebook fence only appears in tabs when I have a multi-container with Facebook. If I disable it and delete the standalone Facebook container I can post comments.

Should I see the Facebook fence in my address bar in Facebook? I don't see it on any websites unless I have a Facebook container in multi.

This is a new problem, it began a few days ago. I have not changed anything with my computer or its software. At all. I have no idea what is happening or why.

### Expected behavior
Commenting on livejournal posts without issue. (I'm still unsure if the Facebook fence should appear without multi-containers or if that is an installation error on my part...despite it not being an error last Monday)

### Steps to reproduce
1. Have Facebook container and multi-container enabled
2. Go to a livejournal community
3. Try to post a comment

### Notes
I'm really confused?? I haven't changed anything but somehow my abillity to post on livejournal has messed up. It works if I disable the solo Facebook container (my other addons are already disabled when I visit the site to see twitter/instagram embeds)..but wasn't an issue last week. I don't know what happened. I tried adding *livejournal.com to the whitelisted sites inside the container...but it isn't helping! 

I wouldn't mind disabling the solo Facebook container if I could let it work on livejournal and still be active everywhere else. I'm still confused about the fence appearing in the address bar. Am I supposed to see the Facebook fence without a Facebook in multi-container???
![error](https://user-images.githubusercontent.com/65290661/81814546-d4ce3f80-9520-11ea-8a6a-e4a554bc53ee.PNG)

**Comment by sraaaaaaaaaaaaaaaa** [comment]
i uninstalled and reinstalled Facebook container and it seemed to solve the problem. Livejournal was already added to the facebook container. I was not using it to log into facebook but for some reason that particular add-on was breaking the comment part of the site

**Comment by maxxcrawford** [comment]
Awesome! Glad it's back to working for you.
