### ISSUE TITLE
[FF nightly] addon only works if I manually disable-then-reenable.

### ISSUE THREAD

**Issue by Pomax** [mozilla/contain-facebook#644]
If I visit `https://www.facebook.com/?sk=h_chr`, contain-facebook does not kick in until I go into the addmons manager, disable it, then reenable it. And then it only puts the facebook tab into a container: if I close that tab and open a new one directly to facebook, again: nothing happens.

- Facebook Container Version: 2.1.1
- Operating System + Version: win10 x64
- Firefox Version: nightly 78.0a1

### Actual behavior

nothing happens

### Expected behavior

the tab gets automatically put into a facebook container

### Steps to reproduce

1. I have no idea, it just stopped working properly.

**Comment by maxxcrawford** [comment]
@Pomax Do you have any other extensions running? Is this in an empty/clean profile?

**Comment by Pomax** [comment]
I have noscript and ad block plus. Neither of those interfered before.

**Comment by maxxcrawford** [comment]
@Pomax Is this still an issue? I'm currently unable to reproduce this.

**Comment by Pomax** [comment]
I suspect it was something that broke in Nightly and got fixed in a subsequent nightly release... so I guess this wasn't the extension doing anything out of the ordinary =)

**Comment by maxxcrawford** [comment]
Thought that might be it. Glad to hear it! 😄
