### ISSUE TITLE
Restrict permission "Access your data for all websites"

### ISSUE THREAD

**Issue by CSammy** [mozilla/contain-facebook#647]
Hey there,

first of all, thank you for this great add-on.

I have seen that the add-on requests the permission "Access your data for all websites" without any restrictions. Would it be possible to narrow this access down to just the pages/domains relevant for this add-on?

Reason:
I don't like to give general access like that to any add-on, and while, arguably, contain-facebook is not just any add-on but by a source I trust, requesting this permission without actually needing it (if that's the case) desensitizes users to it. It also encourages developers to drop the extra step of narrowing down access requests to the absolutely needed minimum. At worst, it becomes like permissions in the Android ecosystem where apparently very few people at all still check the permissions an app requests.

In my case, I'm not using the contain-facebook add-on myself, but I have been looking to use a fork that's aimed at YouTube tabs. I became suspicious when I noticed that it is requesting access to data for all websites, but the similarities to contain-facebook and the commits suggest that is simply due to it being a fork of contain-facebook, and not a deliberate desicion.

**Comment by groovecoder** [comment]
This isn't possible. We need to intercept ALL requests so we can intercept requests to non-Facebook sites and make sure they are opened OUTSIDE the Facebook Container.

**Comment by CSammy** [comment]
Thank you for the explanation, I appreciate it. I wasn't aware of the need to intercept the requests to non-facebook URLs to open them outside of the container. It's unfortunate but no way around it.
