### ISSUE TITLE
Chat closes when pasteing anything into the chat 

### ISSUE THREAD

**Issue by coltondick** [mozilla/contain-facebook#65]
Whenever you paste anything into a chat window (I have 2 chats open) it closes the chats and will not open any new chats until you refresh the page.

**Comment by TanviHacks** [comment]
Can you provide more details?  Are you using facebook.com or messenger.com?

**Comment by coltondick** [comment]
I'm using facebook.com. I've got two chats opened currently, and if I paste a URL using CRTL + V or Right-Click,> Paste both chats disappear. I've tried copying and pasting; URLs, Images, and blocks of text and they all force the chats closed until the page is refreshed.

**Comment by pauljt** [comment]
I've test this in a clean profile and I can't reproduce this issue. The steps I tried were:
 - install contain-facebook
 - open facebook
 - load two conversations
- paste various items into chat

I don't see the closing you are describing. Give that this affects messenger.com, and we don't currently isolate messenger.com, this sounds like a facebook issue, or something else in your browser (other extensions maybe?) that is interfering. Hard to say.

**Comment by coltondick** [comment]
I apologize for opening this issue. The issue is being caused by dom.event.clipboardevents.enabled = false in about:config.

**Comment by localpcguy** [comment]
I am seeing this issue as well, and dom.event.clipboardevents.enabled is set to true (default) in about:config.
