### ISSUE TITLE
Firefox Facebook Extension Not Supported After Mac OSX Catalina

### ISSUE THREAD

**Issue by silentbrave** [mozilla/contain-facebook#661]
-Apple has announced non-support of add-in extensions for Facebook after my current Operating System is upgrade to the next level or revision.  Will there be an upgrade to Firefox to provide a Container-like extension BUILT INTO the Firefox program??

- Operating System + Version:  Mac OSX Catalina
- Firefox Version:  77.0.1 (64-bit)
- Facebook Container Version:  2.1.1

- Other installed Add-ons + Version + Enabled/Disabled-Status:
o Norton Password Manager, v.2.1.1;
o Norton Safe Search, v.3.11.5.2;
o Norton Safe Web, v.3.11.4.2;
o Zoom Scheduler, v3.11.4.2;     with all these add-ons being Enabled

- Extensions
Name 	Version 	Enabled 	ID
Amazon.com	1.1	true	amazondotcom@search.mozilla.org
Bing	1.1	true	bing@search.mozilla.org
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
Facebook Container	2.1.1	true	@contain-facebook
Google	1.0	true	google@search.mozilla.org
Norton Password Manager	6.7.4.10	true	idsafe@norton.com
Norton Safe Search	3.11.5.2	true	nortonsafesearch_ul_ven_y_2@symantec.com
Norton Safe Web	3.11.4.2	true	nortonsafeweb@symantec.com
Twitter	1.0	true	twitter@search.mozilla.org
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org
Zoom Scheduler	2.1.10	true	{bf855ead-d7c3-4c7b-9f88-9a7e75c0efdf}
Finding Forms Pro	2.0.0	false  webext@FindingFormsPro -->

### Actual behavior
o N/A - Facebook Container soon to be extinct

### Expected behavior
o Upgrade to FireFox application

### Notes
o None

**Comment by maxxcrawford** [comment]
I believe this only applies to _Safari_ [browser extensions](https://developer.apple.com/videos/play/wwdc2020/10665/), rather than Firefox. Can you link to documentation supporting this?
