### ISSUE TITLE
Facebook Games need to allow external/non-FB scripts into the Facebook Container. 

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/contain-facebook#663]
Applications on apps.facebook.com load external (allow-listed) scripts. These scripts are allowed by Facebook, but blocked by the Facebook Container. 

The work around is to look at network traffic, and add whatever domains are being blocked to the Container. 

Examples: 
- https://apps.facebook.com/angrybirds
  - Add https://angrybirds-facebook.appspot.com to the FBC
- https://apps.facebook.com/wordswithfriends/
  - Add zynga.com to the FBC

Related issues: 
- #480
- #393

**Comment by ozgey99** [comment]
We are having the same issue with our Facebook application on https://apps.facebook.com/benderimki-anket/
The error on the developer console: the script at “https://connect.facebook.net/en_US/sdk.js” cannot be loaded.
Disabling the Facebook Container add-on solves the issue.
