### ISSUE TITLE
ctrl-click on a facebook page moves focus from the current page upon tab load

### ISSUE THREAD

**Issue by Pomax** [mozilla/contain-facebook#67]
Links opened in FF with ctrl-click will open in a new tab, without moving the focus to that tab so that it loads in the background and is available when the user decides to explicitly bring that tab to the forefront. However, the current version of this addon seems to "steal" focus in that ctrl-clicking a link in the facebook domain will open it in a container tab and then immediately bring that tab to the forefront.

I don't know if that's something this addon can fix, or whether that's a problem with the container API.

**Comment by stoically** [comment]
Fix for this is already merged in #64 and will be available with the next version.

**Comment by stoically** [comment]
Fixed in published version 1.2.5
