### ISSUE TITLE
Instagram photo stream broken

### ISSUE THREAD

**Issue by Darryl1970-P** [mozilla/contain-facebook#671]
- Facebook Container Version:2.1.1
- Operating System + Version: Windows 10 Ent
- Firefox Version: 79
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
Navigate to a website (created with Wix), which contains an Instagram Photostream.

### Expected behavior
Ability to view the photos

### Steps to reproduce
1. navigate https://www.efcakron.org/gallery
2. attempt to view photo stream
3.

### Notes
Is there a setting to disable the FBC, per web site? Is there something the church admin can do to make it more compliant?
![Capture](https://user-images.githubusercontent.com/69209993/89318128-5b8c4780-d64c-11ea-8e9b-750f4d74d8d3.PNG)

**Comment by maxxcrawford** [comment]
@Darryl1970-P Thanks for filing! This behavior is as expected, as Facebook Container blocks all Facebook resources (including the Instagram APIs and CDN) on non-Facebook sites. Note that we are looking at a setting/pref to change this behavior specifically for Instagram integrations. (#402) 

You can add this website to the Facebook Container. Follow the directions [from the docs](https://github.com/mozilla/contain-facebook/blob/master/docs/container-management.md). Please reopen this if adding the site doesn't get your issue resolved. Thanks!
