### ISSUE TITLE
Extension is preventing me from issuing Facebook Business Boletos

### ISSUE THREAD

**Issue by dloiola** [mozilla/contain-facebook#674]
- Facebook Container Version: **2.1.1**
- Operating System + Version: **Arch Linux | Kernel: 5.8.1-zen1-1-zen**
- Firefox Version: **79.0 (64-bits)**
- Other installed Add-ons + Version + Enabled/Disabled-Status: 
  1. **Integração Gnome Shell** | v.10.1 | *Enabled*
  2. **Qwant Basic** | v.1.0.6 | *Enabled*
  3. **uBlock Origin** | v.1.29.0 | *Enabled*
  4. **Vimium C - All by Keyboard** | v.1.84.3 | *Enabled*
  5. **Plasma Integration** | v.1.7.6 | *Disabled*
  6. **Trydactyl** | v.1.20.0 | *Disabled*

### Actual behavior
When the extension is active, instead of generate a Boleto(billet)¹, an error page is loaded.

### Expected behavior
I thought it would not affect the Business Manager behavior.

### Steps to reproduce
1. Goto Business FB/Payment Methods 
2. Click "Add Money", input an amount and click review payment

### Notes
¹ I'm not sure which is the english word for "Boleto Bancário".

**Comment by maxxcrawford** [comment]
When you click "Add Money", it's trying to connect to a site outside of Facebook. You'll need to that website to the Facebook Container. Follow the directions [from the docs](https://github.com/mozilla/contain-facebook/blob/master/docs/container-management.md). Please reopen this if adding the site doesn't get your issue resolved. Thanks!

**Comment by dloiola** [comment]
Thats right, Maxx, now it's woking fine. Thanks a lot.
