### ISSUE TITLE
Breaks Tiny Tiny RSS & inoreader

### ISSUE THREAD

**Issue by mbnoimi** [mozilla/contain-facebook#683]
Both two readers became unable to show Facebook posts collected by rss services ex. [rss bridge](https://github.com/RSS-Bridge/rss-bridge/) in case if enabling Facebook Container extension.

- Facebook Container Version: 2.1.2
- Operating System + Version: Linux Mint 20
- Firefox Version: 81.0 (64-bit)

**Comment by groovecoder** [comment]
Closing as-expected. It looks like the readers are pinging to Facebook for the RSS, which we want to block to make sure Facebook doesn't receive any information from the browser.
