### ISSUE TITLE
Let me accidentally access another FB account on my home network.

### ISSUE THREAD

**Issue by SuperSteveInTheHouse** [mozilla/contain-facebook#694]
- Facebook Container Version: 2.1.2
- Operating System + Version: Version 10.0.18363 Build 18363
- Firefox Version: 82.0.2
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Amazon.com	extension	1.3	true	amazondotcom@search.mozilla.org
Bing	extension	1.2	true	bing@search.mozilla.org
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
eBay	extension	1.2	true	ebay@search.mozilla.org
Google	extension	1.1	true	google@search.mozilla.org
Javascript Switcher	extension	1.4.0	true	{d7e0a6e7-9a50-490a-be5c-3b448be39b42}
Privacy Badger	extension	2020.10.7	true	jid1-MnnxcxisBPnSXQ@jetpack
Shut Up: Comment Blocker	extension	7.0	true	{b6840179-45a1-4a2d-a4ef-e2815c1faa28}
uBlock Origin	extension	1.30.6	true	uBlock0@raymondhill.net
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org

### Behavior

Immediately after installing the add on I was unable to log in to any FB account other than a family members account that had a saved username/password in my Firefox. It would autofill and not accept any other accounts. The bigger issue is, that account has never been signed on to my computer. No one other than me has ever used this computer, especially not with private passwords. They were logged in to FB on their computer at the time which is on the same wifi network but I can see no other connection between my computer and their FB account.

Upon further inspection I found more data lifted off of the other computers web browser. It gave me multiple saved username/password combinations to healthcare and financial websites. This is a pretty serious issue.

### Steps to reproduce

I installed the add on from this [link](https://support.mozilla.org/en-US/kb/trackers-and-scripts-firefox-blocks-enhanced-track?as=u&utm_source=inproduct#w_social-media-trackers). Down in the grey box that mentions Facebook.
It just started happening immediately.

### Fix

I had to delete the add on, delete the new saved username/password from firefox, and reset my own password via Facebook before it would work properly again.

### Notes
The computer that the data was drawn from
Windows 10.0.19041
MS Edge 86.0.622.56 64-bit

**Comment by arthuredelstein** [comment]
It seems very unlikely that Facebook Container is responsible for this.
