### ISSUE TITLE
Exceptional sites?

### ISSUE THREAD

**Issue by archerindigo** [mozilla/contain-facebook#701]
Hi,

Is there any way to put some non-facebook sites into the Facebook container? My Duolingo account has to login with Facebook but the "Login with Facebook" button on Duolingo has no icon for allowing it in the container. Manually move the Duolingo tab into Facebook container is not successful either. The tab will immediately be dropped out from the container. Now I can only temporary disable the addon in order to login.

**Comment by osnelson-git** [comment]
I would second this.  There are some (rare) cases where the fbclid is useful for troubleshooting; right now it appears to be stripped wholesale.

**Comment by osnelson-git** [comment]
> Hi,
> 
> Is there any way to put some non-facebook sites into the Facebook container? My Duolingo account has to login with Facebook but the "Login with Facebook" button on Duolingo has no icon for allowing it in the container. Manually move the Duolingo tab into Facebook container is not successful either. The tab will immediately be dropped out from the container. Now I can only temporary disable the addon in order to login.

I couldn't reproduce this in the "Facebook Container" add-on v 2.1.2 released today.  Navigating to duolingo.com, clicking the fence icon for "Facebook Container", and then clicking "Allow Site in Facebook Container" allowed me to log in with my Facebook account as expected.

**Comment by archerindigo** [comment]
> 
> 
> > Hi,
> > Is there any way to put some non-facebook sites into the Facebook container? My Duolingo account has to login with Facebook but the "Login with Facebook" button on Duolingo has no icon for allowing it in the container. Manually move the Duolingo tab into Facebook container is not successful either. The tab will immediately be dropped out from the container. Now I can only temporary disable the addon in order to login.
> 
> I couldn't reproduce this in the "Facebook Container" add-on v 2.1.2 released today. Navigating to duolingo.com, clicking the fence icon for "Facebook Container", and then clicking "Allow Site in Facebook Container" allowed me to log in with my Facebook account as expected.

Ah... I didn't notice the fence icon in the toolbar as I hided it. Thanks for remaining me.
