### ISSUE TITLE
[privacy] opening a link from facebook share the container with facebook

### ISSUE THREAD

**Issue by nathanaelle** [mozilla/contain-facebook#71]
TLDR :

any link opened from "facebook" container, share everything with facebook

Step to reproduce :

  1. open facebook
  2. open any link in a new tab
  3. the new tab is in "facebook" container so the link may share data with facebook

Suggestions :

 * restrict URL allowed in a container with regural expression list
 * resrict URL allowrd in a container with a white list

**Comment by stoically** [comment]
Closing as this is reported to be working in #72
