### ISSUE TITLE
Facebook Container blocks access to Facebook even after uninstall

### ISSUE THREAD

**Issue by 84korg** [mozilla/contain-facebook#723]
Hello,

I uninstalled the Facebook Container and Google Container extensions.

I reinstalled Facebook Container just in case it could work again. It didn't.

I did multiple firefox refreshes.

I even did a few clean re-installs; that is, I deleted the followings:

Firefox app 

~/Library/Caches/Firefox
~/Library/Caches/Mozilla

~/Library/Application Support/Firefox
~/Library/Application Support/Mozilla

~/Library/Saved Application State/org.mozilla.firefox.savedState
~/Library/Saved Application State/org.mozilla.crashreporter.savedState

Nothing works at all.

I still cannot access Facebook. (Error message: Hmm. We’re having trouble finding that site. We can’t connect to the server at www.facebook.com.) My other browsers can access Facebook just fine.

I can access Gmail, but can't log in at all. My other browsers work just fine.

I'm running Firefox 78.7.0esr on OS X 10.11.6 El Capitan.

Any help would be greatly appreciated. Thank you!

**Comment by furoma** [comment]
I just want a clean reinstall. This should be an easy fix. :)

**Comment by maxxcrawford** [comment]
@furoma Just to confirm, can you access Facebook in [Private Browsing mode](https://support.mozilla.org/en-US/kb/private-browsing-use-firefox-without-history)?

**Comment by furoma** [comment]
I didn't try that, mate.

Anyway, all the issues disappeared just after my Firefox umpteenth re-install at midnight. I guess the cookies or something expired at midnight, just like the spell on Cinderalla!
