### ISSUE TITLE
Opening an URL in a new tab via keyboard (Alt-Enter) doesn't use the same container

### ISSUE THREAD

**Issue by karlschottler** [mozilla/contain-facebook#724]
- Facebook Container Version: 2.1.2
- Operating System + Version: Windows 10, 20H2 (build 19042.746)
- Firefox Version: 85.0
- Other installed Add-ons + Version + Enabled/Disabled-Status:
-- Momentumdash.com, enabled, 2.1.10

### Actual behavior
Opening a new tab via keyboard opens the new tab not in the same container as where I started in.

### Expected behavior
I expected that the new tab opens in the same container instead of no container or any other.

### Steps to reproduce
1. I am surfing in a container tab, i.e. Work. 
2. I enter a new URL in the adress bar.
3. I want to open it in a *new* tab, so I press <Alt><Enter>. 
4. The URL opens in a new tab. The tab isn't opened in a container, but without a container.

### Notes
I am a strict container user, as this is my possibility to have "multiple instances of a browser" next to each other without any interference. To do so, I use "Select a container for a new tab". This is the key feature. The extra mouse click when opening a new tab is worth the effort. I ultimately would love it if the option "No container" would be replaced with an option like "Default container". This would make it possible to remove the default container from time to time. This would mean to start with a new browser instance, like "Delete all cookies".

This bug (?) enforces that I have to select the container for the new tab via mouse. It can't be set via keyboard, so I have to switch from mouse to keyboard and back.

**Comment by maxxcrawford** [comment]
@karlschottler This bug may apply more to [Multi-account Containers](https://github.com/mozilla/multi-account-containers/issues/new). Can you do it with that extension active and this disabled?

**Comment by karlschottler** [comment]
I installed [Multi account conatiners](https://addons.mozilla.org/firefox/addon/multi-account-containers/), though I hesitated because of the description of the parallel use and I was afraid of losing my container contents and configurations. Maybe, it is a good idea to merge these two addons into a single addon?

To answer your question: No, nothing changed

**Comment by maxxcrawford** [comment]
@karlschottler  This project (Facebook Container) was built on top of Mulit-account Containers as a specific Facebook-only extension. I would recommend posting your issue in that repo if you're still encountering the bug.
