### ISSUE TITLE
Facebook share tabs are wrongly opened in 1st position of the tab strip

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/contain-facebook#73]
[Affected versions]:
- Firefox 59.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Facebook Container" add-on (1.2.5) installed.

[Steps to reproduce]:

1. Start the Firefox browser with the profile from prerequisites.
2. Navigate to a website that has Facebook share plugin installed (eg. brightside, cnn).
3. Click on an article from the page (eg https://brightside.me/inspiration-tips-and-tricks/effective-tips-on-how-to-choose-the-perfect-glasses-for-your-face-480060/). 
4. Click the "Share on Facebook" button and observe the behavior.

[Expected result]:
- A share page in a Facebook container tab is opened in the last position of the tab strip.

[Actual result]:
- The share page is opened in the 1st position of the tab strip.

[Notes]:
- This issue is not reproducible with the Facebook Container (v.1.2.4) from AMO.
- Here is a screen recording of the issue: 
![tab moved - fb tainer](https://user-images.githubusercontent.com/31244235/38082829-879353ce-3350-11e8-8c7a-b134f8947023.gif)

**Comment by stoically** [comment]
That's a regression introduced with #56. I've opened PR #76 to fix it - which also includes that the popup stays open instead of getting closed and reopened as tab in the main window, which is technically also a bug currently present in 1.2.4

**Comment by pdehaan** [comment]
Verified in **1.3.1**. Current behavior for CNN and Bright Side seems to be to open the Facebook share page in a popup.
