### ISSUE TITLE
Saynamyen

### ISSUE THREAD

**Issue by Thiraw** [mozilla/contain-facebook#731]
- Facebook Container Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Steps to reproduce
1.
2.
3.

**Comment by maxxcrawford** [comment]
Could you please include more information about this issue?

**Comment by Odyssey346** [comment]
I think this might be spam.

**Comment by maxxcrawford** [comment]
@Odyssey346 Agreed. 🙈 

@Thiraw If this is a real issue, please re-open with additional information. Thanks!
