### ISSUE TITLE
Regularly clear facebook cookies in other containers or strip them from subresources completely. 

### ISSUE THREAD

**Issue by lucasbfr** [mozilla/contain-facebook#74]
It looks like facebook cookies are only cleared when the extension is installed.

Since facebook is no longer usable in the default container cookies, we should probably still delete cookies every once in a while, to prevent logged-out tracking. Is this possible?

**Comment by stoically** [comment]
Cookies are cleared on every initialization of the Add-on, that is: after installation, after disabling/enabling and after browser-start. However, it might be worth to consider removing cookies set by `FACEBOOK_DOMAINS` [if they get set](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies/onChanged) in non-Facebook Containers.

**Comment by TanviHacks** [comment]
@stoically - are facebook cookies cleared on every browser restart?  That is what I thought from reading the code, but QA said that didn't happen in practice.  I would imagine we would be getting a lot more complaints about not staying logged in in the facebook container if that were the case.

@pdehaan to confirm.

**Comment by TanviHacks** [comment]
I just checked, and my facebook cookies aren't wiped on browser restart.

**Comment by stoically** [comment]
@TanviHacks The scenarios I've described only affect the `firefox-default` container. Cookies in the Facebook Container are never cleared, that's correct -which from my current understanding is expected behavior

**Comment by SoftVision-PaulOiegas** [comment]
The users that report that might be hitting #61. If you open Firefox with a Facebook link from 3rd party app while having Facebook Container installed, you will probably see a Facebook login page each time. At least I think this is what I saw in @SoftVision-CiprianMuresan 's bug.

**Comment by englehardt** [comment]
If a user ever interacts with Facebook content in a third-party context, for example through "Login with Facebook" or a Facebook like button, it provides Facebook the opportunity to link their non-container cookies to their container cookies. They can embed their non-container tracking cookies in every link when embedded as a third party and wait for the user to interact with one of those links. The FB container extension will open the resulting page in the user's Facebook container, and the link between the cookies can be established. Once this link happens, Facebook can continue to track all of the user's non-container browsing.

We can remove the motivation to do so by reducing the worth of their non-container cookies. Either by regularly clearing them or by stripping them completely from all requests on non-container pages. At a first pass it seems like the latter suggestion won't cause any additional breakage beyond what the container extension already causes? I.e. Logins or interactions broken by blocking storage access will also be broken by containers?

**Comment by stoically** [comment]
@englehardt Excellent point. uMatrix actually [handles cookies that way too](https://github.com/gorhill/uMatrix/wiki/Cookies): Cookies are allowed to enter, but are never added to the Header. I can't think of any additional breakage either. Will look into implementing this using [onBeforeSendHeaders](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/onBeforeSendHeaders).

An open question at this point is whether we want to allow Facebook Cookies in Permanent Containers other than the Facebook Container. Currently only cookies in the Default Container are cleared. I'd personally be in favour of really only allowing Cookies in the Facebook Container and hence clearing and blocking them in Permanent Containers too.

**Comment by TanviHacks** [comment]
Yes, I dont see a reason to only wipe from default Container.  We should wipe facebook cookies from all non-Facebook Containers.

**Comment by TanviHacks** [comment]
And we could strip them so they are never sent in subresource requests.  But that is a bit harder, and would require more testing.
