### ISSUE TITLE
Filter By Containers

### ISSUE THREAD

**Issue by nicgentile** [mozilla/contain-facebook#743]
**Is your feature request related to a problem? Please describe.**
I run many different containers and find it a hassle having many tabs from different containers scattered across my browser.

**Describe the solution you'd like**
I would like to be able to filter the visual tabs by container, and hide the rest of that container is not being used making it easier to use. Also, it would be a plus to have a feature like the Auto Discard Tabs feature that suspends the tabs when the containers are being used this freeing up resources.

**Describe alternatives you've considered**
My current solution is to use profiles based on the task(s) at hand.

**Additional context**
Nope.

**Comment by maxxcrawford** [comment]
@nicgentile Hey there – this looks like this might be better filed over at the [Multi-account Containers](https://github.com/mozilla/multi-account-containers/) repo. (This add-on only offers support for the Facebook container)
