### ISSUE TITLE
Can't open Later.com in a Facebook container tab

### ISSUE THREAD

**Issue by quasiDigi** [mozilla/contain-facebook#744]
- Facebook Container Version: 2.1.2
- Operating System + Version: macOs 10.15.7 (19H524)
- Firefox Version: 86.0.1 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:
 - British English Dictionary (Marco Pinto)	dictionary	2.94	true	marcoagpinto@mail.telepac.pt
 - Dictionnaire français	dictionary	7.0b	true	fr-dicollecte@dictionaries.addons.mozilla.org
 - Spanish (Spain) Dictionary	dictionary	2.5	true	es-es@dictionaries.addons.mozilla.org
 - Woordenboek Nederlands	dictionary	3.1.2.1webext	true	nl-NL@dictionaries.addons.mozilla.org
 - Adblock Plus - free ad blocker	extension	3.10.2	true	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
 - Amazon.com	extension	1.3	true	amazondotcom@search.mozilla.org
 - Bing	extension	1.3	true	bing@search.mozilla.org
 - CSS Reloader	extension	1.2.0	true	cssreloader@kenneth.io
 - Dark Theme for YouTube™	extension	0.1.9	true	jid1-y4pUQrD6t1PJJa@jetpack
 - DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
 - eBay	extension	1.3	true	ebay@search.mozilla.org
 - Facebook Container	extension	2.1.2	true	@contain-facebook
 - Google	extension	1.1	true	google@search.mozilla.org
 - Stylus	extension	1.5.17	true	{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}
 - Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
 - English (GB) Language Pack	locale	86.0buildid20210222142601	true	langpack-en-GB@firefox.mozilla.org
 - Español (España) Language Pack	locale	86.0buildid20210222142601	true	langpack-es-ES@firefox.mozilla.org
 - Adobe Acrobat	extension	18.0.10	false	web2pdfextension.17@acrobat.adobe.com
 - FoxyProxy Standard	extension	6.6.2	false	foxyproxy@eric.h.jung
 - uBlock Origin	extension	1.34.0	false	uBlock0@raymondhill.net

### Actual behavior
When I open a Facebook container tab and enter "https://later.com" in the address bar, the tab transforms into a normal non-container tab. When I then right click on the tab and select> Reopen in Container > Facebook. A new tab opens, who has a flash of a Facebook container tab but finally switches to a normal non-container tab.

### Expected behavior
In both cases I expect https://later.com to stay in a Facebook container tab

### Steps to reproduce
Case A
1. Open an empty Facebook container tab 
2. Enter "https://later.com" into the address bar
3. Hit enter

Case B
1. Go to website "https://later.com"
2. Right click on the tab and choose option Reopen in Container > Facebook

### Notes
I need later.com to connect with my facebook account and do not want to disable the Facebook container tab. How can I do it? 
Thank you for the great work!

**Comment by maxxcrawford** [comment]
Hey there! Follow these directions [from the docs](https://github.com/mozilla/contain-facebook/blob/master/docs/container-management.md). Please reopen this if adding the site doesn't get your issue resolved. Thanks!

The RIght-Click > Reopen in Container may not work all the time for the Facebook Container. _(It's an artifact from the add-on it started from, Multi-account Containers)_

**Comment by quasiDigi** [comment]
@maxxcrawford now I feel really stupid. Thank you for holding my hand  ^)^
