### ISSUE TITLE
Wit.ai is now part of Facebook

### ISSUE THREAD

**Issue by liberatr** [mozilla/contain-facebook#746]
- Facebook Container Version: 2.1.2
- Operating System + Version: Mac OS 10.15.7
- Firefox Version: 86.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status: N/A

### Actual behavior
https://wit.ai website does not load

### Expected behavior
wit.ai website loads inside Facebook Container

### Steps to reproduce
1. visit https://wit.ai
2. Observe errors in console log
3. Observe blank screen

### Notes
Since this company was acquired by facebook, they are loading Javascript from Facebook domains that the site relies on to work, and it's not loading properly, I think this site needs to be included in the container to work.

**Comment by maxxcrawford** [comment]
Confirmed. We need to add it. 

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/2692333/112528608-5bbf8b80-8d72-11eb-8b78-ad7772cc4334.png">
