### ISSUE TITLE
The "Facebook" website can wrongly be opened in a normal tab if it is assigned to the MAC's "Facebook" container

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/contain-facebook#77]
**[Affected versions]:**
- Firefox 59.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the Firefox Multi-Account Containers add-on (6.0.0) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Go to the "about:addons" page and install the "Facebook Container" add-on (1.2.5).
3. Navigate to the https://www.facebook.com/ and click the "Multi-Account Containers" toolbar button.
4. Check the "Always open in Facebook" option and navigate to https://www.facebook.com/ in a new tab.
5. In the container confirmation tab click the "Open in Current Container" button.
6. Observe the behavior.

**[Expected result]:**
- The "Facebook" website is opened in the "Facebook" container.

**[Actual result]:**
- The "Facebook" website is opened in a normal tab.

**[Notes]:**
- If you will try to open a Facebook link from the normal tab, then the container confirmation page will be prompted again. After that if you will click the "Open in Current Container" button the website will be opened in a normal tab or if the "Open in Facebook Container" button will be clicked, then the website will be opened in the "Facebook" container.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/38089302-af305e06-3367-11e8-813a-37386e5a02d6.gif)

**Comment by stoically** [comment]
This is expected behavior since MAC assignments "overwrite" the Facebook Container functionality.

**Comment by groovecoder** [comment]
Agree with @stoically - the explicit user intent to use MAC to assign Facebook to their own container should override this add-ons implicit assumption.
