### ISSUE TITLE
Container not working on Mac

### ISSUE THREAD

**Issue by miqdadamirali** [mozilla/contain-facebook#81]
The cookie is getting cleared as it logs me out from an existing session but logging in does not open it a container. Tested against a Windows VM and worked right away.

MacBook Pro
Firefox 59.0.2 (64 bit)

**Comment by stoically** [comment]
Do you by chance have Multi-Account Containers installed on your Mac? And which version of Facebook Container are you running?

**Comment by miqdadamirali** [comment]
@stoically 
Facebook Container	1.2.5	true	@contain-facebook
Firefox Multi-Account Containers	6.0.0	true	@testpilot-containers

MacOS High Sierra
Version 10.13.3

**Comment by stoically** [comment]
Do you have facebook.com assigned using Multi-Account Containers? You can check by navigating to facebook.com and opening the MAC toolbar popup. "Always open in" needs to be unticked for Facebook Container to work.

**Comment by miqdadamirali** [comment]
It is unticked @stoically

**Comment by stoically** [comment]
Could you please do the following:

- Open a new tab and navigate to "about:debugging"
- Tick the "Enable debugging" checkbox
- Scroll down to Facebook Container and click the "Debug" link
- Confirm the dialog with OK, you now see "Developer Tools" with "Console" selected
- Type into the console `(async () => console.log(await browser.runtime.sendMessage("@testpilot-containers", {method: "getAssignment", url: "https://www.facebook.com"})))();` and confirm with Enter
- Copy and Paste the result of the what's logged into the Console as Comment here
- Close Developer Tools
- Untick "Enable debugging" again

**Comment by stoically** [comment]
Also - to check whether your Issue indeed roots in the combination of Multi-Account Containers and Facebook Container, you could try disabling MAC, then navigate to facebook and see if it works as expected.

**Comment by stoically** [comment]
Can you also check in your Firefox Options/Preferences under "Tabs" if you see a greyed out but ticked checkbox with the description "Enable Container Tabs"? If not, please let me know and check this comment: https://github.com/mozilla/contain-facebook/issues/84#issuecomment-377534108

**Comment by maciejwalkowiak** [comment]
I am facing same issue. "Enable Container Tabs" is ticket and grayed out, I don't use MAC.

Here is the result of executing this piece of code in debug mode:
![image](https://user-images.githubusercontent.com/1357927/38177048-4e53d046-35fa-11e8-9b99-cafc01fdd8b1.png)

**Comment by stoically** [comment]
@maciejwalkowiak Do you by chance have "Firefox will: Never remember history" activated in the Firefox Preferences/Options under "History"?

**Comment by bodhi1970** [comment]
It has worked once I activated the add-on but since leaving facebook and logging in again the blue bar in the tab does not show up anymore, so I don’t know if the container is working or not.

**Comment by maciejwalkowiak** [comment]
@stoically indeed! After making it remember history I was able to sign-in in container mode. 

I am not sure though if it works as intended. I would expect that I am not able to "login with facebook" to 3rd party sites, but I works as it used to (tested with Wunderlist and Endomondo).

**Comment by bodhi1970** [comment]
What is the purpose of remembering the history for the container? Why is it important to keep that option on?

**Comment by stoically** [comment]
@maciejwalkowiak It does. What happens is, that the popup (or redirection) to the Facebook Login page is reopened into the Facebook Container and that allows you to login. Needed tokens for the initial Auth are passed back and forth in the URL Query in this case and don't rely on cookies and that's why it works. After that the site you're logging in handles your logged in state and doesn't rely on Facebook cookies.

@bodhi1970 "Never remember history" starts Firefox in Private Browsing Mode (Private Windows) - and the Container Feature [isn't available in Private Windows](https://github.com/mozilla/multi-account-containers/issues/469).

@miqdadamirali Could you check if you maybe also have "Never remember history" active?

**Comment by stoically** [comment]
@miqdadamirali No problem, glad it works now
