### ISSUE TITLE
Open external links in default container (no container)

### ISSUE THREAD

**Issue by alekksander** [mozilla/contain-facebook#85]
This extension has to be answer for mozilla's surveys. apparently lots of folks isolate social media from regular browsing. but… i can't see how this extension isn't duplicating functionality of regular containers extensions. i suggest this extension to have a build–in option to open external links (from wall of chat) in default container (no container). otherwise it's just even less than regular containers offer – it lacks of custom name and icon ;)

**Comment by stoically** [comment]
Thanks for the feedback. You can still install [Multi-Account Containers](https://addons.mozilla.org/firefox/addon/multi-account-containers/) alongside Facebook Container and benefit from the additional features. Just make sure that you don't assign facebook domains to a container using MAC, or you'll lose the functionality of opening external links in the default container.

Regarding the "external link in default container"-functionality in MAC, please add your vote here: https://github.com/mozilla/multi-account-containers/issues/847
