### ISSUE TITLE
CSS fonts rules overrides website ones

### ISSUE THREAD

**Issue by noreiller** [mozilla/contain-facebook#857]
- Facebook Container Version: 2.3.3
- Operating System + Version: Ubuntu 22.04
- Firefox Version: 101.0
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
When enabling this extension, other websites have graphic issues due this part of the extension: https://github.com/mozilla/contain-facebook/blob/main/src/content_script.css#L12-L15.

### Expected behavior
No graphic impact on other websites.

### Steps to reproduce
1. Enable the extension
2. Visit any website
3. The font rules applied are not the one setup by the website

**Comment by mvdve** [comment]
The contain facebook extension adds a global stylesheet with the code:
`body {
  --blue60: #0060df;
  --blue70: #003eaa;
  --primaryText: #15141A;
  --secondaryText: #5B5B66;
  --grey20: #ededf0;
  --light-gray: #F0F0F4;
  --white: #ffffff;
  --transition: all .15s cubic-bezier(.07,.95,0,1);
  --borders: 1px solid #ededf0;
  font-size: 13px;
  font-weight: 400;
  color: #15141A;
  font-family: "SF Pro Text", 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;`

This stylesheet overrules the sheet from the website and so resets the font size.

See commit [c8c92e2ff21576931a5046b96fad839f7aa9151a](https://github.com/mozilla/contain-facebook/commit/c8c92e2ff21576931a5046b96fad839f7aa9151a) where the changes where added.

#840

**Comment by lisenet** [comment]
Same problem here. Started this morning after upgrade to 2.3.3, disabling the extension fixes the problem.

**Comment by adrian-pasten** [comment]
Same here the file content_script.css overwrite any changes on other website

**Comment by milutinke** [comment]
> Here's a manual how to downgrade it [#858 (comment)](https://github.com/mozilla/contain-facebook/issues/858#issuecomment-1240543085)

Thanks

**Comment by ann4belle** [comment]
How the hell does this even happen?

**Comment by ann4belle** [comment]
How the hell does something like this make it into a full release?

**Comment by lisenet** [comment]
> How the hell does something like this make it into a full release?

Lack of testing and QA.

**Comment by superlou** [comment]
> Thanks @rittme for the [PR](#860)

@noreiller, did you mean to link to #860?

**Comment by noreiller** [comment]
> > Thanks @rittme for the [PR](#860)
> 
> @noreiller, did you mean to link to #860?

Yes, thanks... :sweat_smile:  It's updated now.

**Comment by zelch** [comment]
#863 is the same issue.

**Comment by bakulf** [comment]
Version 2.3.3 was buggy and, as a temporary fix, we just released a v2.3.4 as a v2.4.2 repackaged. Please, update the add-on to have a fix for this issue.
All the features introduced by v2.3.3 will be released in v2.3.5 as soon as possible.
