### ISSUE TITLE
content_script.css turns body text to black globally

### ISSUE THREAD

**Issue by aaronsantiago** [mozilla/contain-facebook#866]
My local installation of the Facebook Container plugin includes a content_script.css with this text:
```
body {
    --blue60: #0060df;
    --blue70: #003eaa;
    --primaryText: #15141A;
    --secondaryText: #5B5B66;
    --grey20: #ededf0;
	--light-gray: #F0F0F4;
	--white: #ffffff;
    --transition: all .15s cubic-bezier(.07,.95,0,1);
    --borders: 1px solid #ededf0;
	font-size: 13px;
	font-weight: 400;
	color: #15141A;
    font-family: "SF Pro Text", 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
}
```

Turning the text on many websites, including GitHub and Slack, black. In dark mode these sites become unreadable.

Available workarounds:

- Mod the extension to remove the CSS
- Disable the extension
- Use a global Userstyle that changes text colors (such as https://userstyles.world/style/5535/gruvbox-dark-soft-global)

**Comment by divyeshsachan** [comment]
I confirm this issue.
Extension is injecting css file in all tabs which is causing pages in all tabs to change font/size, etc.... This is happening with today's release of 2.3.3.

**Comment by dylemma** [comment]
![image](https://user-images.githubusercontent.com/1355958/189150679-1f837c92-0c9d-4b0a-952f-d296d7467c86.png)
Can confirm 🤣

**Comment by ubald** [comment]
Changing the color in the inspector makes it persist across reloads too.

**Comment by weaversam8** [comment]
Is it possible to rollback 2.3.3? Or do they need to create a new release?

**Comment by dylemma** [comment]
Changing in the inspector seems to work, but on a per-domain basis. I fixed it on one site in the inspector, and it persists as @ubald said, but the issue is still present on other sites.

**Comment by aaronsantiago** [comment]
Another workaround is to use Stylus etc. with a global userstyle. I use global dark style

**Comment by weaversam8** [comment]
It looks like they've already released a patched version, 2.3.4: https://addons.mozilla.org/en-US/firefox/addon/facebook-container/versions/

Uninstalling and reinstalling the extension should fix it.

**Comment by xigoi** [comment]
How did this even happen?

**Comment by andyross63** [comment]
Looking in the pulls section, it looks like 2.3.4 is actually just 2.3.2 repackaged.

**Comment by groovecoder** [comment]
Thanks everyone for the quick feedback on this. We will be more diligent about testing website compatibility in the future.

90K users received the buggy 2.3.3 version, and now 109K users are on the latest 2.3.4 (i.e., the rollback) version. 1.1M users are still on 2.3.2, but their next update should jump them straight to 2.3.4 instead of the buggy 2.3.3.

We are working on a full fix to include the security improvements, performance improvements, AND the bug-fix for the styling issue.
