### ISSUE TITLE
Suggestion: Fingerprint default icon instead of briefcase

### ISSUE THREAD

**Issue by karolyipeter** [mozilla/contain-facebook#87]
I think the "fingerprint" icon would be much more fitting than the current "briefcase" one. The fingerprint icon is much more related to privacy which is the main goal of this project.

**Comment by ryanfeeley** [comment]
Hi @karolyipeter, the official icon for auto-containers is the fence icon. We just weren't able to get it into Firefox in time (and the add-on can't add it where we need it).

It will look something like this: 
![image-1](https://user-images.githubusercontent.com/68213/38153810-905dba7a-343c-11e8-81ca-252cbba88ad2.png)

**Comment by karolyipeter** [comment]
Thanks for the answer! I can definitely get behind that icon
