### ISSUE TITLE
Block facebook.com cookies when it is a subresource

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/contain-facebook#9]
If a webpage attempts to load facebook.com as a third party, intercept the request and response and remove cookies from them.  This way facebook.com won't be able to set a logged-out user cookie and track the user across the web that way.  Later, facebook won't be able to tie that logged-out user to a real user in the backend by cookie-syncing or using other techniques.

However, facebook could still i) set site storage (ex: localstorage) and track the logged-out user across page loads that way, or ii) fingerprint the browser and identify the user (including the users logged in identity that is separated into the facebook container).  https://github.com/mozilla/contain-facebook/issues/3 is more full proof, but would cause more breakage (ex: reading other peoples facebook comments) and is harder to implement.

**Comment by groovecoder** [comment]
Marking as enhancement, and probably out of scope for this add-on? This is probably a wider change we could make to platform Tracking Protection?

**Comment by maxxcrawford** [comment]
This was/is a 2.X feature.
