### ISSUE TITLE
Wrong Version of Firefox

### ISSUE THREAD

**Issue by Mithrandir-Earendur** [mozilla/contain-facebook#90]
Cannot seem to add Facebook Container to Firefox. It detects I have the wrong version.
 I have version 59.0.2 I have re-downloaded Firefox to see if that was the issue, it was not.
it prompts this error:

> This add-on requires a newer version of Firefox (at least version 57.0). You are using Firefox 52.0.

  
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No.
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: No.
- Facebook Container Version: N/A
- Operating System + Version: Windows 8.1
- Firefox Version: 59.0.2
- Other installed Add-ons + Version + Enabled/Disabled-Status: 
     -CanvasBlocker	0.4.4b true	
     -HTTPS Everywhere	2018.3.13	true	
     -minerBlock	1.2.0	true	
     -Privacy Badger	2018.3.21	true	
     -Reddit Enhancement Suite	5.10.3 true	
     -uBlock Origin	1.15.18	true	
     -Avast Online Security	12.0.296	false	
     -Avast SafePrice	12.0.579	false

**Comment by stoically** [comment]
That sounds like you have `privacy.resistFingerprinting` enabled in `about:config`. Can you check if that's the case?

**Comment by Mithrandir-Earendur** [comment]
Seems like privacy.resistFingerprinting was set to true. It fixed it thank you.
