### ISSUE TITLE
Issue with GOG.com

### ISSUE THREAD

**Issue by ktamp** [mozilla/contain-facebook#911]
Facebook Container v2.3.9 breaks some functionality on GOG.com.
Facebook Container v2.3.6 works just fine.

- Facebook Container Version: 2.3.9
- Operating System + Version: Arch Linux
- Firefox Version: 108.0.2

GOG.com enables to hide games. Hidden games have a "hidden" attribute and are displayed semi-transparent.

### Actual behavior
Hidden games are not displayed at all.
The list of hidden games is empty.

### Expected behavior
Hidden games are displayed semi-transparent.

### Steps to reproduce
1. This would require an account on GOG.com.
2. Select [Profile] > Games.
3. Go to the bottom right corner of a game, click oh the down arrow and select "HIDE GAME".
4. Click on the down arrow next to "MY COLLECTION" and select "HIDDEN".

### Notes
Facebook Container v2.3.6 does not have this issue.
Facebook Container does not detect any Facebook trackers on GOG.com.
Adding GOG.com to the Allowed Pages list of Facebook Container v2.3.9 does not fix this issue.

**Comment by maxxcrawford** [comment]
#896 will resolve this, but we need to release a new submission of FBC. I'll get that scheduled. Confirmed on my on GOG.com account: 

With FBC: 
![image](https://user-images.githubusercontent.com/2692333/221218980-071ea84d-37c8-48a2-84bd-bda513b1ecb5.png)

Without FBC: 
![image](https://user-images.githubusercontent.com/2692333/221219100-9eb64e09-24eb-47bd-bddf-b7518fd9f7b8.png)

**Comment by krystian3w** [comment]
https://github.com/mozilla/contain-facebook/issues/886 https://github.com/mozilla/contain-facebook/issues/898

**Comment by krystian3w** [comment]
https://github.com/mozilla/contain-facebook/issues/919
