### ISSUE TITLE
endless loop, need closing firefox

### ISSUE THREAD

**Issue by 4m1r** [mozilla/contain-facebook#92]
The endless loop of tab switching occurs when, firefox has container extension as well as contain-facebook and container extension has facebook assigned to a container. Now if a user opens facebook, there is a endless loop between both extension for assignment.

**Comment by stoically** [comment]
Please provide all asked informations from the Issue template: https://github.com/mozilla/contain-facebook/issues/new

**Comment by maxxcrawford** [comment]
Closing this issue for now. @4m1r Please reopen with details on how to reproduce.  Thanks!
