### ISSUE TITLE
"Open Link In New Container Tab" options on right clicking a link

### ISSUE THREAD

**Issue by yashpunjabi** [mozilla/contain-facebook#93]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes
- Facebook Container Version: Facebook Container 1.2.5
- Operating System + Version: Windows 10
- Firefox Version: 59.0.2 (64 bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status: 

Bitwarden - Free Password Manager	1.25.7	true	{446900e4-71c2-419f-a6a7-df9c091e268b}
Facebook Container	1.2.5	true	@contain-facebook
Momentum	0.99.5	true	momentum@momentumdash.com
Reddit Enhancement Suite	5.10.3	true	jid1-xUfzOsOFlzSOXg@jetpack
uBlock Origin	1.15.18	true	uBlock0@raymondhill.net

### Actual behavior
When you right click a link it shows the option to "Open link in new container tab" and on hovering gives options such as "Personal", "Work", "Facebook", etc.

### Expected behavior
Since this is not the full Containers extension but only the Facebook container extension, it shouldn't allow me to open a tab in, say, a "Personal" container. It should only allow it to be opened in the facebook container (or maybe not show the option at all and open facebook links in a facebook container automatically).

### Steps to reproduce
1. Right click a hyper-link

![Screenshot](https://user-images.githubusercontent.com/6287950/38178913-2aee3624-35ea-11e8-8f96-de7dcd08231e.png)

**Comment by krystian3w** [comment]
Addon actuvate all contextual function hiden in browser.

If no use other containers you can hide it with `userChrome.css` (right click menu link, long press new tab button, Firefox menu).

**Comment by SoftVision-PaulOiegas** [comment]
I think this issue is a dupe of #31.

**Comment by TanviHacks** [comment]
This looks like a duplicate of #26

**Comment by krystian3w** [comment]
Yep we are right
