### ISSUE TITLE
is-hidden selector added globaly by Facebook Container

### ISSUE THREAD

**Issue by materreni** [mozilla/contain-facebook#934]
- Facebook Container Version: 2.3.9
- Operating System + Version: Mac Ventra 13.4.1
- Firefox Version: 114.0.2
- Other installed Add-ons + Version + Enabled/Disabled-Status: Facebook Container 2.3.9

### Actual behavior

Since Firefox 108 (Win/Mac with Facebook Container add-on enabled), Facebook Container is adding this un-encapsulated ".is-hidden" selector to a page's css. This might affect a given website's behavior in terms of styling/js as this is a quite common naming choice for projects that use css.  

In my case .is-hidden was adding an extra display: none rule to a selector inside a component that only needed to use visibility:hidden

### Expected behavior

Maybe use .fcb-is-hidden?

<img width="2048" alt="Screenshot 2023-06-26 at 14 37 09" src="https://github.com/mozilla/contain-facebook/assets/75451444/fbad4980-5b9e-40ea-b939-ee8d966f2db3">

**Comment by dannycolin** [comment]
Thank you for reporting. This seems to be a duplicate as #927 so closing in favor of it.
