### ISSUE TITLE
New release needed for launch of threads.net

### ISSUE THREAD

**Issue by JoshTumath** [mozilla/contain-facebook#940]
Now that threads.net has been launched and support for it has been added in #936, a new release of the Facebook Container addon is needed to support the new domain name.

Can I request the maintainers publish a new release ASAP?

**Comment by maxxcrawford** [comment]
I submitted the new release candidate to internal QA. I'll post back.

For now, I recommend everyone [follow the steps outlined here](https://github.com/mozilla/contain-facebook/blob/main/docs/container-management.md#add-a-site) to add the Threads domain to your contained sites list.

**Comment by Kopilut** [comment]
https://www.threads.net/ works in Facebook container, however it is not listed on included sites list in the plugin.
![image](https://github.com/user-attachments/assets/0231bba9-757a-4255-be7b-bc4985dad973)
