### ISSUE TITLE
Please allow this extension run while private browsing

### ISSUE THREAD

**Issue by khewweifeng** [mozilla/contain-facebook#967]
**Is your feature request related to a problem? Please describe.**
`Please allow this extension run while private browsing`

**Describe the solution you'd like**
`Please allow this extension run while private browsing`

**Describe alternatives you've considered**
`Please allow this extension run while private browsing`

**Additional context**
`Please allow this extension run while private browsing`

**Comment by dannycolin** [comment]
Duplicate of #810
