### ISSUE TITLE
Feature request: Include messenger.com

### ISSUE THREAD

**Issue by maidik** [mozilla/contain-facebook#97]
It appears the container doesn't work for messenger.com, which uses the same login/tracking.  Would it be possible to include messenger.com?

**Comment by pdehaan** [comment]
I believe this was already covered in PR https://github.com/mozilla/contain-facebook/pull/52, and should be included in our upcoming release:

https://github.com/mozilla/contain-facebook/blob/1e37bc677acda63e4621d79677131aed9059e1e3/background.js#L5-L9

**Comment by krystian3w** [comment]
Add `fb.me`

**Comment by pdehaan** [comment]
> Add fb.me

Filed #108
